### ISSUE TITLE
Add AFNI 3dDespike to nuisance

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1002]

**Comment by a3sha2** [comment]
@SucyLi @HechengJin0  is there anything to be done here?
 
what is the most important is the despiking of  nuisance regressors

**Comment by a3sha2** [comment]
we always convert the nuisance regressors  to  nifiti and a apply despiking.  but this code is in bash. I can write in python https://github.com/PennBBL/xcpEngine/blob/cd21531d547d64d7add94769366af0f92b8c9a54/utils/1dDespike

**Comment by SucyLi** [comment]
> @SucyLi @HechengJin0 is there anything to be done here?
> 
> what is the most important is the despiking of nuisance regressors

I added a despike option in func_preproc.py just right after motion correction

**Comment by SucyLi** [comment]
Only AFNI 2017 or later version has 3ddespike, but due to 3dTCorr crash in AFNI 2018 and lack of AFNI 2017 resource, C-PAC is using AFNI 2016 now. We'll implement 3ddespike once AFNI latest version becomes stable.

**Comment by sgiavasis** [comment]
Moving this to 1.6.1.
Also, see #1104
