### ISSUE TITLE
working directory confusion in the docker 

### ISSUE THREAD

**Issue by tbweng** [FCP-INDI/C-PAC#1020]
The quickstart guide suggests that the directory /tmp should be mapped to /scratch (-v /tmp:/s cratch) presumable for the working directory. But the default pipeline uses /tmp as the working directory. Run.py specifically puts crash files in the /scratch directory, but doesn't change the working_dir to be /scratch as well. These should be made consistent, ideally by having the working directory specifically set to /scratch in run.py.

**Comment by sgiavasis** [comment]
This is in v1.6.1.
Thanks again @pn2200
