### ISSUE TITLE
bc and vim command not in Docker container

### ISSUE THREAD

**Issue by tbweng** [FCP-INDI/C-PAC#1024]
`vim` can be installed with `apt-get` in the container.

However, `bc` cannot:

```
root@6fa32f8d91ac:/# apt-get install bc
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package bc
```

**Comment by anibalsolon** [comment]
Hi @tbweng 

We clean up the package cache of apt during image building, to make the docker image smaller.

You can run `apt-get update && apt-get install bc` to rebuild the cache of existing packages!

**Comment by tbweng** [comment]
Thanks @anibalsolon! That worked.
