### ISSUE TITLE
libz.so.1: version `ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by ikimura09** [FCP-INDI/C-PAC#1040]
Hi!
I'm trying to install cpac in my Ubuntu 18.04 PC, using the following link.(https://fcp-indi.github.io/docs/user/install.html# )Everything seemed fine at that time, however when I entered cpac_gui I got the following error.

CPAC was imported and can be used, but wxPython was not found. In order to use the GUI, wxPython must be installed.
Error: /home/ikko/miniconda/lib/python2.7/lib-dynload/../../libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
Traceback (most recent call last):
  File "/home/ikko/miniconda/bin/cpac_gui", line 5, in <module>
    CPAC.GUI.run()
  File "/home/ikko/miniconda/lib/python2.7/site-packages/CPAC/GUI/mainUI.py", line 13, in run
    app = wx.App()
NameError: global name 'wx' is not defined

I thought I should symlink "libz.so.1", but I don't which to symlink.Here is the output of "locate libz.so.1"
/home/ikko/miniconda/envs/cpac/lib/libz.so.1
/home/ikko/miniconda/envs/cpac/lib/libz.so.1.2.11
/home/ikko/miniconda/lib/libz.so.1
/home/ikko/miniconda/lib/libz.so.1.2.8
/home/ikko/miniconda/pkgs/zlib-1.2.11-0/lib/libz.so.1
/home/ikko/miniconda/pkgs/zlib-1.2.11-0/lib/libz.so.1.2.11
/home/ikko/miniconda/pkgs/zlib-1.2.8-0/lib/libz.so.1
/home/ikko/miniconda/pkgs/zlib-1.2.8-0/lib/libz.so.1.2.8
/lib/x86_64-linux-gnu/libz.so.1
/lib/x86_64-linux-gnu/libz.so.1.2.11
/snap/core/7270/lib/x86_64-linux-gnu/libz.so.1
/snap/core/7270/lib/x86_64-linux-gnu/libz.so.1.2.8
/snap/core/7396/lib/x86_64-linux-gnu/libz.so.1
/snap/core/7396/lib/x86_64-linux-gnu/libz.so.1.2.8
/snap/core18/1066/lib/x86_64-linux-gnu/libz.so.1
/snap/core18/1066/lib/x86_64-linux-gnu/libz.so.1.2.11
/snap/core18/1074/lib/x86_64-linux-gnu/libz.so.1
/snap/core18/1074/lib/x86_64-linux-gnu/libz.so.1.2.11
/usr/local/bin/miniconda/envs/cpac/lib/libz.so.1
/usr/local/bin/miniconda/envs/cpac/lib/libz.so.1.2.11
/usr/local/bin/miniconda/lib/libz.so.1
/usr/local/bin/miniconda/lib/libz.so.1.2.8
/usr/local/bin/miniconda/pkgs/zlib-1.2.11-0/lib/libz.so.1
/usr/local/bin/miniconda/pkgs/zlib-1.2.11-0/lib/libz.so.1.2.11
/usr/local/bin/miniconda/pkgs/zlib-1.2.8-0/lib/libz.so.1
/usr/local/bin/miniconda/pkgs/zlib-1.2.8-0/lib/libz.so.1.2.8
/usr/local/fsl/bin/FSLeyes/libz.so.1
/usr/local/fsl/fslpython/envs/fslpython/lib/libz.so.1
/usr/local/fsl/fslpython/envs/fslpython/lib/libz.so.1.2.11
/usr/local/fsl/fslpython/lib/libz.so.1
/usr/local/fsl/fslpython/lib/libz.so.1.2.11
/usr/local/fsl/fslpython/pkgs/zlib-1.2.11-h7b6447c_3/lib/libz.so.1
/usr/local/fsl/fslpython/pkgs/zlib-1.2.11-h7b6447c_3/lib/libz.so.1.2.11

Could you tell me which to change?

Thanks in advance!

**Comment by Aaronearlerichardson** [comment]
Having a similar issue here. I had the same error when running "cpac gui" in terminal. I'm running Ubuntu 18.04 on a virtual machine and I've tried running these commands:
```
sudo apt install make gcc libgtk-3-dev libwebkitgtk-dev libwebkitgtk-3.0-dev libgstreamer-gl1.0-0 freeglut3 freeglut3-dev python-gst-1.0 python3-gst-1.0 libglib2.0-dev ubuntu-restricted-extras libgstreamer-plugins-base1.0-dev
sudo apt-get install python-wxgtk3.0
```
as per these answers [https://askubuntu.com/questions/1073145/how-to-install-wxpython-4-ubuntu-18-04](url)

Which changed the errors to this when I run " cpac gui " in the terminal
```
CPAC was imported and can be used, but wxPython was not found. In order to use the GUI, wxPython must be installed.
Error: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/bin/cpac", line 5, in <module>
    main()
  File "/home/aaron/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aaron/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aaron/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aaron/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aaron/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/__main__.py", line 45, in gui
    CPAC.GUI.run()
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/mainUI.py", line 15, in run
    app = wx.App()
NameError: global name 'wx' is not defined
```

and when I try importing wx in a python terminal I get this:
```
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "wx/_core.py", line 4, in <module>
    import _core_
ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
```

**Comment by shnizzedy** [comment]
Deprecated by #1262
