### ISSUE TITLE
aCompCorr's working directory is way too big!

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#1053]
https://github.com/FCP-INDI/C-PAC/blob/448cbf0cafa9a15823b5289f9beb237f77ba2ce9/CPAC/nuisance/nuisance.py#L1052

DetrendPC's current implementation results in multiple versions of the functional data to be written out at higher resolution. This can account up to 50% of the entire size of the working directory. The pipeline of 3dDetrend -> 3dTstat -> 3dCalc -> 3dPC can either be replaced by python code that would do all of these operations in memory, or a single call to [3dmaskSVD](https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dmaskSVD.html) with the appropriate command line arguments.

Here is an example for data from rockland sample, for reference compressed task_test raw data is 62.4 MB and task_train is 27.4 MB. 

111 | ./nuisance_1_0/_scan_test/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_standarized/sub-M10978008_ses-NFB3_task-test_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 2.4G
-- | -- | --
112 | ./nuisance_1_0/_scan_test/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_detrend/sub-M10978008_ses-NFB3_task-test_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 2.4G
516 | ./nuisance_0_0/_scan_test/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_standarized/sub-M10978008_ses-NFB3_task-test_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 2.4G
517 | ./nuisance_0_0/_scan_test/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_detrend/sub-M10978008_ses-NFB3_task-test_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 2.4G
1251 | ./nuisance_2_0/_scan_test/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2/aCompCor_standarized/sub-M10978008_ses-NFB3_task-test_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 2.4G
1252 | ./nuisance_2_0/_scan_test/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2/aCompCor_detrend/sub-M10978008_ses-NFB3_task-test_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 2.4G
166 | ./nuisance_1_0/_scan_train/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_standarized/sub-M10978008_ses-NFB3_task-train_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 1.1G
167 | ./nuisance_1_0/_scan_train/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_detrend/sub-M10978008_ses-NFB3_task-train_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 1.1G
575 | ./nuisance_0_0/_scan_train/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_standarized/sub-M10978008_ses-NFB3_task-train_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 1.1G
576 | ./nuisance_0_0/_scan_train/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_detrend/sub-M10978008_ses-NFB3_task-train_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 1.1G
1309 | ./nuisance_2_0/_scan_train/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2/aCompCor_standarized/sub-M10978008_ses-NFB3_task-train_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 1.1G
1310 | ./nuisance_2_0/_scan_train/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2/aCompCor_detrend/sub-M10978008_ses-NFB3_task-train_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 1.1G
137 | ./nuisance_1_0/_scan_morald/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_standarized/sub-M10978008_ses-NFB3_task-morald_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 856M
138 | ./nuisance_1_0/_scan_morald/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_detrend/sub-M10978008_ses-NFB3_task-morald_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 856M
544 | ./nuisance_0_0/_scan_morald/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_standarized/sub-M10978008_ses-NFB3_task-morald_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 856M
545 | ./nuisance_0_0/_scan_morald/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/aCompCor_detrend/sub-M10978008_ses-NFB3_task-morald_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 856M
1279 | ./nuisance_2_0/_scan_morald/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2/aCompCor_standarized/sub-M10978008_ses-NFB3_task-morald_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend_calc.nii | 856M
1280 | ./nuisance_2_0/_scan_morald/_selector_CSF-2mmE-M_aC-WM-2mm-DPC5_G-M_M-SDB_P-2/aCompCor_detrend/sub-M10978008_ses-NFB3_task-morald_bold_calc_tshift_resample_volreg_calc_maths_flirt_detrend.nii | 856M

**Comment by sgiavasis** [comment]
This has been resolved.
