### ISSUE TITLE
use more descriptive strings in pipeline configuration file

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#1061]
https://github.com/FCP-INDI/C-PAC/blob/448cbf0cafa9a15823b5289f9beb237f77ba2ce9/dev/docker_data/default_pipeline.yml#L641

For example on the previous line, rather than True and False to indicate that 'degree' and 'binary' centrality should be calculated, should use the strings 'degree' and 'binary'

**Comment by shnizzedy** [comment]
resolved in https://github.com/FCP-INDI/C-PAC/pull/1461
