### ISSUE TITLE
needless duplication in ROI extract timeseries

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#1066]
There is needless duplication of nodes between the 'CPAC' time series extraction and the 'NDMG' time series extraction, as exemplified by the following two lines that do the exact same thing:

https://github.com/FCP-INDI/C-PAC/blob/63c66c3b1d5e3f662ce2ffb521598364805156e4/CPAC/pipeline/cpac_pipeline.py#L3070

https://github.com/FCP-INDI/C-PAC/blob/d31f959ebf49a8859976b7dba3c8076dea4e0ea8/CPAC/pipeline/cpac_pipeline.py#L2983

What is the difference in how NDMG and CPAC extract time series?

**Comment by sgiavasis** [comment]
ndmg formats the information to be used in their graph generation code further down.

We can possibly just update the graph generation code to take in the output of C-PAC's TSE and shape it into the shape it wants.
