### ISSUE TITLE
import func_preproc Error

### ISSUE THREAD

**Issue by Devika-k** [FCP-INDI/C-PAC#1095]
Hi,
I want to preprocess Resting-state fMRI data

I get this error when I tried to import  func_preproc after installing CPAC in the ipython notebook.
Python version:- 2.7
Platform:- Google colab

Steps followed are listed below

1) git clone https://github.com/FCP-INDI/C-PAC.git

2) python setup.py install

3) import CPAC
import nilearn
import fsl
import nibabel
import nipype
import yaml

Nilearn version:- 0.5.2
Nibabel version:- 2.3.3
Fsl version:- 2.7.0
Nipype version:- 1.3.1
CPAC version:- 1.5.0

No errors while importing all these packages

4) Ran the following python files
python __init__.py
python utils.py
python func_preproc.py

No errors while running the above programs.

5) I tried to import func_preproc to run the following example 

>>> import func_preproc
>>> preproc = create_func_preproc(bet=True)
>>> preproc.inputs.inputspec.func='sub1/func/rest.nii.gz'
>>> preproc.run() #doctest: +SKIP

When I tried to import func_preproc I got the following error

/content/C-PAC/CPAC/func_preproc/func_preproc.py in <module>()
      9 from nipype.interfaces.afni import utils as afni_utils
     10 
---> 11 from CPAC.func_preproc.utils import add_afni_prefix, nullify
     12 
     13 

ImportError: No module named func_preproc.utils

Thanks in advance

**Comment by sgiavasis** [comment]
Hi @Devika-k ,

First to check- are you looking to run some basic preprocessing? If so, C-PAC's recommended usage is via containerized apps like Docker or Singularity- see our quick-start guide:
http://fcp-indi.github.io/docs/user/quick.html

However, if you are looking to run specific sub-parts of the pipeline manually, and need some more background info regarding the codebase, let me know and we can continue to assist.

Best,
Steve

**Comment by nx10** [comment]
Outdated
