### ISSUE TITLE
Note about smoothing in vmhc.py 

### ISSUE THREAD

**Issue by joyswe** [FCP-INDI/C-PAC#1100]
Hi!
In vmhc.py the notes about smoothing says that :
        fslmaths rest_res_filt.nii.gz
        -kernel gauss FWHM/ sqrt(8-ln(2))
        -fmean -mas rest_mask.nii.gz
        rest_res_filt_FWHM.nii.gz

Should this be sqrt(8*ln(2)) ?

**Comment by sgiavasis** [comment]
Hello @joyswe,

Yes, it should- this was fixed via @pn2200 's add:
https://github.com/FCP-INDI/C-PAC/pull/1143

Best,
Steve
