### ISSUE TITLE
KeyError: u'ndmg_graph'

### ISSUE THREAD

**Issue by cbin-cnl** [FCP-INDI/C-PAC#1110]
Hi, 

I'm using the fcpindi/c-pac docker instance (version 1.5.0) to run a preprocessing pipeline, but I keep getting the error: 

File "/code/CPAC/utils/symlinks.py", line 255, in create_paths_to_symlinks
    output_group = output_renamings[output_name]
KeyError: u'ndmg_graph'

Has anyone encountered this issue before? I don't believe I am using "ndmg_mode". 

For reference, I pulled the docker image earlier today, and am using Ubuntu 16.04. 

Thank you.

**Comment by arosas5** [comment]
The same has happened to me too.

**Comment by sgiavasis** [comment]
Hi @cbin-cnl and @arosas5,

Could you try re-pulling the latest container and trying again? I would like to see if it still happens.

If so, please let me know and we'll put this on high priority.

Best,
Steve

**Comment by arosas5** [comment]
Hey @sgiavasis ,
 I pulled the latest singularity image (1.6.0) from Shub. I ran the same pipeline with runSymbolicLinks enabled. The linking error for KeyError: u'ndmg_graph' is gone but I have a new error that was not present before.
Here is the recent run with 1.6.0 with runSymbolicLinks enabled.
[crash-pypeline.log](https://github.com/FCP-INDI/C-PAC/files/4031512/crash-pypeline.log)

Here is my previous run with 1.5.0 without runSymbolicLinks enabled.
[pypeline.log](https://github.com/FCP-INDI/C-PAC/files/4031556/pypeline.log)


Best,
Alberto

**Comment by cbin-cnl** [comment]
Thanks @sgiavasis .
I've pulled the latest docker image, and it looks like the "ndmg_graph" error still exists. It looks like the error is in the code for extracting a time series from an image. 

Thank you.

**Comment by sgiavasis** [comment]
Thank you both, this information is helpful.
Will get back to you shortly.

**Comment by sgiavasis** [comment]
@arosas5 - I'm going to create a new issue for your new error. We will take a look.
@cbin-cnl - does it still happen if you turn off runSymbolicLinks ?

**Comment by sgiavasis** [comment]
Actually, @arosas5 - do you also get that new error with runSymbolicLinks turned off?

**Comment by sgiavasis** [comment]
@arosas5 @cbin-cnl 
Hello!

Could you please try repulling and trying again? We have released version 1.6.1 and this should no longer occur. If it does, let me know and we'll address.

Thank you!
Steve
