### ISSUE TITLE
Python 2 -> 3 conversion

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1114]
- [ ] Assess scope
- [ ] Convert where necessary
- [ ] Employ a code checker
- [ ] Test any functionality that was touched

**Comment by HechengJin0** [comment]
https://docs.python.org/2/library/2to3.html

**Comment by shnizzedy** [comment]
I started [a branch for upgrading from Python 2 to 3](https://github.com/FCP-INDI/C-PAC/tree/upgrade/python3). 

Changes in this branch so far:

* :arrow_up: neurodebian xenial → bionic https://github.com/FCP-INDI/C-PAC/blob/8aafe735171d9b876d03bbf3d5a1c3220fdc0f7d/Dockerfile#L2
* :arrow_up: miniconda 2-3.8.3 → 3-4.7.12.1 https://github.com/FCP-INDI/C-PAC/blob/8aafe735171d9b876d03bbf3d5a1c3220fdc0f7d/Dockerfile#L141-L143

I'm going to see what breaks here, but it's taking a while to install FSL on the new build.

An early note:

During the initial build, Node warned me that v11 (which we are using https://github.com/FCP-INDI/C-PAC/blob/a1f22dfe57fc969436e133c0705781006303c223/Dockerfile#L9) is deprecated:

[![Node lifecycle](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)](https://nodejs.org/en/about/releases/)

**Comment by shnizzedy** [comment]
At 3ba96c804f07ee51f8454e886f472cedc23af8ef, the Dockerfile builds an image with the base Python @ 3.7

**Comment by sgiavasis** [comment]
Completed in v1.6.2!
