### ISSUE TITLE
Open configurability access to ANTs registration parameters

### ISSUE THREAD

**Issue by SucyLi** [FCP-INDI/C-PAC#1120]
Current EPI registration (ANTs) only works for human. Maybe a new config field called **species** can be added, and if this field is specified as rodent, it will run Marco's registration code.

**Comment by HechengJin0** [comment]
- e.g. if select rodent as species, only run epi registration with (rodent) ANTs parameter and off regular registration. 

- fix connection of registration to further step. current **rodent_reg** branch cannot do further step, smooth i.e.

**Comment by sgiavasis** [comment]
Second point mentioned above ☝️ tracked here: #1117

**Comment by sgiavasis** [comment]
Changing this to ANTs parameter configurability issue.

**Comment by sgiavasis** [comment]
This is in v1.6.2.
