### ISSUE TITLE
QC html page 'scan' & 'selector' buttons not working 

### ISSUE THREAD

**Issue by Tonyfer** [FCP-INDI/C-PAC#1124]
When navigating to the page with these buttons, the page displays figures for all scans and strategies.

@anibalsolon

**Comment by anibalsolon** [comment]
Fixed in e7a64e0de2fe0abc02157a5b444c7069e9fd307a
Will be deployed in the next hotfix.

Thank you @Tonyfer !

**Comment by sgiavasis** [comment]
This is in v1.6.1.
Thank you @Tonyfer and @anibalsolon !!
