### ISSUE TITLE
YAML safe load

### ISSUE THREAD

**Issue by anibalsolon** [FCP-INDI/C-PAC#1126]
```
/code/CPAC/pipeline/cpac_runner.py:217: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  c = Configuration(yaml.load(open(config_file, 'r')))
```

Now, YAML lib yields a warning about loading files without any custom Loader to handle Objects deserialization. It is unsafe yada yada but would not impact C-PAC (unless someone stored in a pipeline config a Python object that would upload the user's AWS credentials to somewhere, but unlikely).

I would recommend replacing all occurrences of `yaml.load` with `yaml.safe_load`, since C-PAC uses just primitives (dict, list, int, float, str, bool).

**Comment by pn2200** [comment]
I'd like to make these changes, but several uses of `yaml.load` are in source files that appear to be unused, for example `cpac_randomise_pipeline.py`, `create_fsl_model.py`, `cpac_basc_pipeline.py`, and `cpac_cwas_pipeline.py`. Is it safe to remove those files? If I issue a pull request that changes `yaml.load` to `yaml.safe_load`, can I also include removing those files?

**Comment by anibalsolon** [comment]
Hi @pn2200 I would recommend to keep them, although not used. For those not used, it is okay to not test them. I believe a cleaning session will take place in the near future.

**Comment by anibalsolon** [comment]
Thank you for your comprehension @pn2200 ! Your contributions has been much appreciated by the project. I will open an issue for the cleaning, to list what needs to be cleaned and others can jump to discuss it.
