### ISSUE TITLE
Anatomical refined bold mask improvement

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1146]
registration quality in generating anatomical refined bold mask step: use brain to brain, instead of head to head.
Currently, cpac registers func-head to anat-head to get matrix of applying to anat_mask_to_func_space. In this way, registration quality would be not good enough, especially for monkey data. Change it to func-brain to anat-brain to get the matrix. So, generate temporary bold mask to get func-brain first.

**Comment by sgiavasis** [comment]
This is in v1.6.1.
