### ISSUE TITLE
QC translation and rotation motion plots are named incorrectly

### ISSUE THREAD

**Issue by pn2200** [FCP-INDI/C-PAC#1147]
The QC motion plots are named incorrectly. The plot in the `movement_rot_plot` folder, showing roll, pitch, and yaw, is named `motion_trans_plot.png` and the plot in the `movement_trans_plot` folder showing x, y, and z, is named `motion_rot_plot.png`. The file names should be swapped.

**Comment by sgiavasis** [comment]
This is in v1.6.1.
Thank you @pn2200 !!
