### ISSUE TITLE
QC crash file:  motion_plot 

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1153]
function_str = CPAC.qc.utils.gen_motion_plt
 line 1264, in gen_motion_plt
    plt.gca().set_prop_cycle(['red', 'green', 'blue'])
 
TypeError: If only one positional argument given, it must  be a Cycler instance.

**Comment by anibalsolon** [comment]
@HechengJin I've sent a fix on develop, would you mind checking if it still occurs?

**Comment by HechengJin0** [comment]
@anibalsolon fixed. Thank you, Ani
