### ISSUE TITLE
Feature: Ability to "import" pre-configured pipeline config from a new config

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1182]
May be worth making a feature where at the head of a pipeline config, there can be something like this:

`BASE: default`

or

`BASE: benchmark-ANTS`

etc., where doing so will "call" the pre-configured pipeline, but any new fields in the current YAML will override the one being "imported". This way, people can make quick edits without going through a whole new YAML.

**Comment by sgiavasis** [comment]
Nixing this for now.

**Comment by anibalsolon** [comment]
😭
