### ISSUE TITLE
1.6.1 does not work with older pipeline config file

### ISSUE THREAD

**Issue by tbweng** [FCP-INDI/C-PAC#1199]
It seems like there was a change to 1.6.1 pipeline config that is not backwards compatable with older pipeline config files.
I received the below error from running 1.6.1 using a pipeline config file generated from 1.6.0:

```Traceback (most recent call last):
  File "/code/run.py", line 576, in <module>
    test_config = 1 if args.analysis_level == "test_config" else 0
  File "/code/CPAC/pipeline/cpac_runner.py", line 344, in run
    p_name, plugin, plugin_args, test_config)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 2639, in prep_workflow
    '{0}_{1}'.format(regressors_selector_i, num_strat))
  File "/code/CPAC/nuisance/nuisance.py", line 1527, in filtering_bold_and_regressors
    bandpass_selector.get('bottom_frequency'),
AttributeError: 'NoneType' object has no attribute 'get'```

**Comment by pn2200** [comment]
I experienced the same issue, and had to add configuration similar to the following from the `default_pipeline.yml`:
https://github.com/FCP-INDI/C-PAC/blob/master/dev/docker_data/default_pipeline.yml#L772-L774

**Comment by nx10** [comment]
Outdated
