### ISSUE TITLE
🐛🐍 "Module CerebrospinalFluid_mean has no output called stats"

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1201]
In 0e7db8c9eff15e93feb90b94935cd4ddbced0993, I'm getting the following error every time I run `test_config`:

> ```
> 200218-22:29:47,996 nipype.utils INFO:
> 	 No new version available.
> Traceback (most recent call last):
>   File "/code/run.py", line 587, in <module>
>     test_config = 1 if args.analysis_level == "test_config" else 0
>   File "/code/CPAC/pipeline/cpac_runner.py", line 341, in run
>     p_name, plugin, plugin_args, test_config)
>   File "/code/CPAC/pipeline/cpac_pipeline.py", line 2540, in prep_workflow
>     name='nuisance_regressor_{0}_{1}'.format(regressors_selector_i, num_strat)
>   File "/code/CPAC/nuisance/nuisance.py", line 1303, in create_regressor_workflow
>     build_nuisance_regressors, regressor_arg
>   File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 236, in connect
>     raise Exception("\n".join(["Some connections were not found"] + infostr))
> Exception: Some connections were not found
> Module CerebrospinalFluid_mean has no output called stats
> ```

I don't get this error running 3f22187b8483343595c2f7032d0c425e0fa1a1e1, so I think this problem is in either the [Python 2 → 3 / Ubuntu 16 → 18 upgrade](https://github.com/FCP-INDI/C-PAC/pull/1200).

[AFNI took some massaging to get to work in this upgrade](https://github.com/FCP-INDI/C-PAC/compare/e368ba780c8a4e02f4d81bf0810268f2c522f784...0e7db8c9eff15e93feb90b94935cd4ddbced0993), so I wouldn't be surprised if another tool is working not as expected. The [2 → 3 changes are huge](https://github.com/FCP-INDI/C-PAC/commit/27fe3c1a8ae4a951ffe4342d36aeda5a0efc27ce) as well, so there's also a good chance the problem is there.

What software should be generating CerebrospinalFluid_mean stats?

**Comment by anibalsolon** [comment]
This is the CerebrospinalFluid_mean: https://github.com/FCP-INDI/C-PAC/blob/0e7db8c9eff15e93feb90b94935cd4ddbced0993/CPAC/nuisance/nuisance.py#L1190-L1204

I guess you have updated the Nipype version, in which the 'stats' output attribute is now called 'out_file':

https://github.com/nipy/nipype/commit/05c056c5285f0cb9a76d1bf967278231fe4ff03e#diff-851b9f467ed8042d29a89dbd00b754dfL1820-R1897

**Comment by shnizzedy** [comment]
Thanks! 🙏 

That's probably it! I [unlocked all the Python package versions](https://github.com/FCP-INDI/C-PAC/commit/3ba96c804f07ee51f8454e886f472cedc23af8ef?diff=split) to build this new Python3-based image. I'll re-lock everything that's Py3 to what we had before, try again, and then if it all seems to work lock what's left.

**Comment by shnizzedy** [comment]
If we want to upgrade Nipype, we can decide that, but I think that's beyond the scope of this upgrade

**Comment by anibalsolon** [comment]
I guess there is no problem if we upgrade it- the regression test should get any potential errors.

**Comment by anibalsolon** [comment]
You are right, outside the scope, the port to Py3 can bring several problems already. No need to include a new variable.

**Comment by shnizzedy** [comment]
Resolved in 8c659d1

**Comment by shnizzedy** [comment]
:grimacing: maybe this is not well-resolved. Now I'm getting empty `CerebrospinalFluid_mean/roi_stats.csv` files:

```
ValueError: Number of time points in /tmp/resting_preproc_sub-0025427_ses-3/nuisance_regressor_0_0/_scan_rest_run-1/_selector_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_G-M_M-SDB_P-2_BP-B0.01-T0.1/CerebrospinalFluid_mean/roi_stats.csv (0) is inconsistent with length of functional file /tmp/resting_preproc_sub-0025427_ses-3/func_preproc_afni_3dvolreg_0/_scan_rest_run-1/func_normalize/sub-0025427_ses-3_task-rest_run-1_bold_calc_tshift_resample_volreg_calc_maths.nii.gz (300)

ValueError: Number of time points in /tmp/resting_preproc_sub-0025427_ses-3/nuisance_regressor_1_0/_scan_rest_run-1/_selector_CSF-2mmE-M_aC-CSF+WM-2mm-DPC5_M-SDB_P-2_BP-B0.01-T0.1/CerebrospinalFluid_mean/roi_stats.csv (0) is inconsistent with length of functional file /tmp/resting_preproc_sub-0025427_ses-3/func_preproc_afni_3dvolreg_0/_scan_rest_run-1/func_normalize/sub-0025427_ses-3_task-rest_run-1_bold_calc_tshift_resample_volreg_calc_maths.nii.gz (300)
```

**Comment by pn2200** [comment]
Is this the same issue as #1140?

**Comment by shnizzedy** [comment]
> Is this the same issue as #1140?

They might be related, but this issue is occurring exclusively on the [upgrade/python3 branch](https://github.com/FCP-INDI/C-PAC/tree/upgrade/python3) while #1140 seems to be occurring in Python 2 as well

**Comment by sgiavasis** [comment]
I believe this can be removed as a blocker for the Python 3 PR.
