### ISSUE TITLE
read group analysis pipeline output folder properly

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1219]
for some specific cases(/data3/autism_center/projects/patricia/ffa-acc/out1)
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_group_runner.py#L176-L178
cannot find nifti image properly

error:
# Exception:
# [!] No output filepaths found in the pipeline output directory provided for the derivatives selected!
# Pipeline output directory provided: /out1
# Derivatives selected:['functional_to_standard']

**Comment by sgiavasis** [comment]
This has been resolved in v1.6.2.
