### ISSUE TITLE
fork template_based_segmentation(T1_based/EPI_based) and regular SegmentationPreprocessing

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1224]
1. re-organize runSegmentationPreprocessing and segmentation method.
2. fork (T1_based/EPI_based) template segmentation . https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L2241-L2248

**Comment by sgiavasis** [comment]
#1 is mentioned in #1185

**Comment by sgiavasis** [comment]
Point no. 2 is in v1.6.2.
