### ISSUE TITLE
update blip warp inverse in resource pool

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1225]
currently, turn on blip & aroma at the same time would crash pipeline. 
`blip_warp_inverse` were not updated here. 
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L1884
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L2432

**Comment by HechengJin0** [comment]
1. tried calculate both forward and inverse warps in the QWarp step https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dQwarp.html 
However, it can't run with plusminus
```
iwarp: (a boolean)
        Do compute and save the _WARPINV file.
        argument: ``-iwarp``
        mutually_exclusive: plusminus
```
2. another option would be to use a transform utility from ants. not dig into this approach yet. 
 
3. additionaly, we are using this function to convert afni to ants. https://github.com/FCP-INDI/C-PAC/blob/a1f22dfe57fc969436e133c0705781006303c223/CPAC/distortion_correction/distortion_correction.py#L223

**Comment by sgiavasis** [comment]
This is in v1.6.2.
