### ISSUE TITLE
Integrate longitudinal pipeline

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1230]
Based on:
[Within-subject template estimation for unbiased longitudinal image analysis](https://www.sciencedirect.com/science/article/abs/pii/S1053811912002765)

Flowchart created by @SucyLi:
![C-PAC Longitudinal Pipeline](https://user-images.githubusercontent.com/4644673/83286663-4b6c6d80-a1ae-11ea-94e0-563a972ffcd8.png)

First part of implementation by http://computational-neuroimaging-lab.org/

**Comment by SucyLi** [comment]
- [ ] anatomical longitudinal workflow
- [ ] functional longitudinal workflow
- [ ] add runAnatomical so that user can turn off anat preprocessing

**Comment by sgiavasis** [comment]
I believe we already discussed this, but we should establish the validation criteria, data to use as a reference, etc.

**Comment by sgiavasis** [comment]
All set!
