### ISSUE TITLE
No files found in the BIDS directory when creating the data config YAML

### ISSUE THREAD

**Issue by bwinsto2** [FCP-INDI/C-PAC#1252]
Hello all: 
I am attempting to create the data config .yml file (I already created a template) following the instructions on the CPAC page. 
<img width="1127" alt="Screen Shot 2020-04-20 at 1 48 09 PM" src="https://user-images.githubusercontent.com/61159065/79783370-8efdcd00-830e-11ea-852d-8654b98711c0.png">
Above is a picture of the code (the blacked out parts are either my name or username). I am on linux running the latest Docker CE; I was able to create the data settings template file, then I edited it in a text editor (the file on my local drive...do I need to edit the one running in the docker container? is that even possible?). I then ran the command on CPAC's website to build the data config file. As you can see in the screenshot, it fails to find files in my BIDS folder. I am confused why that is -- the directory "raw_data" is a BIDS valid dataset. The "raw_data" contains some .jsons and the "sub-" folders. It seems strange that no files were found in the directory. 
Anyone have any ideas? I am new to CPAC, Linux, and Docker, so I ask for forgiveness if this is a very simple question. Thank you very much for your help!

**Comment by SucyLi** [comment]
Hi,

Thank you for using C-PAC. Could you add 2 lines to map your data and output dir in your docker run command? Like this:

`-v /data2/xxx/1305/BIDS_test_stuff/cpac/BIDS/raw_data:/data2/xxx/1305/BIDS_test_stuff/cpac/BIDS/raw_data` <br/>
`-v /data2/xxx/1305/BIDS_test_stuff/cpac/ouput:/data2/xxx/1305/BIDS_test_stuff/cpac/ouput`

Sorry for the confusion. We'll update our documentation page soon.

**Comment by bwinsto2** [comment]
That worked -- thanks!

**Comment by bwinsto2** [comment]
Appreciate your quick response. It's not working exactly as I thought it would.
<img width="1127" alt="Screen Shot 2020-04-20 at 3 25 11 PM" src="https://user-images.githubusercontent.com/61159065/79791347-29640d80-831b-11ea-84b0-0f0b4a7768aa.png">
I was expecting it to say 

> CPAC DATA CONFIGURATION file created (use this for individual-level analysis):

but instead, I got what is seen in the screenshot. The anatomical template should work since my data are formatted like that (with the exception of one session for one participant not having anatomical scans). I can't tell if the configuration file was created or not.
