### ISSUE TITLE
User reporting empty censor.tsv file

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1256]
From the C-PAC forum:
https://groups.google.com/forum/#!topic/cpax_forum/USFpu9cf11Y

FD_J was disabled due to mcflirt- had to reopen:
https://github.com/FCP-INDI/C-PAC/commit/93be68283eb203dc5c41f5d85b8439884da16b60

However, still need to ensure mcflirt still works smoothly.

**Comment by SucyLi** [comment]
Oops, so sorry I forgot to change it back after adding mcflirt FD-J. Your change should work.

**Comment by sgiavasis** [comment]
This is complete.
