### ISSUE TITLE
Singularity image does not download

### ISSUE THREAD

**Issue by irebollo** [FCP-INDI/C-PAC#1258]
Hi
I'm having issues downloading the singularity image using the command

``
singularity pull shub://FCP-INDI/C-PAC
``
Outpuit

FATAL:   While pulling shub image: failed to get manifest for: shub://FCP-INDI/C-PAC: json: cannot unmarshal number into Go value of type client.ShubAPIResponse

I'm using singularity 3.5.2  on a linux mint machine

Fresh install of singularity using these instructions
https://sylabs.io/guides/3.5/user-guide/quick_start.html#quick-installation-steps

Which is able to install other singularity packages
Cheers,
Ignacio

**Comment by shnizzedy** [comment]
Hi @irebollo,

Thanks for letting us know.

A potential workaround is to pull the Docker image and let Singularity reconstruct the image:

```
singularity pull docker://fcpindi/c-pac:latest
```

If you use Singularity to pull from Docker Hub, the image name will include the Docker tag including the version. Ie, running the previous command will get you an image called `c-pac-latest.simg`.

It looks like you [might be hitting a rate limit on Singularity Hub](https://github.com/sylabs/singularity/issues/4563#issuecomment-538013636). Are you getting a response code in addition to the error message?

**Comment by irebollo** [comment]
Hi @shnizzedy 
Both worked now
I tried
singularity pull docker://fcpindi/c-pac:latest

and retried
singularity pull shub://FCP-INDI/C-PAC
which seems to be working now
Thank you very much!
