### ISSUE TITLE
crash: AFNI reads 1D file (1 column)

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1265]
** FATAL ERROR: 1D file roi_stats.csv has 449 time points, but dataset has 450 values.

AFNI_20.1.01 (in docker container)  works well with 2 or more columns for current 1D format, but not works if it contains 1 column. 

#File,Sub-brick
#Mean_1

**Comment by shnizzedy** [comment]
https://github.com/FCP-INDI/C-PAC/pull/1267 is probably related. 

> * NOTE WELL: 1dcat now also allows comma separated value (.csv) files. These
>              are treated the same as .tsv files, with a header line, et cetera.

― [AFNI program: 1dcat Output of -help](https://afni.nimh.nih.gov/pub/dist/doc/program_help/1dcat.html)

I bet `roi_stats.csv` has 450 entries and needs a header row.
