### ISSUE TITLE
Remove dependence on node names in strat for decisions

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1273]
In some areas in cpac_pipeline.py, the main pipeline builder, the node names within each strategy are used to decide which sub-parts of the pipeline to connect to that particular strategy:

- https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/CPAC/pipeline/cpac_pipeline.py#L1115-L1116
- https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/CPAC/pipeline/cpac_pipeline.py#L2288

The most common use of this is to determine whether or not the strategy being iterated over is an ANTS-registration-based or FSL-registration-based strategy, for the purpose of connecting the rest of the strategy to the appropriate transformation application nodes. However, there are several others, notably related to distortion correction or segmentation decisions.

Goal:
- Remove this dependence by encoding necessary information within the resource pool of each strategy somehow.

Reasoning:
- If some preprocessing in the early pipeline is already performed outside the main pipeline (like with the longitudinal pipeline (#1230)), and these preprocessed data are integrated into the pipeline, the resources will be present in the strategy, but the node names will not be.
- Harder to maintain code if node names are changed.
- Code may be easier to read and follow if a centralized resource in each strategy's resource pool is dedicated to strategy information- perhaps a dictionary.

**Comment by sgiavasis** [comment]
Total count of "in nodes:" checks in cpac_pipeline.py (58 in total):
- 29 for registration (ANTS or FSL) choices
- 16 for EPI-based registration choices
- 8 for segmentation based choices
- 2 for lesion mask choices (registration based)
- 2 for motion statistics/correction choices
- 1 for distortion correction

**Comment by sgiavasis** [comment]
I'll test out using a dictionary as a "strat_info" resource. If it's an easy and small enough change that suits the purpose, let's split up the "in nodes" updates.

**Comment by sgiavasis** [comment]
https://github.com/FCP-INDI/C-PAC/pull/1274

**Comment by sgiavasis** [comment]
#1274 has been merged into develop.

@SucyLi could you take on the ANTS/FSL ones, and I can do the rest?

**Comment by SucyLi** [comment]
> @SucyLi could you take on the ANTS/FSL ones, and I can do the rest?
No problem

**Comment by sgiavasis** [comment]
This was completed for v1.7.0.
