### ISSUE TITLE
Convert pipeline config into nested format

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1278]
**Aim**
Group the pipeline configuration keys into nested blocks of related keys. For example, start with the [on/off switch for segmentation](https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/dev/docker_data/default_pipeline.yml#L397-L398), and then nest the [segmentation parameters](https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/dev/docker_data/default_pipeline.yml#L401-L468) underneath it.

**Reason**
As the pipeline configuration file schema gets larger and larger, the long list of keys becomes daunting and confusing. It is also difficult to quickly tell which keys belong to which part of the pipeline at quick glance.

**Considerations**
All of the code that deals with reading in and writing out pipeline config files, including the GUI.

**Branch:** https://github.com/FCP-INDI/C-PAC/tree/enh/nested_config

**Comment by SucyLi** [comment]
can also refactor some pipeline config keys from camelCase to under_score at the mean time

**Comment by sgiavasis** [comment]
As mentioned in #937 .

**Comment by sgiavasis** [comment]
This is in v1.8.
