### ISSUE TITLE
Band-stop/notch filter for respiratory artifacts (pre-motion estimation)

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1286]
https://www.biorxiv.org/content/10.1101/337360v1.full.pdf

**Comment by HechengJin0** [comment]
Autism center reported: the values before and after notch filter are identical.

**Comment by sgiavasis** [comment]
Bumping the fixes for this to 1.7.1.

**Comment by sgiavasis** [comment]
Done! Released in v1.7.1.
