### ISSUE TITLE
Run CPAC without filtering.

### ISSUE THREAD

**Issue by hahaai** [FCP-INDI/C-PAC#1314]
https://github.com/FCP-INDI/C-PAC/blob/ce26ba9a38cbd401cd405150eeed23b805007724/CPAC/pipeline/cpac_pipeline.py#L3333

This line gives error when running CPAC without filtering, this need to be put into an "if" loop:
if 'Bandpass' in regressors_selector:
    ****

**Comment by sgiavasis** [comment]
This will be resolved in 1.7. Thanks!
