### ISSUE TITLE
Build BIDS-Derivatives intake function

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1344]
**Related Problem**
Right now, C-PAC only accepts inputs from the data config YAML file. It cannot parse already existing resources that users might have already generated. This prevents users from starting the pipeline from an intermediate point.

Thanks to Nipype, C-PAC can start from a middle point in the pipeline, but only if the first half of the pipeline was already run, and if the working directory was retained. Cannot inject custom/other resources into the pipeline.

**Proposed Feature**
Build an intake function that can parse a BIDS-Derivatives compliant derivatives folder.

**Scratchpad**
-  inject into internal pipeline resource pool
- conversion dictionary between BIDS labels and internal naming? or line these up?
- have it check a /derivatives folder? which is the output directory, not the data directory
- are there any apps or packages that make parsing BIDS Derivatives easier?

**Comment by shnizzedy** [comment]
> * are there any apps or packages that make parsing BIDS Derivatives easier?

There's an [open project](https://github.com/bids-standard/bids-validator/projects/1) to add BIDS derivatives to the official BIDS validator, but everything's in the "to do" column at the moment.

**Comment by sgiavasis** [comment]
This is in v1.8.
