### ISSUE TITLE
🐛 motion notch filter 

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1347]
**Describe the bug**
Autism center reported: the values before and after notch filter are identical. 

**To Reproduce**
motion_params: /data3/autism_center/projects/patricia/ffa-acc/notch_filter/out/working/resting_preproc_sub-80324_ses-1/func_preproc_afni_mean_3dvolreg_0/_scan_rest_run-01/func_motion_correct_3dvolreg/sub-80324_task-rest_run-01_bold_calc_resample.1D
TR : 0.8s
notch_filter_motion_estimates: True
notch_filter_breathing_rate_min: 19
notch_filter_breathing_rate_max: 21
notch_filter_order: 4

**Versions** 
 - C-PAC:  e.g. 1.7.0 
 - Container Platform : Docker

**Additional context**
related branch: https://github.com/FCP-INDI/C-PAC/tree/fix/notch_filter
added degree and mm conversion. 

next: check if matlab code <[filter(b_filt,a_filt,MR_ld)](https://github.com/DCAN-Labs/dcan_bold_processing/blob/master/matlab_code/filtered_movement_regressors.m#L98)> is identical to C-PAC <[filtfilt(b_filt, a_filt, params_data.T)](https://github.com/FCP-INDI/C-PAC/blob/develop/CPAC/func_preproc/utils.py#L111)>
check filtfilt params e.g. [padtype](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.filtfilt.html)

**Comment by sgiavasis** [comment]
Fixed- this is in v1.7.1.
