### ISSUE TITLE
🐛 Node copy_xform failed to run on host

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1362]
**Describe the bug**

```
200913-22:26:45,786 nipype.workflow INFO:
	 [Node] Setting-up "resting_preproc_sub-04_ses-movie.anat_preproc_niworkflows_ants_0.anat_skullstrip_ants.atropos_wf.copy_xform" in "/tmp/resting_preproc_sub-04_ses-movie/anat_preproc_niworkflows_ants_0/anat_skullstrip_ants/atropos_wf/copy_xform".
200913-22:26:45,788 nipype.workflow INFO:
	 [Node] Running "copy_xform" ("CPAC.utils.interfaces.utils.CopyXForm")
200913-22:26:46,365 nipype.workflow INFO:
	 [Node] Finished "resting_preproc_sub-04_ses-movie.func_preproc_before_stc_fsl_afni_mean_3dvolreg_0.func_preproc_before_stc_fsl_afni_mean_3dvolreg_0_skullstrip.skullstrip_first_pass".
200913-22:26:51,453 nipype.workflow WARNING:
	 [Node] Error on "resting_preproc_sub-04_ses-movie.anat_preproc_niworkflows_ants_0.anat_skullstrip_ants.atropos_wf.copy_xform" (/tmp/resting_preproc_sub-04_ses-movie/anat_preproc_niworkflows_ants_0/anat_skullstrip_ants/atropos_wf/copy_xform)
200913-22:26:51,457 nipype.workflow ERROR:
	 Node copy_xform failed to run on host node055.
200913-22:26:51,457 nipype.workflow ERROR:
	 Saving crash info to /outputs/crash/crash-20200913-222651-pab2163-copy_xform-051118d9-3dc0-4a93-a0ad-7b2cf0efbcbc.pklz
```
```Python
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 308, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 569, in run
    vals = np.loadtxt(mon_sp.fname, delimiter=',')
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: .proc-7511_time-1600050405.7896101_freq-1.00 not found.
```

**To Reproduce**
```YAML
skullstrip_option :  ['niworkflows-ants']
```

**Versions** 
 - C-PAC: 1.7.0
 - Container Platform :
    - Singularity

**Additional context**

> This issue does seem isolated to the ANTS workflow -- I don't get any problems with skullstripping if I use AFNI instead.

Possibly related:

* #1352:
   ```
   Parsing /bids_dataset..
   {'site': 'none', 'sub': '04', 'ses': 'movie', 'scantype': 'T1w'}
   Did not receive any parameters for sub-04/ses-movie/anat/sub-04_ses-movie_T1w.nii.gz, is this a problem?
   ```
   in log)
* #1338: cooccurs with same configuration
* #1337: may be conflict between data environment and Nipype version

**Comment by sgiavasis** [comment]
This is more of a utility node that is used in the ANTs brain extraction workflow but isn't ANTs proper.

Is there any more info in that crash pickle other than the traceback?

**Comment by shnizzedy** [comment]
Unfortunately no. The only thing besides the traceback that the pickle shows is

```Python
Nipype version 1.1.2
```

**Comment by shnizzedy** [comment]
`multiproc` stands out to me as the likely culprit here. I haven't been able to replicate (yet). On what I thought was a comparable setup on AWS, the pipeline config ran without error for me (besides one [non-crashing SameFileError](https://github.com/FCP-INDI/C-PAC/issues/1260)).

**Comment by shnizzedy** [comment]
[Here](https://github.com/nipy/nipype/blob/8690d55d9a13f686c569cd5dad4f6da6ffc53af8/nipype/pipeline/plugins/multiproc.py#L303-L317)'s the spot in Nipype where the error is being thrown

```Python
# updatehash and run_without_submitting are also run locally
if updatehash or self.procs[jobid].run_without_submitting:
    logger.debug('Running node %s on master thread',
                 self.procs[jobid])
    try:
        self.procs[jobid].run(updatehash=updatehash)
    except Exception:
        traceback = format_exception(*sys.exc_info())
        self._clean_queue(
            jobid,
            graph,
            result={
                'result': None,
                'traceback': traceback
            })
```

when the file [here](https://github.com/nipy/nipype/blob/8690d55d9a13f686c569cd5dad4f6da6ffc53af8/nipype/interfaces/base/core.py#L569) is trying to load

```Python
vals = np.loadtxt(mon_sp.fname, delimiter=',')
```

Since Nipype multiproc as [lots of issues](https://github.com/nipy/nipype/issues?q=is%3Aissue+multiproc), I'm cautiously hopeful that when we upgrade from [1.1.2](https://github.com/nipy/nipype/releases/tag/1.1.2) to [1.5.1](https://github.com/nipy/nipype/releases/tag/1.5.1) (or whatever we upgrade to) this issue will be resolved. [1.1.5](https://github.com/nipy/nipype/releases/tag/1.1.5) & [1.1.6](https://github.com/nipy/nipype/releases/tag/1.1.6) in particular look to have some multiproc fixes.

**Comment by sgiavasis** [comment]
Let's cut 1.7.1, then we can push the Nipype 1.5.1 upgrade to develop- then we can test these on that and see.

**Comment by shnizzedy** [comment]
👍: from another group:

```BASH
crash-20201104-154021-rbc-sinker_0_frame_wise_displacement_jenkinson.b0-050e361a-65b6-417e-b11d-24d7c481742e.pklz
crash-20201104-154311-rbc-copy_xform-2bd70352-5f49-46be-a618-3f429375cc89.pklz
```

> But it is not consistent. Some subjects run through, while some did not

**Comment by shnizzedy** [comment]
Original user reporting the bug:

> if it helps, ANTS skullstrip seems to work fine if I run the pipeline on only 1 core -- more evidence for your idea that this has to do with multiproc

**Comment by shnizzedy** [comment]
After upgrading to Nipype v1.5.1, I'm seeing the behavior described in https://github.com/nipy/nipype/issues/2700 when running with `skullstrip_option :  ['niworkflows-ants']` on Singularity. I'm trying the suggestion from there to use `LegacyMultiProc` now.

**Comment by shnizzedy** [comment]
Closing as duplicate of #1404. Will reopen if still occurs after resolving that issue.
