### ISSUE TITLE
Pipeline Builder code changes for nested pipeline config

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1366]
**Related problem**
Big changes are required for our [pipeline configuration YAML upgrade](https://github.com/FCP-INDI/C-PAC/blob/45796e02a091e98da9d65f882b02ea8aa8a10986/dev/docker_data/default_pipeline.yml) via #1278!

**Proposed feature**
The pipeline builder code needs to be updated to be compatible with the nested config format.
An example of how this looks can be seen here:
https://github.com/FCP-INDI/C-PAC/blob/a21841904b66e30f13f37f61dd454ab338aee372/CPAC/func_preproc/func_preproc.py#L1150-L1156

**Branch:**
https://github.com/FCP-INDI/C-PAC/tree/enh/nested_config

**Additional context**
Rough count of how many instances of the old `c.{parameter}` calls in the codebase:

- cpac_pipeline: 191
- anat_preproc: 52
- longitudinal: 35
- registration: 25
- centrality: 18
- segmentation: 18
- func_preproc + init: 17
- distcor: 8
- plus the Datasink/Output dir handling of On/Off from cpac_outputs.csv

**Comment by sgiavasis** [comment]
Here's a work split based on the number of c.{parameter} calls (instead of number of lines 😄 ):

- @HechengJin0:
    - cpac_pipeline: lines 0-711
    - anat_preproc (all)
- @SucyLi 
    - cpac_pipeline: lines 712-1524
    - func_preproc + func_ingress (all)
    - longitudinal (all)
- @shnizzedy 
    - cpac_pipeline: lines 1525-2700
    - registration (all)
    - centrality (all)
    - segmentation (all)
    - distcor (all)
- @sgiavasis 
    - cpac_pipeline: lines 2700-end
    - Datasink/Output dir system

**Comment by sgiavasis** [comment]
Some questions to answer:

- How are we updating the pipeline YAML/dictionary validation?
- Should we convert all 'On'/'Off' to lowercase in case users type them in lowercase? Instead of using .lower() everywhere?
- When an option isn't forkable and it can only be 'On' or 'Off', is checking against the string being equivalent a robust enough case? etc.

**Comment by sgiavasis** [comment]
I also naively put in some keys with dashes in them at the top level.
This won't work in the pipeline builder when we call `c.seed-based_correlation_analysis`, for example.

Changing the top-level keys to underscores only. The dashes are fine in the lower levels since those are called with strings in the dictionary key brackets.

**Comment by sgiavasis** [comment]
@shnizzedy Don't hate me, but I'm considering having the `registration_workflow` level under `anatomical_preproc` to be its own thing ...

Can discuss more on Monday.

**Comment by shnizzedy** [comment]
> * Should we convert all 'On'/'Off' to lowercase in case users type them in lowercase? Instead of using .lower() everywhere?
> * When an option isn't forkable and it can only be 'On' or 'Off', is checking against the string being equivalent a robust enough case? etc.

* In YAML 1.1, `On` and `Off` are (basically case-insensitive) flavors of `True` and `False`: https://yaml.org/type/bool.html:
   > ```
   > y|Y|yes|Yes|YES|n|N|no|No|NO
   > |true|True|TRUE|false|False|FALSE
   > |on|On|ON|off|Off|OFF
   > ```

* In YAML 1.2, only `true` and `false` (still basically case-insensitive) are valid Booleans: https://yaml.org/spec/spec.html#id2603930:
    > ```
    > true | True | TRUE | false | False | FALSE
    > ```

something like `oN` or `oFF` would probably cause trouble, but otherwise, as long as we're using YAML 1.1 + PyYAML, I don't think we need to worry about casing. If we want to upgrade YAML 1.2 + ruamel.yaml, then we do need to answer those two questions about 'On' and 'Off'

**Comment by sgiavasis** [comment]
Fantastic!

**Comment by shnizzedy** [comment]
> @shnizzedy Don't hate me, but I'm considering having the `registration_workflow` level under `anatomical_preproc` to be its own thing ...
> 
> Can discuss more on Monday.

Once #1380 is merged, it'll be pretty trivial to update :point_up: that change

**Comment by shnizzedy** [comment]
Some todos left after merging #1380, #1394, #1395, #1396:

- [ ] make sure https://github.com/FCP-INDI/C-PAC/blob/8f8bffef7d4a8f6eb44b1a21ce025627fcca8738/CPAC/pipeline/cpac_pipeline.py#L2669 and https://github.com/FCP-INDI/C-PAC/blob/8f8bffef7d4a8f6eb44b1a21ce025627fcca8738/CPAC/pipeline/cpac_pipeline.py#L2702-L2704 work after converting from `[{}]` (one-length list-of-dicts) to `{}` (dict) in pipeline
- [ ] remove `extra=ALLOW_EXTRA` once we fully update the validation schema https://github.com/FCP-INDI/C-PAC/blob/8f8bffef7d4a8f6eb44b1a21ce025627fcca8738/CPAC/pipeline/schema.py#L403
- [ ] decide whether / how to retain median angle correction in the nested config: https://github.com/FCP-INDI/C-PAC/pull/1380#discussion_r510448136

**Comment by sgiavasis** [comment]
We can drop median angle correction.

**Comment by shnizzedy** [comment]
Is this change in the default pipeline intended?

Pre-nested:
https://github.com/FCP-INDI/C-PAC/blob/6eadaed317a9b256a82f15bccee57a5e8de7514e/dev/docker_data/default_pipeline.yml#L756-L757

Nested:
https://github.com/FCP-INDI/C-PAC/blob/14db696e4ac3187c400aeec5d3febc32199fcbcf/dev/docker_data/default_pipeline.yml#L704-L710

**Comment by sgiavasis** [comment]
Yes- I decided to go with having a separate On/Off switch.

I'm still not sure it's even necessary to be able to fork the two different types of distortion correction we have- I don't think I've ever seen a dataset that has both types of field maps- but I left it that way just in case. Doesn't hurt.

**Comment by shnizzedy** [comment]
Wait... it was `["None"]` before, now it's

https://github.com/FCP-INDI/C-PAC/blob/14db696e4ac3187c400aeec5d3febc32199fcbcf/dev/docker_data/default_pipeline.yml#L698-L702

?

**Comment by sgiavasis** [comment]
This has been completed as part of v1.8.
