### ISSUE TITLE
✨ BOLD Mask Option: Resampled anatomical brain mask to functional space

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1369]
**Related problem**
The BOLD mask produced by the options currently in C-PAC can sometimes be a bit too conservative in areas affected by susceptibility artifact.

**Proposed feature**
A functional BOLD masking option that simply transforms the anatomical brain mask to the functional BOLD data. This is different than the "Anatomical Refined" option which is based off of the BOLD mask.

It would be a new option here:
https://github.com/FCP-INDI/C-PAC/blob/a21841904b66e30f13f37f61dd454ab338aee372/dev/docker_data/default_pipeline.yml#L824-L826

**Additional context**
May be worth simply using the inverse transform of the coregistration.

**Comment by sgiavasis** [comment]
This will be adapted from the DCAN Labs method:
https://github.com/DCAN-Labs/DCAN-HCP/blob/master/fMRIVolume/scripts/DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh

**Comment by sgiavasis** [comment]
@HechengJin0 Could we work towards a draft flowchart on how we'd line up the nodes in C-PAC for this? And an estimate on the complexity?

**Comment by HechengJin0** [comment]
> @HechengJin0 Could we work towards a draft flowchart on how we'd line up the nodes in C-PAC for this? And an estimate on the complexity?

Time estimate: 
read script: 1.5 hour
draw a flowchart: 0.5 hour
build nodes in C-PAC: 1 hour
test and finalize: 1 hour

**Comment by HechengJin0** [comment]
https://app.lucidchart.com/invitations/accept/e600ce6d-c2a2-437f-9825-b52d46c4dd4a

**Comment by sgiavasis** [comment]
This is in v1.7.2.
