### ISSUE TITLE
🐛[Bug] functional to anat registration off, when set 'Selected Functional Volume' 

### ISSUE THREAD

**Issue by HechengJin0** [FCP-INDI/C-PAC#1381]
**Describe the bug**
func_reg_input :  ['Selected Functional Volume']
if we set ‘Selected Functional Volume’ as functional to anat registration EPI input, Func-to-anat registration (FLIRT) is off, especially for monkey data. 
If we set `func_reg_input :  ['Selected Functional Volume']`, the input image in FLIRT is raw data. while it should be the image after skullstripping.
Please reference func_reg_input :  [’mean functional`]

**To Reproduce**
1. pipeline config
func_reg_input :  ['Selected Functional Volume']
func_reg_input_volume :  1
2. check functional in anat space overlay anat edge in QC dir.
![image](https://user-images.githubusercontent.com/47699110/96502337-a36c4500-121f-11eb-99e5-1f0af3cc28e8.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/47699110/96502375-af580700-121f-11eb-88eb-c402ad2f334f.png)

**Versions** 
 - C-PAC: 1.7.1
 - Container Platform :
    - Docker 

**Additional context**
`/data3/cnl/monkey_benchmark/cpac_run/monkey_1016_oxford_cpac171master_tingmask_benchmark_config`
related code:
1. `selected_func_volume` in resource pool is raw data
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/func_preproc/func_ingress.py#L167-L211
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/registration/registration.py#L971-L981
2. reference 'mean_functional' in resource pool, which is after skullstripping. 
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/func_preproc/func_preproc.py#L1296-L1311
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/func_preproc/func_preproc.py#L1809

**Comment by sgiavasis** [comment]
@HechengJin0 Does this happen with other data?

**Comment by HechengJin0** [comment]
Didn't test human data, but monkey happens. fixed https://github.com/FCP-INDI/C-PAC/pull/1385. this fix should work for monkey.

**Comment by sgiavasis** [comment]
Actually I meant if it happens with other NHP data outside one subject.
Would be good to test for human too though.
