### ISSUE TITLE
✨ import default config in other pipeline configs 

### ISSUE THREAD

**Issue by SucyLi** [FCP-INDI/C-PAC#1383]
**Related problem**

Currently there are [13 custom pipeline configs](https://github.com/FCP-INDI/C-PAC/tree/master/CPAC/resources/configs) and [one default pipeline config](https://github.com/FCP-INDI/C-PAC/blob/master/dev/docker_data/default_pipeline.yml) in C-PAC. Any changes in the default config will require corresponding changes in other pipeline config, which can cause unnecessary overhead in development process.

**Proposed feature**

We propose an automatic pipeline config set-up process - import the default config in other pipeline configs and only change the fields which are different from the default config.

**Alternatives**

**Additional context**

**Comment by shnizzedy** [comment]
Continuing from https://github.com/FCP-INDI/C-PAC/pull/1395#issuecomment-723277714, I think we could import the default pipeline into [`schema.py`](https://github.com/FCP-INDI/C-PAC/blob/enh/nested_config/CPAC/pipeline/schema.py) and feed those defaults in so just [the validation step of loading a configuration](https://github.com/FCP-INDI/C-PAC/blob/013fe1b688ce5dac46c277d9e7a559083917d388/CPAC/utils/configuration.py#L25) could populate any non-specified values to defaults.

**Comment by sgiavasis** [comment]
This is in v1.8.
