### ISSUE TITLE
✨ Offer an option to use 3dBandpass in nuisance regression

### ISSUE THREAD

**Issue by SucyLi** [FCP-INDI/C-PAC#1412]
**Related problem**

Current C-PAC has our own [code](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/nuisance/bandpass.py) to perform bandpass filtering in nuisance regression, but Marco's rodent pipeline uses 3dBandpass. Our code and 3dBandpass output different results even with the same input (see correlation image from @HechengJin0):

<img src="https://user-images.githubusercontent.com/34257357/101831771-6ed08780-3b04-11eb-84ce-6542c5f03ca4.png" alt="image" width="400"/>

**Proposed feature**

Offer an option to use 3dBandpass in nuisance regression

**Alternatives**

**Additional context**

[Nipype Bandpass interface](https://nipype.readthedocs.io/en/0.12.0/interfaces/generated/nipype.interfaces.afni.preprocess.html#bandpass)

**Comment by sgiavasis** [comment]
This is in v1.8.
