### ISSUE TITLE
Custom regressor error 🐛 [User-reported Bug]

### ISSUE THREAD

**Issue by zeosmar** [FCP-INDI/C-PAC#1419]
**Describe the bug**
After including a two columns CSV file as a custom regressor in the pipeline config file, I'm getting the following compilation error: _AttributeError: 'list' object has no attribute 'get'_. The full error message can be seen in the attached screenshots along with the used nuisance regressors strategy.

**To Reproduce**
Just include a Custom regressor in the pipeline and put it to run.
 
**Screenshots**
![image (1)](https://user-images.githubusercontent.com/8835630/103301750-c5810100-49e0-11eb-820e-6b1ad110bee5.png)
![image (2)](https://user-images.githubusercontent.com/8835630/103301924-31fc0000-49e1-11eb-8cc1-b99bda8125f8.png)

**Versions** 
 - C-PAC: 1.7.0
 - Container Platform :
    - Docker:  18.06.1-ce using fcpindi/c-pac:release-v1.7.0

**Additional context**
For CPAC team at CMI: I'm running CPAC on Lisa. If necessary, my working directory is located on /data3/autism_center/wave2/QC/CPAC_1.7.0_no_notch

**Comment by SucyLi** [comment]
When I added `Custom` into nuisance regressor and tested the current master branch (1.7.2) locally, I got a error:

![image](https://user-images.githubusercontent.com/34257357/103303596-59989b80-49d4-11eb-936a-a6309d5b7c73.png)

**Comment by SucyLi** [comment]
After fixing the above issue, I am getting a new error:

![image](https://user-images.githubusercontent.com/34257357/103307061-27d80280-49dd-11eb-88ce-d40c52922f4a.png)

Related code:
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/nuisance/utils/__init__.py#L615-L620
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/nuisance/utils/crc.py#L34-L35

**Comment by SucyLi** [comment]
Fixed in https://github.com/FCP-INDI/C-PAC/pull/1420
