### ISSUE TITLE
🔧 Don't fork endpoints that don't impact the alternative

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1439]
> There is one thing I wanted to clarify actually - I realized it's a moot point to make the registrations and derivatives forkable, because the registrations lead to pipeline endpoints that don't impact the alternative (native-space endpoints), and because the derivatives are endpoints themselves.
> 
> In contrast, something like the preprocs should be forkable because On,Off would enable having the preprocessed data, and the raw data, both go into registration/nuisance/derivatives etc.
> 
> So those don't need to be lists, and we're probably better off removing the `if True in X` and just using a straight bool check like `if cfg.network_centrality['run']`:.
> 
> I'll actually merge this in because I'd like to get the container running now, and changing those bool checks are just a few lines and I can do it. But I wanted to let you know so everyone knows why it changed.

― @sgiavasis https://github.com/FCP-INDI/C-PAC/pull/1433#pullrequestreview-588126813

**Related problem**

```Python
bool([False]) == True
```
so whether a key is forkable matters. If a list is provided, `if key` will evaluate to `True` if the list is not empty. In #1433, I aimed for simplicity by:
1. making all the `run` keys lists
2. setting all [forkable options](https://github.com/FCP-INDI/C-PAC/blob/f185ed855232f56b8065a726ba6305a9fda2ff92/CPAC/pipeline/schema.py#L17) as lists when converting a dict to a Configuration (so lists of booleans stay lists of booleans; `False` or `Off` becomes `[False]`; `True` or `On` becomes `[True]`)
3. making all the checks `if True in key` instead of `if key`

Given the context above, we probably don't want to have some of these keys be forkable and should enforce providing a single boolean.

**Proposed feature**

1. Update [`schema.py`](https://github.com/FCP-INDI/C-PAC/blob/develop_v1.8_convergence/CPAC/pipeline/schema.py),  possibly [`default_pipeline.yml`](https://github.com/FCP-INDI/C-PAC/blob/develop_v1.8_convergence/dev/docker_data/default_pipeline.yml), and the preconfigs to make specific keys non-forkable and document which keys those are.
2. Update / revert the boolean checks in the files changed in #1433 from `if True in key` to `if key`

**Comment by sgiavasis** [comment]
This was resolved in v1.8.
