### ISSUE TITLE
✨ crash files should be human readable

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#1450]
It has always bothered me that crash files require a special tool to view. Instead of PKLZ it would be more valuable for the crashes to be written out as human readable files. Looks like Nipype has anticipated this too. They have an option that will change the output format of crash files to text, https://nipype.readthedocs.io/en/1.1.0/users/config_file.html

Look for ```crashfile_format``` under the execution parameters

This can be very easily changed in cpac_pipeline.py

**Comment by ccraddock** [comment]
Here is an example of the text formatted crash file, it contains everything that I think we need for debugging [crash-20210226-191233-UID1000-_func_motion_correct_3dvolreg_964-75d47825-06f3-4a75-9070-45a356f2ef79.txt](https://github.com/FCP-INDI/C-PAC/files/6052023/crash-20210226-191233-UID1000-_func_motion_correct_3dvolreg_964-75d47825-06f3-4a75-9070-45a356f2ef79.txt)

**Comment by shnizzedy** [comment]
I totally agree. For our purposes, a human-readable text file seems to be always (or almost always) useful and a Python pickle is rarely unpickled to do anything except read the text.

[This issue](https://github.com/shnizzedy/cpac/issues/9) was a pain point behind the initial iteration of the cpac wrapper package, and I think an end-user would prefer a text file to a pickle for almost any crash.

Also: https://github.com/FCP-INDI/C-PAC/issues/960#issuecomment-479580830

**Comment by sgiavasis** [comment]
This is now in v1.8.
