### ISSUE TITLE
✨ CCS harmonization

### ISSUE THREAD

**Issue by XinhuiLi** [FCP-INDI/C-PAC#1465]
**Related problem**

Overcome the reproducibility problem in neuroimaging studies

**Proposed feature**

Implement CCS minimal preprocessing pipeline (https://github.com/zuoxinian/CCS) as part of the reproducibility study

**Comment by SucyLi** [comment]
**Action items**

- [ ] Anatomical mask: add FreeSurfer-BET masking option
- [ ] Anatomical segmentation: add an option to select FreeSurfer segmentation labels
- [ ] Anatomical registration: open FLIRT + FNIRT argument options
- [ ] Functional bbreg: add FreeSurfer bbregister
