### ISSUE TITLE
✨ revisit fMRIPrep harmonization

### ISSUE THREAD

**Issue by XinhuiLi** [FCP-INDI/C-PAC#1466]
**Related problem**

Current fMRIPrep-options functional connectivity spatial correlation is around 0.95, which is not perfect compared with ABCD-options 0.99. 

**Proposed feature**

* Motion correction reference
Based on research in 2019, fMRIPrep applies 3dvolreg on 20-40th slices of timeseries and uses the median of these 20 slices along the third axis as the reference ([code](https://github.com/nipreps/niworkflows/blob/dda0b5fd2b9f30cb9d8bc48879c8407028a38af1/niworkflows/interfaces/registration.py#L359-L422)). 
fMRIPrep updates reference code recently ([code](https://github.com/nipreps/niworkflows/blob/master/niworkflows/interfaces/images.py#L218-L331)). LTS uses 3dvolreg by default, the first volume is used to generate reference and the median volume is used to perform motion correction.

* Coreg reference
* Single step resampling

**Alternatives**

**Additional context**

**Comment by SucyLi** [comment]
**Action items**
- [ ] Run fMRIPrep LTS version: https://github.com/nipreps/fmriprep/tree/maint/20.2.x
- [ ] Run C-PAC v1.8 fMRIPrep-options
- [ ] Compare outputs from both latest pipelines
