### ISSUE TITLE
🐛 [User-reported Bug] Latest singularity container points to old commit

### ISSUE THREAD

**Issue by tbweng** [FCP-INDI/C-PAC#1472]
**Describe the bug**

The latest C-PAC build on Singularity Hub is 1.7.2. It should be 1.8.0.

**To Reproduce**
1. `singularity pull shub://FCP-INDI/C-PAC`
2. Check pypeline.log file.
3. See top version is C-PAC 1.7.2

On singularity hub, the latest build points to this commit: 
https://github.com/FCP-INDI/C-PAC/commit/55ae58c004307294dae41ba4a60120ca444bf465

https://singularity-hub.org/containers/11614: 
Commit: 55ae58c004307294dae41ba4a60120ca444bf465
Branch: master

**Expected behavior**
Expected latest Singularity build to be 1.8.0

**Versions** 
 - C-PAC: 1.8.0
 - Container Platform:
    - Singularity:  3.7.0-1.el7

**Comment by sgiavasis** [comment]
Just re-triggered it. Sorry about that, that's my fault!
Let me know if it doesn't update.

**Comment by sgiavasis** [comment]
Hi @tbweng - did this end up working alright for you?

**Comment by tbweng** [comment]
Hi @sgiavasis , 
Yes, this worked. Thanks!
