### ISSUE TITLE
✨ Fixing random state via config or command line

### ISSUE THREAD

**Issue by gkiar** [FCP-INDI/C-PAC#1496]
**Related problem**

When performing reproducibility/variability experiments, it is important to isolate sources of variability. One such source is random state.

**Proposed feature**

It would be great to add a configuration variable or flag to the command-line of the `run.py` (at least in the case of the BIDS app, but this would apply to other interfaces as well) such that users can fix the random state of the execution. Importantly, this shouldn't just be set as the random seed within Python, but also for all of the called libraries (and if the dev team doesn't want to use the identical state for each step, for whatever reason, then at least have a deterministic seed selection based on a single user-supplied value).

**Additional context**

When we're considering evaluating the stability of the tool with respect to numerical error, or even in TRT settings, I believe this feature is a pre-requisite.

**Comment by gkiar** [comment]
Hey team — any update on whether or not this could be integrated soon? Thanks!

**Comment by shnizzedy** [comment]
In [v1.8.3](https://github.com/FCP-INDI/C-PAC/releases/tag/v1.8.3)
