### ISSUE TITLE
✨ ANTs num CPUs as a --parameter in the CLI and Docker interface

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1563]
### Related problem

It's easy to quickly modify performance parameters like `n_cpus` or `mem_gb` from command line, but in order to modify `num_ants_threads`, you still have to modify a pipeline config and provide it. And if you want to run something like the `default` pipeline, now you need to get an actual YAML, modify, etc.

### Proposed feature

It would be great if we opened access to `num_ants_threads` as well, especially since it's a parameter that is so commonly adjusted, and not related to the actual pipeline methods.

### Acceptance criteria

- [ ] Can provide something like `--num_ants_threads 3` (doesn't have to be that wording) and it will quickly update the pipeline config.

**Comment by shnizzedy** [comment]
Fixed in #1578
