### ISSUE TITLE
🐛"No module named bids_utils" error

### ISSUE THREAD

**Issue by amygutierrez** [FCP-INDI/C-PAC#1566]
### Describe the bug

When running on the server, this error appeared. Can get around this error by adding:
-v $PATH_TO_CPAC/dev/docker_data/bids_utils.py:/code/bids_utils.py to the docker run command. 

### To reproduce

Run C-PAC in server within a develop branch. 

### Expected behavior

Should not be receiving that error 

### Acceptance criteria

Error will not appear when starting a CPAC run in (Lisa) server 

### Screenshots

<img width="330" alt="Screen Shot 2021-09-16 at 11 19 29 AM" src="https://user-images.githubusercontent.com/58920810/133639418-3d109802-a7ab-413c-a25d-2e31fde5eda5.png">

**Comment by shnizzedy** [comment]
Related https://github.com/FCP-INDI/C-PAC/issues/1469
