### ISSUE TITLE
🐛 ACPC alignment crash if custom brain mask is offered

### ISSUE THREAD

**Issue by XinhuiLi** [FCP-INDI/C-PAC#1586]
### Describe the bug

ACPC alignment fails when a brain mask is offered

### To reproduce

1. Add brain mask in output dir
2. Turn on ACPC alignment

### Expected behavior

No crash

### Acceptance criteria

ACPC runs successfully without crash

### C-PAC version

v1.8.1

### Container platform

Docker

**Comment by shnizzedy** [comment]
Fixed in #1587
