### ISSUE TITLE
✨ CLI flags for scan inclusion

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1606]
### Related problem

There is no easy way to tell CPAC to only run one type of T1w or BOLD data from the command line. We can do it through the data config generator, but not through the CLI.

### Proposed feature

Similar to the `--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]` flag, it would be nice to have something like:

- `--T1w_label`
- `--bold_label`

### Acceptance criteria

- [x] `--T1w_label acq-VNavNorm` for an input file such as
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-CBIC/sub-NDARAA504CRN/anat/sub-NDARAA504CRN_acq-VNavNorm_T1w.nii.gz`
- [x] `--bold_label task-rest_run-1` for
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAC462DZH/func/sub-NDARAC462DZH_task-rest_run-1_bold.nii.gz`
- [x] `--bold_label [task-rest_run-1 task-rest_run-2]` to include both
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAC462DZH/func/sub-NDARAC462DZH_task-rest_run-1_bold.nii.gz` and
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAC462DZH/func/sub-NDARAC462DZH_task-rest_run-2_bold.nii.gz`

### Additional context

Caveats/points of possible complication:

- C-PAC currently combines `task-*`, `acq-*`, and `run-*` into one "scan label". For example, `task-rest_run-01` is listed as the scan name in the data configuration. This prevents the flexibility needed for full BIDS compliance - for example, it should be that selecting `--bold_label task-rest` should select both `task-rest_run-01` and `task-rest_run-02`, but at this moment, it would not. At the least, with the way the input data parser is structured.
  - This is worth changing, but may be much out of the scope of this issue and should probably be its own.
- C-PAC only runs one T1w per participant-session at a time, at this time. So providing a list of T1w labels may not be feasible right now. It may be worth making it so that C-PAC will run a pipeline for each T1w scan specified, though this feature may not be widely used/needed. Low priority.
- Currently, C-PAC will choose the first T1w it finds. This is not ideal if there are many different T1w's in the directory, and if this, by chance, leads the data configuration to have something like `acq-VNavNorm_T1w` for one participant and `acq-HCP_T1w` for another participant from the same site directory, for one run. Providing a `--T1w_label LABEL` would iron out this inconsistency (and possibly lead to participants being dropped if the user selects `acq-VNavNorm` for example, and some participants only have `acq-HCP`).
  - However, if the user does not provide this flag, we should still have something in place to look out for this inconsistency. It may be worth having a pre-defined set of priority (example, `VNavNorm` tends to be the T1w of choice), or maybe searching the `dataset_description.json` for any notes.
  - Either way, again this is beyond the scope and should be its own issue.

**Comment by shnizzedy** [comment]
Resolved in #1610
