### ISSUE TITLE
✨ Allow ingress of entire FreeSurfer output/participant directory

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1629]
### Related problem

If someone has already run Freesurfer on data and has the output, C-PAC currently doesn't have an easy way to pull that data in to bypass surface analysis (which is very time costly).

### Proposed feature

A field in the pipeline configuration file that will allow the user to provide a path to a Freesurfer output directory.

This would bypass the BIDS/BIDS-Derivatives directory ingress due to the multi-tiered nature of a Freesurfer output directory. However, C-PAC would still re-write out any computed outputs in BIDs-Derivatives automatically (the way it is now).

### Acceptance criteria

- [ ] Provide a completed Freesurfer directory and have C-PAC successfully bypass surface analysis and use these Freesurfer outputs in the pipeline.

**Comment by shnizzedy** [comment]
Resolved in #1630
