### ISSUE TITLE
Support: No data left after temporal filtering, for few subjects.

### ISSUE THREAD

**Issue by alexsavio** [FCP-INDI/C-PAC#168]
Hi,

Support Forum in NITRC is nearly empty, so I am writing here.

I'm processing COBRE schizophrenia database.
I left default parameters for temporal filtering (0.01-0.1Hz) and nuisance correction, all the results seem alright, except for only 3 subjects. Temporal filtering these resulted in empty volumes.

How can I rerun just the temporal filtering jobs for these subjects? The whole database seem quite homogeneous, what could be happening?
I would like to have ReHo and ALFF measures for these subjects, what do you recommend me to do?

Thank you very much.

Cheers,
Alexandre Savio

**Comment by dclark87** [comment]
Closed due to inactivity
