### ISSUE TITLE
🐛 'desc-denoisedNofilt_bold' not in resource pool if ['bandpass_filtering_order'] == 'Before'

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1821]
### Describe the bug

```Python
221104-11:44:23,706 nipype.workflow INFO:
         Connecting transform_denoisedNofilt_to_T1template...
221104-11:44:23,718 nipype.workflow ERROR:
         Building workflow failed
Traceback (most recent call last):
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1429, in build_workflow
    wf = connect_pipeline(wf, cfg, rpool, pipeline_blocks)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 1085, in connect_pipeline
    wf = nb.connect_block(wf, cfg, rpool)
  File "/code/CPAC/pipeline/engine.py", line 1293, in connect_block
    pipe_x, opt)
  File "/code/CPAC/registration/registration.py", line 3976, in warp_denoiseNofilt_to_T1template
    report_fetched=True)
  File "/code/CPAC/pipeline/engine.py", line 300, in get_data
    report_fetched=report_fetched)
  File "/code/CPAC/pipeline/engine.py", line 276, in get
    raise LookupError(info_msg)
LookupError: When trying to connect node block 'transform_denoisedNofilt_to_T1template' to workflow 'cpac_sub-NDARZA694WHF_ses-HBNsiteRU' after node block 'timeseries_extraction_AVG':

[!] C-PAC says: None of the listed resources are in the resource pool:

  ['desc-denoisedNofilt_bold']

Options:
- You can enable a node block earlier in the pipeline which produces these resources. Check the 'outputs:' field in a node block's documentation.
- You can directly provide this required data by pulling it from another BIDS directory using 'source_outputs_dir:' in the pipeline configuration, or by placing it directly in your C-PAC output directory.
- If you have done these, and you still get this message, please let us know through any of our support channels at: https://fcp-indi.github.io/
```

### Preconfig

- [X] rbc-options

### Expected behavior

f/alff works regardless of bandpass before / after regression

### Acceptance criteria

- [ ] f/alff works regardless of bandpass before / after regression
OR
- [ ] f/alff clearly requires bandpass after regression

### C-PAC version

v1.8.5-dev@ a273e24

### Container platform

Docker

### Additional context

`desc_keys[2]` is `desc-denoisedNofilt_bold`, and it's only defined for bandpass-after:
https://github.com/FCP-INDI/C-PAC/blob/a273e2430072cd6ceb39c51da1459ac06f873e96/CPAC/nuisance/nuisance.py#L2500-L2537

**Comment by sgiavasis** [comment]
This is probably just going to be a guard rail. If the user wants filtering to happen before nuisance, but they want ALFF and f/ALFF, then either they get a non-denoised time series going into ALFF, or they'll have to settle for nuisance and filtering afterwards, but only for the data going into ALFF.

Either way isn't ideal.

**Comment by shnizzedy** [comment]
> This is probably just going to be a guard rail. If the user wants filtering to happen before nuisance, but they want ALFF and f/ALFF, then either they get a non-denoised time series going into ALFF, or they'll have to settle for nuisance and filtering afterwards, but only for the data going into ALFF.
> 
> Either way isn't ideal.

What do we want for `rbc-options`?

**Comment by shnizzedy** [comment]
https://github.com/FCP-INDI/C-PAC/pull/1824#discussion_r1017020198
