### ISSUE TITLE
✨ Seamless ingress of fmriprep outputs

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#1902]
### Related problem

It's not easy (or possible) to directly ingress already-computed outputs into C-PAC from other pipelines (or specifically fmriprep) in order to perform further processing.

### Proposed feature

The ability to ingress fmriprep output data directly into the C-PAC resource pool, so that users can then proceed to perform further processing. Example: pulling in the `confounds.tsv` and also the BOLD time series that has already been preprocessed and warped to template; then, C-PAC can proceed with denoising and anything else, including calculating connectomes and other derivatives.

Note: C-PAC v1.8+ has code/infrastructure to allow ingress of already-computed data into the resource pool, but needs to be expanded to make the process seamless.

### Acceptance criteria

- [ ] New field in the data configuration YAML which holds the path to an fmriprep output directory
- [ ] Each possible layout of fmriprep outputs able to be pulled into C-PAC flexibly without issues (i.e. surface on or off)
- [ ] Clearly-defined user flow: if the user has preprocessing selected in the pipeline config, and already-preprocessed data is pulled in, C-PAC needs to handle this safely

### Additional context

There is also the question and possibility of forking. It's possible we can have the user provide an fmriprep output directory and also select a modified version of the `fmriprep-options` preconfig which includes denoising and derivatives, and have C-PAC write out the end result of both for comparison easily.

### Reference

Branch: https://github.com/FCP-INDI/C-PAC/tree/feature/fmriprep_ingress

**Comment by sgiavasis** [comment]
From earlier discussion:

Good first target is getting the fmriprep outputs ingressed into the resource pool, and testing a couple simple things:

- [ ] Taking the whole output dataset in, will C-PAC smoothly proceed with denoising/nuisance regression and derivative calculation?
- [ ] Taking only the T1w-related outputs in, and anatomical preprocessing and registration turned `Off` in C-PAC, will C-PAC seamlessly proceed with BOLD preprocessing, coregistration, and final BOLD time-series warp to template?

**Comment by sgiavasis** [comment]
@e-kenneally resolves issue with the func datasource connection.

Next:
- [ ] Update the internal guardrails to accommodate a data dictionary that works with fmriprep output directory files.
- [ ] Try using fmriprep's confounds.tsv directly with AFNI 3dTproject to see if it works out of the box.
- [ ] Ascertain BIDS standard for confounds/regressors and change CPAC's naming of `regressors` to `confounds` if necessary.

**Comment by e-kenneally** [comment]
Current issue: quadruple-nested workdir folders - there is a `_scan-{scan_name}` folder for EVERY scan inside every `_scan-{scan-name}` folder in the working directory.

This is what I know about the problem so far:

- I see the same forking issue (super nested workdir folders) if I create a datasource node for every func file, or just for each key 
- Forking doesn’t happen if I only pass one scan name for every resource in the inputnode.iterables field , but then only one version / scan of each file ends up in the func output
- Everything runs smoothly and the scan iterables are handled when scan iterables handled outside of loop, but then not tied to the correct ingress node, just the last one to be created in the loop. 
        - Also, this is the case where they aren’t correctly matched up with the files.

**Comment by sgiavasis** [comment]
This was resolved in v1.8.6.
