### ISSUE TITLE
🐛 .proc-* files get saved in current working directory

### ISSUE THREAD

**Issue by amygutierrez** [FCP-INDI/C-PAC#1955]
### Describe the bug

.proc-####_time-* files, which are generated by nipype, get saved into the current working directory. It might be deleted after the runs are done, but if there is a crash or if you cancel the job, the files do not get deleted. 

### To reproduce

1. Run C-PAC develop branch
2. You will notice that in the current working directory (wherever you ran the cpac command), the `.proc*` files will appear.

### Preconfig

- [X] default
- [X] abcd-options
- [X] anat-only
- [X] blank
- [X] ccs-options
- [X] fmriprep-options
- [X] fx-options
- [X] monkey
- [X] monkey-ABCD
- [X] ndmg
- [X] nhp-macaque
- [X] preproc
- [X] rbc-options
- [X] rodent

### Run command

Tested in ACCESS with singularity: 

```
#!/usr/bin/bash
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH -t 14:00:00
#SBATCH --ntasks-per-node=20

HOME=${HOME} \
singularity run \
    --cleanenv \
    -B ${MED} \
    -B ${DATA}:${DATA} \
    -B ${OUTPUT}:${OUTPUT} \
    -B ${CONFIG}:${CONFIG} \
    -B ${PIPELINE_CONFIGS}:${PIPELINE_CONFIGS} \
    ${IMAGE} ${DATA} ${OUTPUT} participant \
    --save_working_dir --skip_bids_validator \
    --pipeline_file ${PIPELINE_CONFIGS}/${pipeline}_seed.yml \
    --data_config_file ${CONFIG}/data_config_regtest_${data}.yml \
    --n_cpus 18 --mem_gb 60
```

### Expected behavior

.proc files get generated and saved in cwd of terminal as soon as CPAC run starts.

### Acceptance criteria

no `.proc*` should be getting written/saved in the current working directory. Maybe they can get moved to a `tmp` folder in the container.

### Screenshots

<img width="755" alt="Screenshot 2023-06-21 at 3 36 33 PM" src="https://github.com/FCP-INDI/C-PAC/assets/58920810/8dd7cd39-78e0-49e4-a5a6-4634147d6c7e">

### C-PAC version

v1.8.6dev

**Comment by amygutierrez** [comment]
Suggestion from @shnizzedy 
```
for proc in pathlib.Path.cwd().glob('.proc-*_time-*.*_freq-*'):
    if proc.is_dir():
        proc.rmdir()
    else:
        proc.unlink()
```

**Comment by shnizzedy** [comment]
☝️ in this https://github.com/FCP-INDI/C-PAC/blob/bc851da4bcb7003992ca300e99027ffbcb80bc04/CPAC/pipeline/cpac_pipeline.py#L766 block
