### ISSUE TITLE
📦️ Build AFNI without SUMA

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1967]
### Related problem

SUMA requires libraries not otherwise required by AFNI or C-PAC and is potentially unnecessary to build.

### Proposed feature

We take [this makefile](https://github.com/afni/afni/blob/AFNI_23.1.10/src/other_builds/Makefile.linux_ubuntu_22_64), comment out or remove the SUMA lines, and build from there.

### Acceptance criteria

- [x] AFNI builds without SUMA
- [ ] AFNI tools built without SUMA run and produce identical results to AFNI tools built with SUMA

### Alternatives

No change, keep building AFNI with SUMA then paring down

### Additional context

When we comment out or remove

```Makefile
INSTALL_PREREQ = suma_gts
```

we might need to separatenly install [`gsl-bin`](https://www.gnu.org/software/gsl/)

**Comment by nx10** [comment]
[There is a flag in the cmake config for disabling SUMA](https://github.com/afni/afni/blob/8cae3af2d4c1426fadf16768ee42a961930041c2/src/CMakeLists.txt#L125)

**Comment by shnizzedy** [comment]
3dSkullStrip seems to require SUMA, so we'll need to keep it
