### ISSUE TITLE
🐛 Using the unfiltered head motion parameters (rotation and translation) for nuisance regression even for forks with the filter on?

### ISSUE THREAD

**Issue by shnizzedy** [FCP-INDI/C-PAC#1985]
### Describe the bug
> unfortunately it is looking like the output timeseries from the preprocessed data are identical for `notch-none`  `notch-notch4fc0p31bw0p12` and the run-specific notch pipelines only when there is no censoring. Based on this, I am wondering whether c-pac is using the filtered Jenkinson FD timeseries for censoring, but still using the _unfiltered_ head motion parameters (rotation and translation) for nuisance regression even for forks with the filter on.
― https://danlabc-pac.slack.com/archives/C01AESSCX8W/p1692104120536609

### Expected behavior
Filtered head motion parameters are used for nuisance regression

### Acceptance criteria
- [x] Filtered head motion parameters are used for nuisance regression

### Additional context
It’s [somewhat by design](https://github.com/FCP-INDI/C-PAC/pull/1919#only-fdj) and mostly a mistake. When I separated out filtered-motion-parameters from motion-parameters so we could output both, I didn’t update the node that take motion-parameters as input to filtered-motion-parameters, which I assume they all should? I’ll make that update

**Comment by nimzodisaster** [comment]
I am interested in using the filtered motion parameters. If I pull the nightly, will it have the latest patch for this, or is that still in development?
Also, am I right in understanding that if I JUST choose filtered, it will be produced correctly in 1.8.5?

thanks

**Comment by shnizzedy** [comment]
@nimzodisaster 

> If I pull the nightly, will it have the latest patch for this, or is that still in development?

If you want a use-at-your-own-risk in-development version of this feature, you probably want `ghcr.io/fcp-indi/c-pac:filt_downstream` (that's the branch image for #1989 which is the PR to address this issue)

> Also, am I right in understanding that if I JUST choose filtered, it will be produced correctly in 1.8.5?

Yes, it should be, except [FDJ won't reflect the filtering in <1.8.6](https://github.com/FCP-INDI/C-PAC/issues/1891)! This issue arose in the fix for that one, both in the 1.8.6 development cycle

**Comment by shnizzedy** [comment]
Fixed in [`1.8.6`](https://github.com/FCP-INDI/C-PAC/releases/tag/v1.8.6)
