### ISSUE TITLE
Relative Paths for Symlinks and QC?

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#209]
Use Case:

User runs CPAC, including the generation of symlinks and QC pages. They then move the folder containing the sink directory to a different location. Symlinks and QC are now broken, because they use absolute paths to point to the original location of the files.

(This happened to me earlier today)

Would it be possible to have these features use relative paths instead?

**Comment by sgiavasis** [comment]
This can now be closed.
