### ISSUE TITLE
Need to provide enough information to debug error in config file

### ISSUE THREAD

**Issue by conge** [FCP-INDI/C-PAC#230]
if user put a line or two what are not follow YAML format, CPAC will give a error message stating " Error reading config file".

Given the fact that the config file is now more than 600 lines, it will be very helpful to point out at with line the error occurs. Will make debugging easier.

This is not urgent.

Yang

**Comment by anibalsolon** [comment]
Fixed on 7b3e59a0af11733dff394d0d9c2249f6d063a854 for release 1.4.2.
