### ISSUE TITLE
Smooth 4D functional data

### ISSUE THREAD

**Issue by czarrar** [FCP-INDI/C-PAC#258]
Have an option to smooth the 4D functional data in native space or in standard space.

**Comment by sgiavasis** [comment]
Motion-corrected functional in standard space now gets smoothed (when optional functional outputs are selected), but we can do the same with native, and also other forms of the time series.

**Comment by HechengJin0** [comment]
it is done [smooth 4d data #1261](https://github.com/FCP-INDI/C-PAC/pull/1261)
reopen it?

**Comment by sgiavasis** [comment]
Nope, was just moving it from Backlog to Review/Done.
I just linked the PR.

**Comment by sgiavasis** [comment]
This is in v1.7.0!
