### ISSUE TITLE
Default values for symmetric standard files can be incorrect

### ISSUE THREAD

**Issue by czarrar** [FCP-INDI/C-PAC#263]
Within the config file, I=if I set a standard resolution of 3mm, then the values for the different symmetric images (brainSymmetric, symmStandard, and twommBrainMaskDiluted) do not work. It seems like these files only exist for 2mm and since they depend on the standardResolution variable this causes a problem when standardResolution is anything but 2mm.

**Comment by ccraddock** [comment]
Check to make sure that 3mm symmetric are included in image resources

**Comment by jpellman** [comment]
The C-PAC resources tar contains the following 3mm template files:

MNI152_T1_3mm_brain_mask_symmetric_dil.nii.gz
MNI152_T1_3mm_brain_symmetric.nii.gz
MNI152_T1_3mm_symmetric.nii.gz
T1_2_MNI152_3mm_symmetric.cnf

These get put in $FSLDIR/data/standard along with the other symmetric template files by the installer script.
