### ISSUE TITLE
Create_montage crashes sometimes with Remove Working Directory turned On.

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#270]
More specifically, a node after resample_u crashes when it cannot find the output of resample_u (which is the MNI brain resampled to 1mm).

It is possible that maybe the output file is being deleted during the removal of the working directory files, but the folder is not deleted yet when the pipeline reaches this point, leading Nipype to think that this step has already been completed.

Removing the working directory files manually prior to running CPAC avoids this problem.

**Comment by ccraddock** [comment]
Please check if this is still a problem and resolve.

**Comment by sgiavasis** [comment]
This will be re-evaluated in the QA Pages refactoring in the release after this one (1.0.2).
