### ISSUE TITLE
CPAC should always write to log files, not stdout/stderr

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#274]
There are a few obvious reasons for this, most notably that it's important/useful to have a log of the output that you can go back to later without having to manually pipe CPAC into a text file.

More importantly, it occurred to me yesterday that writing to stdout might be slowing things down, and a thread on stackoverflow (http://stackoverflow.com/questions/3857052/why-is-printing-to-stdout-so-slow-can-it-be-sped-up) suggest that this might indeed be the case.

**Comment by sgiavasis** [comment]
Logging has been mostly overhauled. Will adhere to this going forward as well.
