### ISSUE TITLE
CPAC does not include newly calculated SCA maps in Group Analysis when running from a previously generated output directory.

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#277]
Related to #276, may be due to not running the QC or symlinks workflow (see below).

1) Run SCA on a new ROI file in a previously generated output directory.

2) Run Group Analysis (making sure ROI average SCA is selected as a derivative).

Result: GA will run on only the original seeds.

When I look at the path files, the new seed has not been added. When I ran the new seeds, I turned off the QC and symlinks workflows to speed things up (which it did, a LOT, but that's another issue), so I wonder if manipulating/generating the path files is only called if those workflows are active.

**Comment by sgiavasis** [comment]
Enough has changed that this is no longer an issue. Closing.
