### ISSUE TITLE
Not sure how subjects are ordered in subject_List_group_analysis.txt file. 

### ISSUE THREAD

**Issue by ZhenYangCMI** [FCP-INDI/C-PAC#293]
The order is different from my subject list and also not in ascending or descending order. If this order information is used in group analysis, they may not match my phenotypic data.

**Comment by ccraddock** [comment]
Verify that the subject list to phenotypic file mapping is correct. Suggest enforcing some order on writing out these files, such as sorting IDs in ascending order.
