### ISSUE TITLE
Add informative error message if "subjects to include" file is not formatted properly.

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#303]
(In the generate new subject list window)

Currently, an improperly formatted subject list file (e.g. if there is a space or a tab before the subject on each line), CPAC will popup the "None type not iterable" error, which isn't informative.

**Comment by dclark87** [comment]
I have tested and fixed this issue in my latest commit and merged it with FCP-INDI's 0.3.9_development branch, here: https://github.com/FCP-INDI/C-PAC/commit/c44334621f0586c7cbdbe92673dd913c58a0da62
