### ISSUE TITLE
Group analysis reads only a subset of subjects from the specified subject list.

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#305]
In 0.3.3 (my copy with the pipeline name fix for the GUI).

Steps to reproduce:
I specify a CPAC subject list (the YAML file) and group analysis subject list (the .txt. file), both with 43 subjects. I set GA to run on any derivative or combination of derivatives.

CPAC builds and runs a model with only 39 subjects. It looks from stdout like these are all it is seeing when it reads in the subject list .txt file.

I've manually run the same model through FSL on the full 43 subjects (using a bash script that just pulls the derivative files for each subject in the list), and all subjects have all the derivatives, so I don't think CPAC is dropping them for that reason.

This problem occurs for all derivatives I have tried (ALFF, f/ALFF, Dual Regression, Centrality, ReHo, and VMHC).

**Comment by dclark87** [comment]
Haven't seen this recently come up, so we're closing it.
