### ISSUE TITLE
Group analysis fail: Could not create ftst file

### ISSUE THREAD

**Issue by czarrar** [FCP-INDI/C-PAC#309]
Group analysis fails in generating the F-test file if there is only one contrast present in the contrast file. Below indicates the offending lines.

``` python
data = np.genfromtxt(con_file, names=True, delimiter=',', dtype=None)
...
# see line: 545 in CPAC/utils/create_fsl_model.py
lst = data.tolist()
...
for tp in lst:
    contrast_names.append(tp[0])
    ....
```

When the data object is read in and converted into a list, when there is only one line in the data matrix then the list is actually a tuple. It will only be a list if data has 2 or more rows. This issue then leads to an error when calling `tp[0]`, which is actually a string and not the first column of that row.

**Comment by sgiavasis** [comment]
This will be in the 0.3.9 release!
