### ISSUE TITLE
CPAC GUI should check subject list exists before continuing with Load dialog

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#318]
Currently, in 0.3.4, if you click to load a subject list, but paste in a non-existent path, it continues with asking for a name, displaying the list in the GUI, etc. At no point does it throw an error, until you try and run a pipeline, at which stage it complains about not having a properly formatted YAML file.

**Comment by dclark87** [comment]
Fixed this issue in commit https://github.com/FCP-INDI/C-PAC/commit/e4d8ee19de64033ba2706a7aaa451cf2aa4c677c. This will be in the 0.3.9 release.
