### ISSUE TITLE
CPAC should check scan types (anat/functional) before starting pipeline.

### ISSUE THREAD

**Issue by danlurie** [FCP-INDI/C-PAC#319]
I ran into an issue today where anatomical files were accidentally specified as functional files in the subject list (due to a mis-specified functional file path template). 

When CPAC tried to start functional preprocessing on these files, it crashed. Specifically, it tried to execute `func_get_idx` and returned:

```
<string> in get_idx(in_files, stop_idx, start_idx)

IndexError: tuple index out of range
Interface Function failed to run. 
 <string>(38)get_idx()
```

I figure this is an issue that will be relatively common once we get a larger user base, so perhaps CPAC should do a rudimentary check to confirm that the files specified are of the right type. Something like confirming that specified anatomicals have only 1 volume, and specified functionals have >1 volume.

**Comment by ccraddock** [comment]
Add in basic check to verify that anatomicals are 3D files (only one volume) and fmri are 4D files (more than one volume). Can also through an error if the fmri data contains too few volumes for further analysis (i.e. no volumes left after discarding first N volumes)

**Comment by dclark87** [comment]
Added check for this in: https://github.com/FCP-INDI/C-PAC/commit/6f44d9c6fd9631311a91f0be11da0e18849a15f6; closing
