### ISSUE TITLE
C-PAC 0.3.4 - standard preprocessing takes more than 24h for one subject

### ISSUE THREAD

**Issue by ababino** [FCP-INDI/C-PAC#362]
Dear CPAC development team,
thanks for this great tool. I downloaded and installed CPAC successfully. Then I downloaded some fmri data from the 1000 Functional Connectomes Project.

In order to test the tool I created a subject list with subject `sub17017` only from the Baltimore dataset (available in http://www.nitrc.org/frs/downloadlink.php/1600) and executed what I thought it was a standard preprocessing pipeline. Now C-PAC has been executing `nonlinear_reg_1` for more than 24h.

Here I paste my .yml subject list and my .yml pipeline configuration file
* https://gist.github.com/ababino/25827a03c0a8bb65f24f#file-pipeline_config_test_2mm-yml
* https://gist.github.com/ababino/25827a03c0a8bb65f24f#file-subject_list-yml

I also paste the last lines of the pypeline.log
```
140626-18:48:23,981 workflow INFO:
	 [Job finished] jobname: sinker_33.c0 jobid: 22
140626-18:48:23,987 workflow INFO:
	 Submitting 12 jobs
140626-18:48:23,990 workflow INFO:
	 Executing: link_33.c0 ID: 23
140626-18:48:23,995 workflow INFO:
	 Executing: link_31.c0 ID: 33
140626-18:48:23,999 workflow INFO:
	 Executing: link_25.c0 ID: 59
140626-18:48:24,3 workflow INFO:
	 Executing: link_57 ID: 70
140626-18:48:24,7 workflow INFO:
	 Executing: link_56 ID: 73
140626-18:48:24,11 workflow INFO:
	 Executing: link_72 ID: 93
140626-18:48:24,16 workflow INFO:
	 Executing: link_74 ID: 95
140626-18:48:24,20 workflow INFO:
	 Executing: link_75 ID: 97
140626-18:48:24,25 workflow INFO:
	 Executing: link_73 ID: 100
140626-18:48:24,32 workflow INFO:
	 Executing: inv_linear_reg0_xfm ID: 109
140626-18:48:24,35 workflow INFO:
	 Executing: sinker_9 ID: 114
140626-18:48:24,40 workflow INFO:
	 Executing: nonlinear_reg_1 ID: 116
```

I hope you could help me.

Thanks!

Andrés

**Comment by sgiavasis** [comment]
Closing this issue for now then. @ababino, when you are ready to return, please do not hesitate to re-open a new issue. Thank you!
