### ISSUE TITLE
CPAC error: cpac_runner_003

### ISSUE THREAD

**Issue by zedtower** [FCP-INDI/C-PAC#365]
Goodmorning,

I'm a new user of CPAC package for neuroimaging analysis. When I tried to run an analysis at individual level I had this problem:

running for configuration, subject list, pipeline_id --> /home/utente/Lavoro_PD_PDD_LBD_FSL/CPAC/pipeline_config_PD_PDD_LBD.yml /home/utente/Lavoro_PD_PDD_LBD_FSL/CPAC/output/CPAC_subject_list.yml PD_PDD_LBD
corrections dictionary list: 
None

ERROR: There are no strategies to build.
Error name: cpac_runner_0003

Unhandled exception in thread started by <bound method ListBox.runAnalysis1 of <CPAC.GUI.interface.windows.main_window.ListBox; proxy of <Swig Object of type 'wxFrame *' at 0x3ec2280> >>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/windows/main_window.py", line 225, in runAnalysis1
    CPAC.pipeline.cpac_runner.run(pipeline, sublist, p)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_runner.py", line 392, in run
    strategies = sorted(build_strategies(c))
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_runner.py", line 179, in build_strategies
    raise Exception
Exception

Any ideas?

Thank you in advance,

Enrico

**Comment by jpellman** [comment]
Hello Enrico,

If this is still an issue, can you re-send your pipeline configuration file to john.pellman@childmind.org?  When attachments are sent to notifications@github.com we are unable to see them (or the e-mails that they are attached to)?

Best,
John Pellman
