### ISSUE TITLE
CPAC preprocessing crashed in anat_skullstrip

### ISSUE THREAD

**Issue by albertleemon** [FCP-INDI/C-PAC#370]
Hello.

I'm trying this nice software (CPAC 0.3.5) to preprocess my data. Unfortunately, I have a similar problem of segmentation/anat_skullstrip as described by @didhavn in https://github.com/FCP-INDI/C-PAC/issues/366.  Here is the error message in my log file. 

140923-17:38:03,349 workflow INFO:
     Executing node skull_edge_0 in dir: /media/TOSHIBA_EXT/newdata2/cpac/work/resting_preproc_dp37_2/skull_edge_0
140923-17:38:04,620 workflow ERROR:
     ['Node anat_skullstrip failed to run on host fmri-Canlab.']
140923-17:38:04,621 workflow INFO:
     Saving crash info to /media/TOSHIBA_EXT/newdata2/cpac/log/crash-20140923-173804-fmri-anat_skullstrip.pklz
140923-17:38:04,621 workflow INFO:
     Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1390, in run
    self._run_interface()
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1500, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1626, in _run_command
    result = self._interface.run()
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 959, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 1053, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: File/Directory '/media/TOSHIBA_EXT/newdata2/cpac/work/resting_preproc_dp37_2/anat_preproc_0/anat_skullstrip/t1_resample_skullstrip+orig.BRIK' not found for SkullStrip output 'out_file'.
Interface SkullStrip failed to run. 

Instead of t1_resample_skullstrip+orig.BRIK file, we have a  t1_resample_skullstrip.nii in the  anat_skullstrip folder. Here is everything in this folder. 
$ls '/cpac/work/resting_preproc_dp37_2/anat_preproc_0/anat_skullstrip' 
command.txt   _node.pklz  t1_resample.nii.gz
_inputs.pklz  _report     t1_resample_skullstrip.nii

I thought this could be a problem related to parameter definition in source code. However, I have no clue how to fix it. I have tried everything suggested by @sgiavasis. You can find more details as follows. 

1). To check the command from the command.txt in the anat_preproc_0/anat_skullstrip folder. 
Here it is. 
3dSkullStrip -input /media/TOSHIBA_EXT/newdata2/cpac/work/resting_preproc_dp37_2/anat_preproc_0/anat_skullstrip/t1_resample.nii.gz -prefix t1_resample_skullstrip

2). To check the  content of  "report.rst".
Here is what we got.
Exec ID : anat_skullstrip
Original Inputs
- args : <undefined>
- environ : {}
- ignore_exception : False
- in_file : /media/.../cpac/work/resting_preproc_dp37_2/anat_preproc_0/anat_reorient/t1_resample.nii.gz
- out_file : <undefined>
- outputtype : AFNI
  terminal_output : allatonce

3). to check and run 3dSkullStrip in terminal
$ 3dSkullStrip -help
Usage: A program to extract the brain from surrounding.
tissue from MRI T1-weighted images. 
The simplest command would be:
        3dSkullStrip <-input DSET>

$ 3dSkullStrip -input /media/TOSHIBA_EXT/newdata2/cpac/work/resting_preproc_dp37_2/anat_preproc_0/anat_skullstrip/t1_resample.nii.gz -prefix t1_resample_skullstrip
The intensity in the output dataset is a modified version
of the intensity in the input volume.
To obtain a masked version of the input with identical values inside
the brain, you can either use 3dSkullStrip's -orig_vol option
or run the following command:
  3dcalc -a /media/TOSHIBA_EXT/newdata2/cpac/work/resting_preproc_dp37_2/anat_preproc_0/anat_skullstrip/t1_resample.nii.gz -b t1_resample_skullstrip+orig -expr 'a*step(b)' \
         -prefix t1_resample_skullstrip_orig_vol
to generate a new masked version of the input.

4).  Afterwards I tried this: 3drefit -view orig anat_preproc_0/anat_skullstrip$  3drefit -view orig ../anat_reorient/t1_resample.nii.gz
++ 3drefit: AFNI version=AFNI_2011_12_21_1014 (Mar 19 2012) [64-bit]
++ Authored by: RW Cox
++ Processing AFNI dataset ../anat_reorient/t1_resample.nii.gz
- Didn't make any changes for dataset ../anat_reorient/t1_resample.nii.gz !
  ++ 3drefit processed 1 datasets

I am very thankfull for any comment and suggestion.

**Comment by jpellman** [comment]
Hi albertleemon,

Are you using the version of AFNI included in the Neurodebian repositories?  We have encountered issues in the past in getting that to work with C-PAC.

Best,
John Pellman

**Comment by albertleemon** [comment]
Hi John


Thanks for your information.
I get AFNI from its official website.
Any idea which repository could work with C-PAC?

Best,
Meng

**Comment by jpellman** [comment]
Hi Meng,

The version of AFNI directly from the NIH website should work with C-PAC.  Since we've eliminated the possibility of an incompatible binary, could you try performing the steps outlined <a href=https://github.com/FCP-INDI/C-PAC/issues/366#issuecomment-70741249>here</a> and see if they help?  Also, make sure that you are using 3drefit with AFNI's BRIK format, since 3drefit cannot act upon NIFTI files.

Regards,
John Pellman

**Comment by albertleemon** [comment]
Hi John,

I'll give one more try. Thanks for your suggestion.

Best,
Meng

**Comment by sgiavasis** [comment]
Closing this issue because it has been awhile. If there are any more issues or questions, please feel free to open a new one.

Best,
The C-PAC Team
