### ISSUE TITLE
LinAlg error if segmentation thresholding is too high

### ISSUE THREAD

**Issue by dclark87** [FCP-INDI/C-PAC#387]
Noticed this earlier today and several times in the past.

When CPAC does GM/WM/CSF segmentation, and the probability maps it produces are below the respective thresholds input in the config file, CPAC crashes (due to a LinAlg error) during nuisance correction (if the user uses those signals to in their strategy).

We should put a check in for this.

**Comment by dclark87** [comment]
This fix was made in the 0-variance check made by @ccraddock for commit https://github.com/FCP-INDI/C-PAC/commit/240942547ee42326486cf2227177cf1e032d9e5b. It will be in the 0.3.9 release

**Comment by jpellman** [comment]
Some of our users are experiencing the LinAlg error again in 0.3.9.1.  The specific line where the error originates is [here](https://github.com/FCP-INDI/C-PAC/blob/d78861001e3dc3fef7b785710cf06a7dc3a9efeb/CPAC/nuisance/nuisance.py#L236).

**Comment by sgiavasis** [comment]
Thresholding has been removed in 1.0.0.
