### ISSUE TITLE
Group Analysis [Measure_Mean]: v 0.3.7.

### ISSUE THREAD

**Issue by msk1105** [FCP-INDI/C-PAC#404]
Even when I select only "smoothed & zscore std" (not "raw score") for group analysis, CPAC seems to include "Measure_Mean" as an EV. That is, after uploading an EV file, "Measure_Mean" is automatically added to the Model Setup box (and also to Design Matrix Formula). See the image below. 

As "Measure_Mean" should be included as an EV *only* when we use raw score (to covary out "Measure_Mean" at the group level), I want to double check if CPAC can add "Measure_Mean" only when raw score is selected/used by users. 

Maki 

![slide1](https://cloud.githubusercontent.com/assets/8195791/5192517/1692c3a4-74c6-11e4-8ae0-9f3477cea315.png)

**Comment by ccraddock** [comment]
I think that this is a documentation issue. When z-score is included, please do not include automatically include measure_mean in the model specification equation, but do continue to calculate the measure mean and add it to the internal phenotype file. This way a user can include measure_mean with z-score if they like. This requires that the model can only run on z-scored derivatives or non-z-scored derivatives and not both. Please verify that this is the case.

**Comment by sgiavasis** [comment]
This will be resolved in 0.3.9.
