### ISSUE TITLE
Group Analysis [Mask for Measure_Mean]: v 0.3.7.

### ISSUE THREAD

**Issue by msk1105** [FCP-INDI/C-PAC#405]
Does CPAC compute "Measure_Mean" for each subject using "group-specific mask" or "individual mask"? I prefer the use of "group-specific mask", by the way. 

Maki

**Comment by sgiavasis** [comment]
There will be an option to use either a group specific mask or an individual specific mask in the group analysis model builder GUI. Closing this issue now, but this feature will be released with 0.3.9.
