### ISSUE TITLE
CPAC error  after installation

### ISSUE THREAD

**Issue by jonwieser** [FCP-INDI/C-PAC#413]
HI
I recently installed CPAC .  After installation, I ran the program and got the following  error:

psy-blackbird:~ wieser$ cpac_gui
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.

how do i fix this ?
the software  was installed on Mac OS   10.6.8

**Comment by jaipel** [comment]
Hi all-

Try seeing if the solution for the following related issue helps: https://github.com/FCP-INDI/C-PAC/issues/430#issuecomment-69824990

**Comment by jonwieser** [comment]
I created the Bash script file

Contents of script file:?

#!/bin/bash

# what real Python executable to use
PYVER=2.7
PYTHON=/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..'))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV
exec $PYTHON "$@"


When I ran the script file, I got the error:
./cpac.bash: line 8: /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7: No such file or directory
./cpac.bash: line 12: /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7: No such file or directory
./cpac.bash: line 12: exec: /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7: cannot execute: No such file or directory


I looked  in the /Library/Frameworks  directory
There is no directory named:  Python.framework

 Jon



________________________________

**Comment by jpellman** [comment]
Hi Jon-

Normally, official Python releases are stored in '/Library/Frameworks/Python.framework'.  Apple's version of Python is stored in '/System/Library/Frameworks/Python.framework'.  With your particular configuration, you don't seem to have an official python.org binary. You could try to re-run the script with PYTHON set to '/System/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER' instead to use Apple's default installation of Python.  Alternatively, you could install the <a href=https://www.python.org/ftp/python/2.7.8/python-2.7.8-macosx10.6.dmg>official binary</a> from the Python website and then run the script again.

John Pellman

**Comment by jonwieser** [comment]
HI john,

Thanks for the help. I modified the script to  /System/Library/Frameworks/Python.framework

however our current version of Python was 2.6, not 2.7


/System/Library/Frameworks/Python.framework/Versions/2.6/bin




Contents of the script  "cpac.bash:


#!/bin/bash

# what real Python executable to use
PYVER=2.6
PYTHON=/System/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..'))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV
exec $PYTHON "$@"





I ran the script,


bash-3.2$ ./cpac.bash
'import site' failed; use -v for traceback
Python 2.6.1 (r261:67515, Aug  2 2010, 20:10:18)
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>



and it produced a python prompt.

I then tried to import CPAC


>>> import CPAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named CPAC



Since we didn't have python 2.7, I downloaded python 2.7 from the link in your e-mail. I installed python 2.7

I now have the directory:

/Library/Frameworks/Python.framework/Versions/2.7/bin

and python 2.7 is in that directory


I modified the script to use the new Python 2.7


current contents of the script:


#!/bin/bash

# what real Python executable to use
PYVER=2.7

PYTHON=/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER

# find the root of the virtualenv, it should be the parent of the dir this script is in
ENV=`$PYTHON -c "import os; print os.path.abspath(os.path.join(os.path.dirname(\"$0\"), '..'))"`

# now run Python with the virtualenv set as Python's HOME
export PYTHONHOME=$ENV
exec $PYTHON "$@"



I ran the script:

psy-blackbird:bin wieser$ ./cpac.bash
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>


I then imported CPAC

>>> import CPAC

then I tried to run CPAC.GUI.run(), and got an error:

>>> CPAC.GUI.run()
Fri Jan 23 15:16:34 psy-blackbird.ad.uwm.edu Python[2138] <Error>: kCGErrorFailure: Set a breakpoint @ CGErrorBreakpoint() to catch errors as they are logged.
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.


how can I fix this ?
Thanks
Jon



________________________________

**Comment by jpellman** [comment]
Hi Jon,

Try placing the script within the directory /home/\<your_username\>/anaconda/bin.  If that directory does not exist, search for a folder named 'anaconda' (which is where your Anaconda installation should reside).  Then run the script again, open up Anaconda, and let me know if "import CPAC" followed by "CPAC.GUI.run()" will work.

**Comment by jpellman** [comment]
Hi Jon,

Alternatively (if the above does not work for you) we have found that installing wxpython using Anaconda's "conda" utility does not present any issues.  To do this, open up a terminal and type "conda wxpython".

Best,
John Pellman

**Comment by jonwieser** [comment]
?the previous fix worked. thanks for your help!!

Jon

________________________________
