### ISSUE TITLE
VMHC 

### ISSUE THREAD

**Issue by msk1105** [FCP-INDI/C-PAC#420]
What are differences between" vmhc_fisher_zstd" and "vmhc_fisher_zstd_zstat_map"? The VMHC outputs have been created by the CAPC 3.8.

Maki

**Comment by sgiavasis** [comment]
Hey Maki,

The "vmhc_fisher_zstd" output is the VMHC map after the Fisher z-transform. More specifically, it is the result of this operation:

3dcalc -a <raw VMHC input.nii.gz> -expr "log((1+a)/(1-a))/2" -prefix <output.nii.gz>

On the other hand, "vmhc_fisher_zstd_zstat_map" is the Z-statistic map of the Fisher z-transformed output. This is the result of this operation:

3dcalc -a <VMHC Fisher z-transformed file.nii.gz> -expr "a*sqrt({num_vols}-3)" -prefix <output.nii.gz>

Hope this helps!

Steve

**Comment by msk1105** [comment]
Thanks, Steve.

Maki

On Tue, Jan 20, 2015 at 5:05 PM, sgiavasis <notifications@github.com> wrote:

> Hey Maki,
>
> The "vmhc_fisher_zstd" output is the VMHC map after the Fisher
> z-transform. More specifically, it is the result of this operation:
>
> 3dcalc -a -expr "log((1+a)/(1-a))/2" -prefix
>
> On the other hand, "vmhc_fisher_zstd_zstat_map" is the Z-statistic map of
> the Fisher z-transformed output. This is the result of this operation:
>
> 3dcalc -a -expr "a*sqrt({num_vols}-3)" -prefix
>
> Hope this helps!
>
> Steve
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FCP-INDI/C-PAC/issues/420#issuecomment-70743827>.
>



-- 
*Maki S. Koyama, PhD*
Research Scientist

Nathan Kline Institute for Psychiatric Research
140 Old Orangeburg Rd, Orangeburg, NY 10962

Child Mind Institute
445 Park Avenue, New York, NY 10022

Rutgers University Center for Molecular & Behavioral Neuroscience
197 University Avenue Newark, NJ 07102
http://babylab.rutgers.edu/Maki_Koyama_Postdoctoral_Fellow.html
