### ISSUE TITLE
Multiple ROI files as well as sub bricks

### ISSUE THREAD

**Issue by mherting** [FCP-INDI/C-PAC#421]
Hello CPAC team,

Once we upgraded to the newest version we noticed something a bit strange with our sca_roi_to_standard_smooth_fisher_zstd ROI files. Before the new release we had 6 ROI files so they each had one volume in them, each being the Z score value at each voxel that correlated with that given ROI, and included: z_score_ROI_number_1.nii.gz, z_score_ROI_number_2.nii.gz, etc.

Now, with the new version we still get z_score_ROI_number_1.nii.gz, z_score_ROI_number_2.nii.gz, etc., except now each of these nifti files includes 6 sub bricks (volumes) and each of the nifti files are identical to each other (each sub-volume in each of the 6 ROI files is identical). Given my 6 ROIs, I am assuming there is an error where it is collapsing each of the 6 ROIs now into one volume (which is fine), but why are there 6 ROI files? 

I presume this stems from the SCA options. We give it a text file with 6 ROIs, but in order to actually get a sca output we also have to select in our pipeline to turn on the ROIAverage option from the menu and then if we don't give it an ROI file (nifti) it fails with the NoneType Error.

Please advise!

Code:
seedSpecificationFile :  /nfs/PHACS/CPAC-new/site_1/default_seeds_num.txt
(6 ROIs listed as instructed. This leads to the creation of: /nfs/PHACS/CPAC-new/site_1/rois_2mm.nii.gz)

# Directory where CPAC should write NIfTI files containing new seeds.
seedOutputLocation :  /nfs/PHACS/CPAC-new/site_1

# It is possible to use the newly generated seeds when running a number of the analyses included in CPAC. Note that these analyses will be run using all new seeds.
# If you wish to use these new seeds to run Seed-based Correlation Analysis, select ROI Average Timeseries Extraction.
# If you do not wish to use new seeds in these analyses, select none.
useSeedInAnalysis :  ['roi_average']

# Extract the average time series of one or more ROIs/seeds. Must be enabled if you wish to run Seed-based Correlation Analysis.
runROITimeseries :  [1]
(We have to set to 1 or we don't get the SCA output)

# Full path to a text file containing a list ROI files.
# Each line in this file should be the path to a NIfTI file containing one or more ROIs.
# If you only wish to extract time series for newly defined spherical seed ROIs, set this field to None.
# Note that all ROI masks values are converted to integers within C-PAC.
roiSpecificationFile :  None

# Full path to a text file containing a list ROI files.
# Each line in this file should be the path to a NIfTI file containing one or more ROIs.
# If you only wish to extract time series for newly defined spherical seed ROIs, set this field to None.
# Note that all ROI masks values are converted to integers within C-PAC.
roiSpecificationFileForSCA :  /nfs/PHACS/CPAC-new/site_1/rois_2mm.nii.gz

(i think this is where our issue comes from. BUT when we set this to 'None' we were unable to run the pipeline as we got a NoneType Error)

# By default, extracted time series are written as both a text file and a 1D file. Additional output formats are as a .csv spreadsheet or a Numpy array.
roiTSOutputs :  [True, False]

**Comment by sgiavasis** [comment]
Hello mherting,

Thanks for the report! Yes, our SCA workflows need some clean-up, and we are taking care of that in this release. Some details are available in this issue as well:

https://github.com/FCP-INDI/C-PAC/issues/401

Nothing in the calculation of these outputs has changed, it is more related to how we have Nipype write the results out.

Thank you for your patience, and let me know if there is anything we can do to help you with getting your data in the format you prefer.

**Comment by sgiavasis** [comment]
This will be resolved in 0.3.9.
