### ISSUE TITLE
CPAC_runner unnecessarily consumes 100% of CPU in busy wait

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#424]
This while loop at line [504 in cpac_runner.py](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_runner.py#L504) implements a busy wait that consumes 100% of a processor during pipeline execution. This is an unnecessary waste of resources. This can be easily fixed by adding a 2 second sleep at [line 528](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_runner.py#L528) that is in the else block but outside of the for loop block.

**Comment by dclark87** [comment]
I made this change in the commit https://github.com/FCP-INDI/C-PAC/commit/62ee9903ac19ef29f510fa54608e709eb65f8c3a and this will be in the 0.3.9 release
