### ISSUE TITLE
Improve error message for scrubbing

### ISSUE THREAD

**Issue by Angel-Fernandez** [FCP-INDI/C-PAC#429]
Hi,

I'm using CPAC 0.3.8. The main problem is that with some images the workflow stops when is running the scrubbing and jumps to the next image without finalize the quality control.

This is my crash file:

File: crash-20150107-084313-cafetero-scrubbed_movement_parameters.c0.a0.pklz
Node: resting_preproc_02_A089.scrubbing_0.scrubbed_movement_parameters.c0.a0
Working directory: /home/cafetero/datos/rdoProyectoEHM/tmp/resting_preproc_02_A089/scrubbing_0/_scan_func_02_A089/_threshold_0.2/scrubbed_movement_parameters

Node inputs:

function_str = S'def get_mov_parameters(infile_a, infile_b):\n    """\n    Method to get the new movement parameters\n    file after removing the offending time frames \n    (i.e., those exceeding FD 0.5mm/0.2mm threshold)\n\n    Parameters\n    ----------\n    infile_a : string\n        path to file containing the valid time frames\n\n    infile_b : string\n        path to the file containing  motion parameters \n\n    Returns\n    -------\n    out_file : string\n        path to the file containing motion parameters\n        for the valid time frames \n\n    """\n    import os\n    import warnings\n\n    out_file = os.path.join(os.getcwd(), \'rest_mc_scrubbed.1D\')\n\n    f1= open(infile_a)\n    f2=open(infile_b)\n    l1=f1.readline()\n    l2=f2.readlines()\n    f1.close()\n    f2.close()\n\n    if l1:\n        l1=l1.rstrip(\',\').split(\',\')\n        warnings.warn("number of timepoints remaining after scrubbing -> %d"%len(l1))\n    else:\n        raise Exception("No time points remaining after scrubbing.")\n\n    f = open(out_file, \'a\')\n    for l in l1:\n        data=l2[int(l.strip())]\n        f.write(data)\n    f.close()\n    return out_file\n'
.
ignore_exception = False
infile_a = /home/cafetero/datos/rdoProyectoEHM/tmp/resting_preproc_02_A089/gen_motion_stats_0/_scan_func_02_A089/_threshold_0.2/include_frames/frames_in.1D
infile_b = /home/cafetero/datos/rdoProyectoEHM/tmp/resting_preproc_02_A089/fristons_parameter_model_0/_scan_func_02_A089/calc_friston/fristons_twenty_four.1D

Traceback:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 38, in get_mov_parameters
Exception: No time points remaining after scrubbing.
Interface Function failed to run.

Thanks in advance

**Comment by jpellman** [comment]
Hi Angel-Fernandez,

Was there a graph of head motion produced, and is there any pattern that can be found relating motion to the volumes that were skipped during scrubbing?

Best,
John Pellman

**Comment by ccraddock** [comment]
Hello,

I apologize that the error is not more clear, we are working to improve error messages in future versions.

The scrubbing process removes scans who have a framewise displacement (motion between two consecutive fMRI volumes) of more than a threshold that you specify in the configuration, as well as a user configurable number of timepoints before and after the offending timepoint. The error that you are getting indicates that there are no time points remaining in your data after this procedure. This is most likely due to the fact that your FD threshold is too high for the amount of motion in your data. If you are already using a liberal threshold, than the data has too much motion. 

Regards,
Cameron

**Comment by Angel-Fernandez** [comment]
Thanks. My FD threshold was set to 0.5 and my image has only a few volumes under it.

This is my FA plot:

![fd_plot](https://cloud.githubusercontent.com/assets/10339281/5758924/f831c87a-9cc9-11e4-9d48-ffba0dd570c1.png)

The upper values from FA plot are caused by the rotation movement. rotation in the rotation head plot are really in degrees? I've a rotation about 70º degrees.

![rotation](https://cloud.githubusercontent.com/assets/10339281/5758918/e20bc370-9cc9-11e4-9806-bb7fed6b6d3d.png)

**Comment by jpellman** [comment]
Hi,

While a few volumes are below the FD threshold, it appears that the volumes immediately before and after these scans are above the threshold, which would cause the below threshold volumes to be censored as well.  Using a threshold of around 1.5 would allow more volumes to be kept, but would be too liberal.  This subject has a substantial amount of motion, so scrubbing will not work in this instance. 

Best,
John Pellman

**Comment by Angel-Fernandez** [comment]
Ok, thanks a lot.
