### ISSUE TITLE
BOLD signal data location and DVARS units 

### ISSUE THREAD

**Issue by Angel-Fernandez** [FCP-INDI/C-PAC#433]
Hi @ranjit, @sgiavasis, @ssikka, @ccraddock 

I'm Angel again. I'm looking for BOLD signal data stored by CPAC. Please, where can I find it?

Also I've another question, the DVARS values into workingDirectory/resting_preproc_X/gen_motion_stats_0/_scan_func_X_fMRI/cal_DVARS/DVARS.npy are a percentaje? (X is the subject id).

Thanks and best regards

**Comment by jpellman** [comment]
Hi Angel,
A preprocessed BOLD timeseries can be found under a directory of the form \<session\>/preprocessed/\_scan\_rest\_\<number\>\_rest in 4D NifTI format.  An average functional image can be found under a directory of the form  \<session\>/mean\_functional/\_scan\_rest\_\<number\>\_rest.  Let me know if that helps in finding the files that you need.

The DVARS file is in Numpy format, which is binary data.  It can only be read via the numpy.load method from numpy, so first make sure that it is being read that way.  I am uncertain how that file is scaled once it is open, and will need to research that more thoroughly.

Best,
John Pellman

**Comment by Angel-Fernandez** [comment]
I've loaded the matrix that is located into DVARS.py. At the beginning I thought that it was in percent units but later in one image I saw a dvars is over 100%.

On the other hand, about the question refered to the BOLD signal. I want to plot the BOLD signal in order to see the effect of motion over it. Do you have data about the BOLD signal across the volumes?

**Comment by jpellman** [comment]
As a tentative answer, DVARS is not typically expressed as a percentage, but is rather an expression of the rate of change for the BOLD signal across all voxels in the brain between volumes in a time series.  There is a standardized version of DVARS (since DVARS as originally conceived would vary between subjects and groups) proposed by Nichols.  I am uncertain whether C-PAC uses the standardized or unstandardized version and will check on that tomorrow.  Regardless, values greater than 100 should not be abnormal.

**Comment by jpellman** [comment]
Hello again Angel,

C-PAC uses the method for calculating DVARS originally used in Smyser et al (2010) and described by Power et al (2011), which is unstandardized.  Again, this means that values over 100 are to be expected.

The BOLD signal values should be contained within the preprocessed NifTI file.  If you want to have a plot of these for specific voxels, I would suggest opening the NifTI in a visualization tool such as AFNI and generating a plot that way.

Best,
John Pellman
