### ISSUE TITLE
Multiple output htmls by subject

### ISSUE THREAD

**Issue by Angel-Fernandez** [FCP-INDI/C-PAC#438]
Hi @ranjit, @sgiavasis, @ssikka, @ccraddock , @jpellman 

When I started to use cpac I only ran the preprocess feature and one html was obtained as result. Now I'm trying to begin with the postprocess and four new html are created two with the information of preprocess qc and a part of the preprocess the others contains a list like group list page.

The files obtained for one subject are:

in the pipline outpur directory -->

paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1____hp_0.01_lp_0.1_.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_fwhm_8.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9____.html

in the subject/qc_files_here/ -->

paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1.txt
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1____hp_0.01_lp_0.1__0.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1____hp_0.01_lp_0.1__1.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1____hp_0.01_lp_0.1_.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1____hp_0.01_lp_0.1_.txt
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_fwhm_8_0.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_fwhm_8_1.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_fwhm_8.html
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_fwhm_8.txt
paths_file_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_.txt
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_____0.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_____1.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1_0.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1_1.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1.txt
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1__0.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1__1.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_.html
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_.txt
qc_scan_func_00_EP_0033_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9____.html

I'm doing something wrong?

Thanks and best regards

**Comment by jpellman** [comment]
Hi Angel,

Can you open up your pipeline in the C-PAC GUI and go to "Output Settings" under "Environment Setup"?  Once there can you check to see if "Create Symbolic Links" is set to "On"?  If it is, that might explain why you are seeing duplicate files.  With this option enabled, C-PAC will make shortcuts of files in the working directory and place them within a better-organized directory.

Best,
John Pellman

**Comment by Angel-Fernandez** [comment]
Thanks John, now only I have these two files:

qc_scan_func_00_EP_0001_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9_bandpass_freqs_0.01.0.1___fwhm_8_hp_0.01_lp_0.1.html

![untitled2](https://cloud.githubusercontent.com/assets/10339281/6050468/19d7811c-acc0-11e4-8dc5-11bd05dc935c.png)


qc_scan_func_00_EP_0001_fMRI_CSF_0.9_GM_0.6_SCRUB_2_WM_0.9__hp_0.01_lp_0.1_.html

![untitled](https://cloud.githubusercontent.com/assets/10339281/6050428/b4d7003a-acbf-11e4-8fd3-d21faeb07ec0.png)

Please can you tell me why we have these two html? This is normal?

Thanks a lot

**Comment by jpellman** [comment]
Hi Angel,

I notice that the first of these two HTML files looks at images with smoothing applied (due to the presence of "fwhm_8"), while the other does not.  Since both smoothed and unsmoothed images are saved by C-PAC, the presence of two qc outputs would not be abnormal.

It's also worth noting that, in addition to creating file shortcuts, C-PAC also generates QC pages for multiple analysis strategies.  Therefore, if you are using many strategies, and each strategy has multiple qc pages, you can ultimately expect to have a large number of qc pages normally.

**Comment by Angel-Fernandez** [comment]
Ok thanks.
