### ISSUE TITLE
Concatenate multiple runs prior to sca 

### ISSUE THREAD

**Issue by mherting** [FCP-INDI/C-PAC#440]
Hi all, 

This may not be an "issue" BUT it seems when I have two separate resting state runs from 1 session, that each run is processed entirely separate so that the SCA analyses run on each 5 minute run, rather than 1 long 10 minute run. Is this a problem with how I structured my data?

Structure Example:
Site_1->Subject->func (rest_1.nii.gz and rest_2.nii.gz)

processing them all the way through as _scan_func_rest_1

Preferably (with other scripting) these are added together after preprocessing but before analyzing. Is this not an option? If not, suggestions on how to go about having it preprocess and then concatenate prior to sca???

Thanks! 

Megan

PS. Is there a better place to post for user help rather than here which seems like it is just for code bugs/errors? It would be useful to have a user forum!

**Comment by jpellman** [comment]
Hi Megan,

This is presently not an option within C-PAC.  If you would like to concatenate together your runs after preprocessing, I would suggest navigating to *\<directory_containing_analysis\>*/output/*\<pipeline_name\>*/*\<session_name\>*/preprocessed on your workstation, copying the two preprocessed runs to another folder, and then running AFNI's <a href=http://afni.nimh.nih.gov/pub/dist/doc/program_help/3dTcat.html>3dTcat</a> on them followed by <a href=http://afni.nimh.nih.gov/pub/dist/doc/program_help/3dAFNItoNIFTI.html>3dAFNItoNIFTI</a> on the resulting file.  You could then create a new subject list using the concatenated NifTI files, and a new pipeline with all of the preprocessing options (except smoothing) set to off in the CPAC GUI.  Note that C-PAC does not perform smoothing until after SCA is run, so make sure that the FWHM value in the "Spatial Smoothing Options" pane is still set in the new pipeline.

Also, there is, in fact, a dedicated C-PAC user forum!  It is implemented as a Google group that can be found here: https://groups.google.com/forum/#!forum/cpax_forum.  Simply request to be added and I will give you access.

Best,
John Pellman
