### ISSUE TITLE
run_sge_jobs has a misleading exception message.

### ISSUE THREAD

**Issue by alexsavio** [FCP-INDI/C-PAC#442]
Hi,
Still trying to excute C-PAC. In general, you haven't applied the best Exception handling politics in the project.

For example, the comment here: https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_runner.py#L234 is totally misleading. The fact that qsub is installed or not is not the only problem that may raise this Exception.

**Comment by jpellman** [comment]
Hi Alex,

We're well-aware that the Exception handling in many of our functions is not ideal.  This is why we're going to re-factor our code.  This is information is going to be really helpful for the re-factor.
