### ISSUE TITLE
C-PAC's workflow construction will fail if given an incorrect string for the regOption

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#447]
If you write 'FNIRT' instead of 'FSL' in the config file for the 'regOption' field, the construction of the segmentation workflow will fail.  Specifically, there is an issue with the 'create_seg_preproc' function in seg_preproc.py (probably due to an issue with the 'use_ants' boolean).  It looks like C-PAC doesn't know how to deal with incorrect input to that field.  Here is the error:

> ERROR: Invalid Connection: Segmentation Preprocessing: 0, resource_pool: {'anatomical_reorient': (resting_preproc_2014113_session_1.anat_preproc_0, 'outputspec.reorient'), 'anatomical_brain': (resting_preproc_2014113_session_1.anat_preproc_0, 'outputspec.brain')}
> 
> Error name: cpac_pipeline_0004
> 
> This is a pipeline creation error - the workflows have not started yet.
> 
> Process Process-1:
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>    self.run()
>  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>    self._target(_self._args, *_self._kwargs)
>  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_pipeline.py", line 640, in prep_workflow
>    seg_preproc, 'inputspec.brain')
> UnboundLocalError: local variable 'seg_preproc' referenced before assignment

**Comment by adonayn** [comment]
Hi, 

I am getting this error and  in the regOption  I wrote 'FSL', even with the other options I get the same error. I will appreciate if you can help me out with this error.
The error is: 
ERROR: Invalid Connection: Segmentation Preprocessing: 0, resource_pool: {'anatomical_reorient': (resting_preproc_0051462_session_1.anat_preproc_0, 'outputspec.reorient'), 'anatomical_brain': (resting_preproc_0051462_session_1.anat_preproc_0, 'outputspec.brain')}

Error name: cpac_pipeline_0004

This is a pipeline creation error - the workflows have not started yet.


Process Process-7:
Traceback (most recent call last):
  File "/Users/adonay/anaconda/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/adonay/anaconda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adonay/anaconda/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 934, in prep_workflow
    seg_preproc, 'inputspec.brain')
UnboundLocalError: local variable 'seg_preproc' referenced before assignment
    seg_preproc, 'inputspec.brain')
UnboundLocalError: local variable 'seg_preproc' referenced before assignment
found dead job  <Process(Process-4, stopped[1])>
found dead job  <Process(Process-7, stopped[1])>
[pipeline_config_CPAC_all.yml.zip](https://github.com/FCP-INDI/C-PAC/files/446142/pipeline_config_CPAC_all.yml.zip)

I have attached my YAML pipeline file.

Thanks,
Adonay

**Comment by jpellman** [comment]
What happens if you change _runRegistrationPreprocessing :  [1, 0]_ to just _runRegistrationPreprocessing :  [1]_?  Does the error persist?

**Comment by adonayn** [comment]
Hi,

It worked! Also If I turn off the anatomical registration the error
reoccurs, I guess it needs anatomical to mni registration.

Thanks for your help,
Adonay

**Comment by sgiavasis** [comment]
The pipeline construction part has changed enough in v1.8 that this can be considered closed.
