### ISSUE TITLE
func_preproc.py not actually deobliquing data

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#450]
For functional preprocessing, we use 3drefit to perform deobliquing.  However, this does not actually apply any transformation to the data- 3drefit only modifies the header to say that the data is deobliqued.  I'm not entirely sure if this is intended or not, but (other than the headers) the deobliqued NifTI file is identical to the truncated  NifTI file.  If it isn't intentional, we should switch to using AFNI's 3dWarp for deobliquing.

**Comment by ccraddock** [comment]
It is intentional. We remove the transform from the header without reslicing the data.
