### ISSUE TITLE
Subject List Setup: No Parameter values for the $site site is defined in the scan parameters csv file

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#451]
If the scan parameters csv used by a study has an empty line, then C-PAC will throw this error (from line 259 of extract_data.py).  We could have the subject list setup ignore empty newlines when the csv is read in, and that would prevent this error from being thrown and/or I could add this to the 0.3.9 documentation.

**Comment by sgiavasis** [comment]
No longer relevant.
