### ISSUE TITLE
collect_linear_transforms in create_nuisance of nuisance.py input mismatch

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#454]
Three inputs are being connected to collect_linear_transforms in lines 485-487 of nuisance/nuisance.py (0.3.9 branch), but collect_linear_transforms is only initialized to accept two inputs (line 477).  Either one of the inputs will need to be removed or collect_linear_transforms will need to be modified to accept 3 inputs.

**Comment by sgiavasis** [comment]
Nice find! Did you notice this through some behavior/output, or were you just going through the code?

**Comment by jpellman** [comment]
This came to light because of the "ANTS module issue" post on the forum; I
was able to track down the issue to this module, but I wanted to determine
whether or not it was due to an unnecessary extra input argument or a need
to update the Merge node before suggesting a solution.

2015-04-02 11:20 GMT-04:00 sgiavasis <notifications@github.com>:

**Comment by sgiavasis** [comment]
Sounds good. I fixed it locally and I'm doing a quick run right now to see what impact this has on the outputs, and if it will explain any change in correlations.
