### ISSUE TITLE
Crash with FSL registration option

### ISSUE THREAD

**Issue by alexsavio** [FCP-INDI/C-PAC#457]
Hi,

C-PAC v0.3.9.1 runs smoothly with ANTs, but with FSL the log shows the following. The only change I made was regOption from ['ANTS'] to ['FSL']

ERROR: Invalid Connection: Anatomical Registration (FSL): 0, resource_pool: {'anatomical_reorient': (resting_preproc_0040000.anat_preproc_0, 'outputspec.reorient'), 'anatomical_brain': (resting_preproc_0040000.anat_preproc_0, 'outputspec.brain')}

Error name: cpac_pipeline_0002

This is a pipeline creation error - the workflows have not started yet.

**Comment by jpellman** [comment]
Hi Alex,
Would you be able to send a copy of your pipeline configuration file to john.pellman@childmind.org?  I'd like to check to see if any other options are enabled that could be interacting with regOption.
--John

**Comment by alexsavio** [comment]
Hi John,

Thanks for your reply.

It is on Github: https://github.com/alexsavio/cobre/blob/master/cpac_conf/corsair/pipeline_config_cobre_wroclaw_fsl.yml

Cheers,
Alex

**Comment by jpellman** [comment]
Hi Alex,
All of the options that are specified look good.  However, I noticed that you do not have a FNIRT reference mask ('ref_mask') option specified.  This is a new option that C-PAC 0.3.9 uses when performing anatomical registration, and without it pipelines will not run correctly.  C-PAC's default for this option should work in most cases.  You can use the default by adding the following line to your YAML file:

> ref_mask : /usr/share/fsl/5.0/data/standard/MNI152_T1_${resolution_for_anat}_brain_mask_dil.nii.gz

If your copy of FSL is located in a place other than '/usr/share/fsl/5.0', then you can replace that path with '$FSLDIR'.

Best,
John Pellman

**Comment by jpellman** [comment]
Hi Alex,

I'm going to close this for now.  If the solution above didn't resolve your issue, feel free to re-open this.

--John

**Comment by alexsavio** [comment]
Hi John,

You nailed it, I've just tried it Thank you very much!

Cheers,
Alex
