### ISSUE TITLE
Redundant output for scrubbing on/off option

### ISSUE THREAD

**Issue by DaveOC90** [FCP-INDI/C-PAC#460]
Hi CPAC Team,

If you pick the on/off option for scrubbing, the output forks at the pipeline level. However in the scrubbed pipeline the functional data and all derivatives are output scrubbed and unscrubbed. So you basically double up on the unscrubbed output data.

Dave

**Comment by danlurie** [comment]
We're seeing this issue on our install of 0.3.9 here too.

I vaguely remember this being related to the way Nipype handles things depending on how workflows/pipelines are constructed, such that some options cause forks within pipelines and others create entirely new pipelines.

In any case, +1 to fixing this in a future release.

**Comment by anibalsolon** [comment]
Reworked by the nuisance regression overhaul! :rocket:
