### ISSUE TITLE
MNI152_T1_3mm is in talairach space?

### ISSUE THREAD

**Issue by petergoodin** [FCP-INDI/C-PAC#461]
I've downloaded the cpac imaging resources and opening them in FSLview suggests they're in talairach space not MNI.

**Comment by jpellman** [comment]
Hi Orcasha,

The C-PAC MNI templates were created from FSL's MNI templates using AFNI's 3dresample utility.  When 3dresample finished creating the new templates, it mislabelled the 'Template Space' field of the NifTI header as 'TLRC', but did not change the space (only the resolution).  You can check to see that the C-PAC templates align with the original FSL MNI templates by setting one of the original FSL templates as an underlay in AFNI and setting one of the C-PAC templates as an overlay.  If you are curious about the original command that produced the C-PAC templates, you can use AFNI's 3dinfo utility to get a history of all the commands that have been run to create the templates.

--John
