### ISSUE TITLE
c.runAnatomicalPreprocessing will crash C-PAC if set to both 0 and 1

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#472]
The code linked to below implies that runAnatomicalPreprocessing can be set to both 0 and 1.  A user is unlikely to try this, but if it is done C-PAC will crash during the non-linear registration setup with either error '0002' or '0003'.  This is because there will be a strategy with an empty resource pool (i.e., a copy of the initial strategy).  We might want to remove this code block if there's no compelling reason for it to be kept.

https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L418-L426

**Comment by sgiavasis** [comment]
This has been resolved in a past release.
