### ISSUE TITLE
Sometimes output folders will have two folders named '_scan_<scan_name>' with one nested within the other

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#473]
Occasionally the output folder will have directories organized as follows, where a scan folder will have another folder with the same name nested within it:

<pipeline_name>/<session>/alff_img/_scan_<scan_name>/_scan_<scan_name>

Other times the format is conventional:

<pipeline_name>/<session>/alff_img/_scan_<scan_name>

I'm not sure why this is occurring- I've found that the duplicated directory occurs with a multi-subject run whereas the conventional format occurs when there's only a single subject.  It could trip up some scripts acting on the output directory though.

**Comment by sgiavasis** [comment]
Looks like this happens when running ANTS and FNIRT at the same time. Will investigate further.

**Comment by nx10** [comment]
Outdated
