### ISSUE TITLE
cpac_pipeline.py passes in unexpected string values to create_roi_mask_dataflow

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#475]
[Here](https://github.com/FCP-INDI/C-PAC/blob/1cdecd5dcf6bba31221abf1f77f0e83c5646a6ed/CPAC/pipeline/cpac_pipeline.py#L2558) and in other locations in cpac_pipeline.py, the value passed into create_roi_mask_dataflow for mask_type is 'ROI Average TSE', 'ROI Voxelwise TSE', or 'Network Centrality'.  However, [this code](https://github.com/FCP-INDI/C-PAC/blob/afbc30e28e4c282847920119e922953690835d36/CPAC/utils/datasource.py#L74-L79) expects either 'roi','voxel' or 'centrality'.  'tab' is therefore never defined and the error/exception [here](https://github.com/FCP-INDI/C-PAC/blob/afbc30e28e4c282847920119e922953690835d36/CPAC/utils/datasource.py#L93-L98) is never raised.

**Comment by shnizzedy** [comment]
Resolved in 14a6edf3d27b61111b507b138e94f747a0b6817b
