### ISSUE TITLE
functional_tab.py has duplicate code

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#476]
@erramuzpe  noticed that functional_tab.py has what looks to be a large duplicated block of code.  However, the duplicate code block is not identical to the original.  One version of this code block (the latter) defines the current C-PAC interface for functional preprocessing (as of 0.3.8 onwards), while the other does not.  Removing the latter code block produced a regression in the C-PAC GUI.

There are some changes in the former code block though that are semi-recent (Nov 11, 2014), and might or not might not belong in the latter code block.  We should check the two code blocks against each other and reconcile them so that there is only one block.

**Comment by sgiavasis** [comment]
This is gone.
