### ISSUE TITLE
Would it make sense to put the SGE jobs in a non-temp folder?

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#477]
The way that run_sge is set up [here](https://github.com/FCP-INDI/C-PAC/blob/1cdecd5dcf6bba31221abf1f77f0e83c5646a6ed/CPAC/pipeline/cpac_runner.py#L206), SGE batch submission jobs are stored in a temp directory inside of the directory that C-PAC is run from.  Would it make sense to put the generated batch scripts in another directory (possibly within the output or working directory)? Or if they're meant to be temp files, should they be deleted after the job has finished?

**Comment by nx10** [comment]
Outdated
