### ISSUE TITLE
C-PAC will freeze if subject directories made by another user in the working directory can't be overwritten

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#478]
Recently there was an issue where multiple users were writing in the same working directory.  One user had subjects in her subject list that had already been run by another user.  The subject directories created in the working directory by the other user had permissions set up such that the first user could not write to them.  This caused C-PAC to hang once it got to the subjects that had already been run.  We might want to add a way to check if subject directories already exist in the working directory and warn users if they're not writeable.

**Comment by sgiavasis** [comment]
Alright, checks will be in place for all four directories (working, output, crash, logs) in 1.0.2.
