### ISSUE TITLE
Blank drop-down menu items and text paths sometimes in GUI

### ISSUE THREAD

**Issue by pintohutch** [FCP-INDI/C-PAC#480]
Occasionally the options for a drop-down menu or filepaths in text boxes will disappear from view and will only re-appear when clicking on them; this is typically seen over a remote connection to a server running C-PAC (via X2Go or X11 for example)

**Comment by sgiavasis** [comment]
With the introduction of the new pipeline builder GUI, we will be phasing these issues out.

More info on the new GUI available here:
http://fcp-indi.github.io/docs/user/new_gui.html
