### ISSUE TITLE
GUI: Revise Time Series Extraction Pages

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#486]
- Allow PC1 to be run on ROIs.
- Checkbox grid which accepts multiple paths to ROI files, where the user can check which analyses to run for each ROI (i.e. Avg, PC1, Voxelwise, Spatial Regression).

**Comment by ccraddock** [comment]
![img_0914](https://cloud.githubusercontent.com/assets/1725272/10002652/6af4d62a-6076-11e5-9c3c-70be65dce3ba.JPG)

**Comment by sgiavasis** [comment]
This new GUI element will be in effect in the 0.4.0 release.
