### ISSUE TITLE
When you give the pipeline configuration builder a pipeline name that already exists, it doesn't go back to the builder

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#493]
When you enter a pipeline name that already exists in the 'Pipeline Name' field of 'Output Settings' it will warn you that the pipeline already exists and that you should choose a new name.  It then exits the pipeline configuration builder without keeping any of your currently entered settings in tact.

**Comment by sgiavasis** [comment]
With the introduction of the new pipeline builder GUI, we will be phasing these issues out.

More info on the new GUI available here:
http://fcp-indi.github.io/docs/user/new_gui.html
