### ISSUE TITLE
'Test Configuration' throws error when nuisance regression is turned off

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#495]
If you try to test a configuration in the CPAC Pipeline Configuration window where nuisance regression is off, you receive the follow error:

>  File "/usr/local/bin/miniconda/envs/cpac_040_test/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 617, in testConfig
>    if (1 in c.runNuisance) or (c.Corrections != None):
> UnboundLocalError: local variable 'c' referenced before assignment

**Comment by jpellman** [comment]
It seems that this also occurs when nuisance regression is on and corrections are defined- the following lines were also present in the error:

> [Errno 13] Permission denied: u'/home/johnpellmantestConfig.yml'
> Error Writing the pipeline configuration file /home/johnpellmantestConfig.yml

Where /home/johnpellman is the output directory.

The only time this error isn't produced is when nuisance signal regression is on and no regressors are selected.  Then, it gives a warning about the lack of regressors.

**Comment by shnizzedy** [comment]
Deprecated by #1262
