### ISSUE TITLE
Error w/ 'Run individual level analysis' button on main screen in 0.4.0 dev

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#498]
I select a subject list and pipeline and get the following error:

> Error reading config file - /home/johnpellman/Desktop/benchmark_package_2/settings/configs/pipeline_config_ANTS_example_a.yml
> Unhandled exception in thread started by <bound method ListBox.runAnalysis1 of <CPAC.GUI.interface.windows.main_window.ListBox; proxy of <Swig Object of type 'wxFrame *' at 0x410eda0> >>
> Traceback (most recent call last):
>  File "/usr/local/bin/miniconda/envs/cpac_040_test/lib/python2.7/site-packages/CPAC/GUI/interface/windows/main_window.py", line 234, in runAnalysis1
>    CPAC.pipeline.cpac_runner.run(pipeline, sublist, p)
>  File "/usr/local/bin/miniconda/envs/cpac_040_test/lib/python2.7/site-packages/CPAC/pipeline/cpac_runner.py", line 388, in run
>    raise Exception
> Exception

**Comment by sgiavasis** [comment]
With the introduction of the new pipeline builder GUI, we will be phasing these issues out.

More info on the new GUI available here:
http://fcp-indi.github.io/docs/user/new_gui.html
