### ISSUE TITLE
Deploying to PyPI

### ISSUE THREAD

**Issue by souravsingh** [FCP-INDI/C-PAC#504]
Deploying the package to PyPI would allow for easy installation steps.Then one will need to just do: `pip install cpac`

**Comment by jpellman** [comment]
I'm going to bump this issue as having a PyPI package would greatly simplify the ability to add C-PAC to platforms such as NeuroGentoo / gentoo-science (https://github.com/TheChymera/neurogentoo), as well as other repositories (such as Neurodebian).

**Comment by souravsingh** [comment]
@jpellman Should I start work on this?

**Comment by jpellman** [comment]
Hi @souravsingh ,

We're presently testing the next release of C-PAC (0.4.0) and will add this to our to do list for the release.  We'd prefer that the core developers do this as part of the release cycle, but would be glad for any pointers that you'd be willing to share with them.

**Comment by sgiavasis** [comment]
We will be publishing to PyPi for the 1.0.1 release. @souravsingh , please let me know if you would like a quick update on what's left.

**Comment by nimzodisaster** [comment]
Does this mean going forward I can install updates to C-PAC with pip?
Joshua

**Comment by sgiavasis** [comment]
Once we have the distribution package set up properly, yes. We will announce it when it is available.
