### ISSUE TITLE
Median Angle Correction throws TypeError exception when enabled.

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#511]
When median angle correction is enabled, the following exception gets thrown:

  File "<string>", line 51, in median_angle_correct
TypeError: cannot concatenate 'str' and 'tuple' objects
Interface Function failed to run.

This is because there is a print statement that tries to concatenate a string with the shape attribute of a Numpy array.

**Comment by sgiavasis** [comment]
This was resolved awhile back.
