### ISSUE TITLE
Remove cpac_setup.py and cpac_centrality.py from scripts directory?

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#513]
Two files in the 'scripts' directory haven't been updated in about 2 years and might not reflect C-PAC's current state.  We should remove them for the next release if they aren't being used or add them to the documentation otherwise.

**Comment by jpellman** [comment]
cpac_setup.py prepares subject lists from the command line, thus addressing the concerns from https://github.com/FCP-INDI/C-PAC/issues/518.  This is more of a naming issue (maybe change "cpac_setup.py" to something like "cpac_sublist.py")  / documentation issue.

**Comment by sgiavasis** [comment]
This has been moved into cpac_data_config_setup.py.
