### ISSUE TITLE
C-PAC should do input validation at the pipeline level rather than at the GUI level

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#516]
Currently C-PAC performs input validation at the GUI level but not in the pipeline itself.  This can be problematic when using an invalid pipeline config or subject list with the command line utility (cpac_run.py), since the run will start without warning the user of any issues and eventually just crash.  If input validation were done at a lower level, there could feasibly be a way to propagate issues back up to the GUI.

**Comment by sgiavasis** [comment]
Old GUI is gone, this can be closed.
