### ISSUE TITLE
CPAC GUI Problem

### ISSUE THREAD

**Issue by kdunlop** [FCP-INDI/C-PAC#519]
Hi,

I am able to import CPAC without errors, but both cpac_gui and CPAC.GUI.run() commands give the following error:
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.

I've tried to follow one of the previous messages (error message 430), but even changing the bash script to make the directories comes up with this error when I run the potential solution for wx:
ImportError: No module named site

Any help for a novice Python user like myself would be greatly appreciated!

**Comment by jpellman** [comment]
Hi kdunlop,

If you've tried the solution outlined in issue 430
<https://github.com/FCP-INDI/C-PAC/issues/430>, then there is clearly
something else afoot.  Which version of Mac OS X are you using?  We've had
issues installing C-PAC on some versions of OS X in the past.  If you
aren't trying to run C-PAC on Mac OS X, which OS are you using?

2016-03-23 13:21 GMT-04:00 kdunlop <notifications@github.com>:

**Comment by kdunlop** [comment]
I'm on Mac OS X 10.10.5. Oddly enough, I'm able to get to the GUI by typing "pythonw" and then the cpac gui command!

**Comment by jpellman** [comment]
Good to hear that it's working now!  Indeed, sometimes graphical applications will only work if executed with pythonw under OS X.  Let us know if you have any other questions!
