### ISSUE TITLE
Fix within GUI documentation for BBR

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#535]
The help icon that summarizes "Boundary Based Regisration Scheduler" provides a confusing description of when you would modify this option.

**Comment by sgiavasis** [comment]
I'm going to put in the description you have on the user guide, it seems sufficient:

"Use Boundary-Based Registration in the functional-to-anatomical registration process. This uses the anatomical segmentation outputs to improve the co-registration of functional images to the anatomical. However, this may not be the best option if your anatomical images feature low contrast, resulting in segmentation which may not be of high quality."
