### ISSUE TITLE
Error whith 3dSkullStrip

### ISSUE THREAD

**Issue by shenlongsanti** [FCP-INDI/C-PAC#541]
Dear experts,

I got an error while running my images that said I miss a library (lib.gsl.so.0), which is necessary for 3dSkullStrip, as you can see below: 

Standard error:
3dSkullStrip: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory (wich I took of the pipeline log of one of my subjects)

I am using Ubuntu 16.04

I went to the AFNI forum and they recommended to install gls-bin: 
sudo apt-get install gsl-bin. 

When I tried to install it, I got the following message: 

gsl-bin is already the newest version (2.1+dfsg-2).  

Despite that, the CPAC continued running without de skullstrip. Later on I got this essage: 
         ***********************************
160707-13:13:36,436 workflow ERROR:
     could not run node: resting_preproc_RFC.anat_preproc_0.anat_skullstrip
160707-13:13:36,437 workflow INFO:
     crashfile: /media/nf05/D4E47912E478F7D6/Shen/Crash_log/crash-20160707-125535-nf05-anat_skullstrip.pklz
160707-13:13:36,439 workflow INFO:
     ***********************************

I tried to attach the log images (pklz), but apparently they are not supported in this forum editor.

Do you know what I should do to overcome this issue?

Thanks in advance,
Santiago

**Comment by ccraddock** [comment]
Did you install AFNI using neurodebian? Would you try installing the binaries from AFNI instead?

**Comment by shenlongsanti** [comment]
Yes, I had installed using neurodebian.

**Comment by jpellman** [comment]
Hi Santiago,

The Neurodebian version of AFNI is very old (the update cycle for Debian packages is much slower than the update cycle for AFNI) and we have encountered issues with it in the past that make it not usable with C-PAC.  To ensure that AFNI works with our software, you should uninstall the Neurodebian binary and follow the installation instructions from the AFNI website [here](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu.html#install-steps-linux-ubuntu).

Best,
John Pellman

**Comment by shenlongsanti** [comment]
We just did it. We tryed to install AFNI manually but it still doesn't work. We are thinking that may be a problem with our version of ubuntu (16.04). What do you think?Thanks for your fast answers!

Get Outlook for iOS




On Mon, Jul 11, 2016 at 4:54 PM -0300, "John Pellman" <notifications@github.com> wrote:





Hi Santiago,

The Neurodebian version of AFNI is very old (the update cycle for Debian packages is much slower than the update cycle for AFNI) and we have encountered issues with it in the past that make it not usable with C-PAC.  To ensure that AFNI works with our software, you should uninstall the Neurodebian binary and follow the installation instructions from the AFNI website [here](https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_ubuntu.html#install-steps-linux-ubuntu).

Best,
John Pellman

---

**Comment by jpellman** [comment]
Hi Santiago,

Are you receiving the same error as before?  If so, you might want to make sure that you are following the extra steps under the subsection for _versions 15.10 and higher_ in the link I sent, since there is a step involving the library that AFNI was having difficulty linking in.

Best,
John

**Comment by shenlongsanti** [comment]
Hey, Jpellman

It really worked! Thank you very much for your advice. It was indeed necessary to follow the extra steps.

We tried to run just two images and apparently it worked. Nevertheless, we still got two error messages:
snr value:  5.24
mv /media/nf05/D4E47912E478F7D6/Shen/Results/pipeline_pipeline/Subject_1/qc_files_here/path/*.txt /media/nf05/D4E47912E478F7D6/Shen/Results/pipeline_pipeline/Subject_1/qc_files_here/
qc_path:  /media/nf05/D4E47912E478F7D6/Shen/Results/pipeline_pipeline/Subject_1/qc_files_here
file_:  qc_scan_Func_RFC_FUNC_wm1.motion1.csf1_CSF_0.96_GM_0.7_WM_0.96__hp_0.01_lp_0.1_.html
Error: some power params lost.
Error: some motion params lost.
qc_path:  /media/nf05/D4E47912E478F7D6/Shen/Results/pipeline_pipeline/Subject_1/qc_files_here
file_:  qc_scan_Func_RFC_FUNC_wm1.motion1.csf1_CSF_0.96_GM_0.7_WM_0.96__hp_0.01_lp_0.1_fwhm_6.html
Error: some power params lost.
Error: some motion params lost.
160712-21:05:41,98 workflow INFO:
	 End of subject workflow resting_preproc_Subject_1  

What do those errors mean? Do you think I should do anything?
If you prefer a can open a new thread about those errors.

Thank you,
Santiago

**Comment by jpellman** [comment]
Hi Santiago,

Did you turn scrubbing on?  In older versions of C-PAC prior to 0.3.9 there were some issues with this functionality, and I'm wondering if that's related to the error you're encountering now.  Would you be willing to send a copy of your pipeline configuration and any crash files to me at john.pellman@childmind.org?

Best,
John

**Comment by sgiavasis** [comment]
Closing this issue because it has been awhile. If there are any more issues or questions, please feel free to open a new one.

Best,
The C-PAC Team

**Comment by shnizzedy** [comment]
Reopening because this issue has resurfaced in the Singularity builds of 1.6.2.

Related: [cpax_forum › Issue with running singularity image](https://groups.google.com/forum/#!topic/cpax_forum/G_9UMgTWjfE)

Maybe related: https://github.com/FCP-INDI/C-PAC/issues/1277

**Comment by shnizzedy** [comment]
Currently in 1.6.2 Singularity container, `libgsl.so.0` seems to be the only library that isn't linking correctly for 3dSkullStrip:

```shell
~> ldd /opt/afni/3dSkullStrip

        linux-vdso.so.1 (0x00007ffcc7bef000)
        libGLU.so.1 => /usr/lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f31c4727000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f31c449b000)
        libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007f31c4232000)
        libXft.so.2 => /usr/lib/x86_64-linux-gnu/libXft.so.2 (0x00007f31c401d000)
        libXp.so.6 => /usr/local/lib/libXp.so.6 (0x00007f31c3e14000)
        libXpm.so.4 => /usr/lib/x86_64-linux-gnu/libXpm.so.4 (0x00007f31c3c02000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f31c39f0000)
        libXmu.so.6 => /usr/lib/x86_64-linux-gnu/libXmu.so.6 (0x00007f31c37d7000)
        libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f31c35cf000)
        libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f31c33b4000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f31c307c000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f31c2e57000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f31c2c3a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f31c289c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f31c2698000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f31c22a7000)
        libgsl.so.0 => not found
        libgslcblas.so.0 => /usr/lib/x86_64-linux-gnu/libgslcblas.so.0 (0x00007f31c2068000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f31c1e23000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f31c1a9a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f31c1882000)
        libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f31c1651000)
        libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f31c139b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f31c117c000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f31c0ec8000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f31c0cbe000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f31c0aba000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f31c08b3000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f31c069e000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f31c0476000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f31c4996000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f31c0244000)
        libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f31c0012000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f31bfe0a000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f31bfc04000)
```

**Comment by sgiavasis** [comment]
Do we know if the actual libgsl.so.0 does not exist inside the container, or if the link is just not being formed?

**Comment by shnizzedy** [comment]
`libgsl.so.0` is just supposed to be a file link to the current libgsl.so. It's linking correctly in Docker, but something about the way Singularity handles permissions isn't handling this one particular linkage. And without sudo privileges, the link can't be added after creating the image.

```shell
~> ls /usr/lib/x86_64-linux-gnu/libgsl*
/usr/lib/x86_64-linux-gnu/libgsl.a	    /usr/lib/x86_64-linux-gnu/libgslcblas.so
/usr/lib/x86_64-linux-gnu/libgsl.so	    /usr/lib/x86_64-linux-gnu/libgslcblas.so.0
/usr/lib/x86_64-linux-gnu/libgsl.so.23.0.0  /usr/lib/x86_64-linux-gnu/libgslcblas.so.0.0.0
/usr/lib/x86_64-linux-gnu/libgslcblas.a
```

```shell
~> ln $libs_path/libgsl.so.23.0.0 $libs_path/libgsl.so.0
ln: failed to create hard link '/usr/lib/x86_64-linux-gnu/libgsl.so.0' => '/usr/lib/x86_64-linux-gnu/libgsl.so.23.0.0': Operation not permitted
```

```shell
~> ln -s $libs_path/libgsl.so.23.0.0 $libs_path/libgsl.so.0
ln: failed to create symbolic link '/usr/lib/x86_64-linux-gnu/libgsl.so.0': Permission denied
```

I'm tinkering with [our Singularity recipe](https://github.com/FCP-INDI/C-PAC/blob/f6c307338bb79bd74927ecf87d8c13822b0f616d/Singularity#L10-L14) and [the linking section of the Dockerfile](https://github.com/FCP-INDI/C-PAC/blob/18fa210228b1c347f2d436b73f9247bdf5839de8/Dockerfile#L101-L114).

This particular issue has been a recurring thorn for fmriprep and OpenfMRI too:
https://github.com/poldracklab/mriqc/issues/567, https://github.com/poldracklab/mriqc/issues/648, https://github.com/poldracklab/mriqc/pull/733, https://github.com/hpcng/singularity/issues/795
