### ISSUE TITLE
Error while testing the C-PAC installation

### ISSUE THREAD

**Issue by phirity** [FCP-INDI/C-PAC#543]
I'm new to C-PAC and I've been trying to install C-PAC on my mac for a week.
After arduous installing of C-PAC, whenever I try to test the installation by typing import CPAC in python environment, many lines scroll down until I get to this same error message every time I try.

IOError: [Errno 2] No such file or directory: '/private/tmp/C-PAC/test/resources/settings/configs/data_config_test.yml'

When I checked the directory, there were no 'resources' folder in the 'test' folder. these are the lists of my 'test' folder currently.

README.txt  **init**.pyc    test_all.py unit
**init**.py templates   test_trivial.py

Why is there no 'resources' folder? Which stage did I omit? Please help.

Best, 
Kyung.

**Comment by jpellman** [comment]
Hi Kyung,

We haven't encountered this error before, but it is related to some automated tests that have been set up for C-PAC.  Just to clarify, does this occur just when you type "import CPAC" or have you been typing "CPAC.test()" as well to test your installation of C-PAC?  Also, which version of Python (Canopy, Anaconda) / Mac OS X are you using?

Best,
John

**Comment by phirity** [comment]
Hi John, 
Thanks for the reply. 
But things got a little more complicated. The error I mentioned above only happens when I reinstall C-PAC. And if I restart mac and try to test C-PAC by "import CPAC" in python environment, this happens.

>>> import CPAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/CPAC/__init__.py", line 21, in <module>
    import anat_preproc, \
  File "/usr/local/lib/python2.7/site-packages/CPAC/pipeline/__init__.py", line 3, in <module>
    from cpac_pipeline import run
  File "/usr/local/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 16, in <module>
    from   nipype.pipeline.utils import format_dot
ImportError: No module named utils



FYI, I did install python-utils 2.0.0 but the error says it's about module it is saying and I'm not sure which "utils" it wants. 
My version of Python, conda, Mac OS X are as follows(with the error I just mentioned). And I also tried "CPAC.test()" although I'm not quiet sure if it's done properly.

OS X El Capitan 10.11.6 


Last login: Fri Jul 22 09:50:41 on ttys000
KYUNGui-MacBook:~ CK$ conda --version
conda 4.1.8
KYUNGui-MacBook:~ CK$ python
Python 2.7.12 (default, Jul  4 2016, 12:47:11) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import CPAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/CPAC/__init__.py", line 21, in <module>
    import anat_preproc, \
  File "/usr/local/lib/python2.7/site-packages/CPAC/pipeline/__init__.py", line 3, in <module>
    from cpac_pipeline import run
  File "/usr/local/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 16, in <module>
    from   nipype.pipeline.utils import format_dot
ImportError: No module named utils
>>> CPAC.test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'CPAC' is not defined
>>> 

<img width="1111" alt="2016-07-22_09-53-34" src="https://cloud.githubusercontent.com/assets/20572696/17043672/e0aa914e-4ff3-11e6-82e6-f86f93e4827d.png">

**Comment by jpellman** [comment]
Hi Kyung,

Could you try uninstalling nipype and using an earlier version?  The nipype developers recently released a newer version that breaks compatibility with C-PAC 0.3.9.2.  You should be able to get the older version using the following commands:

pip uninstall nipype
pip install nipype==0.11

You shouldn't need to run CPAC.test() to make sure that your installation of CPAC is fine- that is used by our developers to test C-PAC's stability after code changes (as are the items in the "test" folder).  To verify that C-PAC itself is installed correctly, you should only need to run "import CPAC".

**Comment by phirity** [comment]
Finally it worked!
Nothing after "import CPAC". I think I passed this stage. 
Thank you so much. 

Best,
Kyung.
