### ISSUE TITLE
C-PAC logs generate large numbers of files in /tmp

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#545]
The function [create_log_node](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L314) is invoked for each step in the C-PAC pipeline.  This depends upon [create_log](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/utils/utils.py#L1759), which generates a workflow object that wraps the function [write_to_log](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/utils/utils.py#L1664).  Since this workflow object does not set _base_dir_, it stores provenance data for the wrapper nodes in /tmp (see [here for more info](https://neurostars.org/p/165/)).  There should be a way for users to specify that they want to delete these files (or they should be deleted automatically), and maybe possibly a location in the log directory where these temporary files can be kept.

**Comment by anibalsolon** [comment]
I would argue to remove these create_log_nodes completely. This log information was moved to CPAC.utils.monitoring and plugged in the workflow node execution per se.

@sgiavasis permission to wipe out create_log_node :rocket:

**Comment by sgiavasis** [comment]
@anibalsolon **granted**
