### ISSUE TITLE
cpac_gui start fails missing Framework build of python

### ISSUE THREAD

**Issue by adonayn** [FCP-INDI/C-PAC#548]
HI

I have installed CPAC but when running the cpac_gui command it gives me this error:

This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.

How can I fix it?

Thanks
Adonay

**Comment by jpellman** [comment]
Hi Adonay,

The 2nd item [here](http://fcp-indi.github.io/docs/user/help.html#common-issues-and-solutions) should point you to the solution to this issue.

Best,
John

**Comment by adonayn** [comment]
Thanks John,

I saw the link, but I can't find a way to create a virtual environment. When running the command: 
$ virtualenv --python=python2.7 --distribute --no-site-packages --unzip-setuptools  test1

I get a problem with setuptools that I can't fix it:

 Running virtualenv with interpreter /Users/adonay/anaconda/bin/python2.7
New python executable in /Users/adonay/test1/bin/python2.7
Also creating executable in /Users/adonay/test1/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Users/adonay/test1/bin/python2.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/adonay/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/adonay/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/adonay/test1/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/adonay/test1/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Users/adonay/test1/lib/python2.7/lib-dynload/_io.so
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/adonay/anaconda/lib/python2.7/site-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/Users/adonay/anaconda/lib/python2.7/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Users/adonay/anaconda/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/Users/adonay/anaconda/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/adonay/anaconda/lib/python2.7/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/adonay/test1/bin/python2.7 - setuptools pip wheel failed with error code 1

If you have any solutions please let me know

Thanks
Adonay

**Comment by jpellman** [comment]
Hi Adonay,

Anaconda is itself a Python virtual environment, so the steps regarding setting up a Python virtual environment can be skipped.  You should pick up after the line that says:

> At this point it may appear that everything is working and that we're finished. However as mentioned above this environment is not recognized as a framework or application bundle by the system and so wxPython applications can not initialize.

Let me know if you require any more assistance fixing the framework build issue.

**Comment by adonayn** [comment]
Hi John,

I tried to follow the instructions but the path: 
PYTHON=/Library/Frameworks/Python.framework/Versions/$PYVER/bin/python$PYVER
its is not a Mac path, there is no /Library/ path, there is though /usr/Frameworks/ but not Python.framework 
Do you know what the PYTHON path should be? 
I also tried to create an anaconda environment, but still I can't run cpac_gui.

Also, if I call python and do import wx there is no screen warning, which means that it is imported successfully. 

Any thoughts will be appreciated.
Thanks
Adonay

**Comment by jpellman** [comment]
Hi Adonay,

The directory that houses the system-level Python, which is what the script in that tutorial uses, might have changed in newer versions of Mac OS X.  A better approach might be to do what MartinGregory did in the comments section for the tutorial, and add the following line to /Users/adonay/anaconda/bin/activate:

> export PYTHONHOME=`dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"`

**Comment by jpellman** [comment]
You also might want to try the solution posted [here](https://github.com/conda/conda/issues/607#issuecomment-220575441) or using pythonw from the terminal:

> pythonw
> import CPAC.GUI
> CPAC.GUI.run()

**Comment by adonayn** [comment]
Hi John,

I tried to add the line in the active file but did not work, the pythonw option did work!

Thanks for your assistance,
Adonay
