### ISSUE TITLE
Mixing s3 and local paths causes local files to be deleted when testing configuration

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#551]
This might be an unlikely scenario, but I noticed that when you run 'Test Configuration' in the pipeline builder using a subject list that mixes S3 and local paths (i.e., local paths to anatomical scans and S3 paths for functional scans) C-PAC deletes the local files after the config is done being tested.

**Comment by sgiavasis** [comment]
Like, actually literally deleting scans that are on the hard drive? This sounds potentially horrible despite its unlikelihood. Bumping this up to current sprint. Will need to confirm it's happening and see why.

**Comment by jpellman** [comment]
iirc, it was deleting files.  I think what was happening is related to the code for managing inputs once they're grabbed from S3.  I haven't looked at the code, but I assume that what happens is that the images from S3 are pulled to the local volume and then deleted after the pipeline execution is complete.  When mixing S3 paths and local paths, C-PAC might just assume that all paths are S3 and use the S3 logic rather than the local path logic.

**Comment by sgiavasis** [comment]
@jpellman , when you get a chance, can you see if you can still reproduce this with the latest commit on 1.0.1_development?

**Comment by jpellman** [comment]
Here's what I get using the attached text file 'anat_in_s3.txt' with 'pipeline.txt':

```
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac101_112916/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 544, in testConfig
    sub_flg = self.test_sublist(sublist)
  File "/usr/local/bin/miniconda/envs/cpac101_112916/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 413, in test_sublist
    creds_path = sub['creds_path']
KeyError: 'creds_path'

```

And here's what I get when I use 'func_in_s3.txt':

```
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac101_112916/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 544, in testConfig
    sub_flg = self.test_sublist(sublist)
  File "/usr/local/bin/miniconda/envs/cpac101_112916/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 440, in test_sublist
    for func_file in func_files.values():
AttributeError: 'NoneType' object has no attribute 'values'

```

[pipeline.txt](https://github.com/FCP-INDI/C-PAC/files/620333/pipeline.txt)
[anat_in_s3.txt](https://github.com/FCP-INDI/C-PAC/files/620335/anat_in_s3.txt)
[func_in_s3.txt](https://github.com/FCP-INDI/C-PAC/files/620334/func_in_s3.txt)

**Comment by sgiavasis** [comment]
I added a few more needed checks- try again.

**Comment by jpellman** [comment]
The functional / indentation issue warning works for both configs.  When I indent 'rest_1_rest' I get this for anat_in_s3.txt:
```

Connecting to AWS: fcp-indi anonymously...
Subject list looks good!
corrections dictionary list: 
[{'global': 0, 'linear': 1, 'wm': 0, 'pc1': 0, 'motion': 1, 'quadratic': 0, 'gm': 0, 'compcor': 1, 'csf': 1}]
sub entries: 
['_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1', '_target_angle_deg_90', '_threshold_0.2']
strategy_entries:  [['_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1', '_target_angle_deg_90', '_threshold_0.2']] 


Number of threads for ANTS: %d is greater than the number of threads per subject: %d. Change this and try again.
an exception occured
```
![err112916_1820](https://cloud.githubusercontent.com/assets/5000591/20733373/086ec08c-b661-11e6-9d84-ae22ef42dc17.png)

And this for func_in_s3.txt:

```
Checking subject list: /tmp/anat_in_s3.yml...
Connecting to AWS: fcp-indi anonymously...
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac101_112916/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 573, in testConfig
    raise Exception
Exception

```

[func_in_s3.txt](https://github.com/FCP-INDI/C-PAC/files/620531/func_in_s3.txt)
[anat_in_s3.txt](https://github.com/FCP-INDI/C-PAC/files/620532/anat_in_s3.txt)

**Comment by sgiavasis** [comment]
Okay, you should be good- try one more time to verify.

**Comment by jpellman** [comment]
I'm getting this now for anat_in_s3:

```
Checking subject list: /tmp/anat_in_s3.yml...
Connecting to AWS: fcp-indi anonymously...
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac101_112916/lib/python2.7/site-packages/CPAC/GUI/interface/windows/config_window.py", line 571, in testConfig
    raise Exception
Exception
```

I got this for func_in_s3:

```
Checking subject list: /tmp/func_in_s3.yml...
Connecting to AWS: fcp-indi anonymously...
Subject list looks good!
corrections dictionary list: 
[{'global': 0, 'linear': 1, 'wm': 0, 'pc1': 0, 'motion': 1, 'quadratic': 0, 'gm': 0, 'compcor': 1, 'csf': 1}]
sub entries: 
['_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1', '_target_angle_deg_90', '_threshold_0.2']
strategy_entries:  [['_compcor_ncomponents_5_selector_pc10.linear1.wm0.global0.motion1.quadratic0.gm0.compcor1.csf1', '_target_angle_deg_90', '_threshold_0.2']] 


Number of threads for ANTS: 8 is greater than the number of threads per subject: 1. Change this and try again.
```

I changed the number of cores to 1, it starts testing and now I get this:

```
Whoops! - Filepaths provided do not exist:

templateSpecificationFile  -  /mnt/mask-thr50-3mm.nii.gz

Please double-check your pipeline configuration file.
```

The file doesn't exist so that's right, but the node that uses it (centrality) is set to off.  It might possibly be nice in the future to have it not check for a file's existence when the node that uses the file isn't being run.  If I remove '/mnt/mask-thr50-3mm.nii.gz' from the centrality settings the test runs fine.

**Comment by sgiavasis** [comment]
Really informative error message for anat_in_s3 there... going to root that out.

As for the final point, I'll make an issue for it but I'll put it in the next release.

**Comment by sgiavasis** [comment]
@jpellman 
Alright, try now.. that should do it. Thanks again!!

**Comment by jpellman** [comment]
It works!  The only minor issue I encountered was with the error dialog when running anat_in_s3 or func_in_s3 with a nonexistent mask file defined for centrality.  The error I got for this in the terminal was the same as last time:

```
Whoops! - Filepaths provided do not exist:

templateSpecificationFile  -  /mnt/mask-thr50-3mm.nii.gz

Please double-check your pipeline configuration file.
```

But the dialog window that popped up in the GUI was empty under _Issue Info_:

![pipeline_not_ready_120116](https://cloud.githubusercontent.com/assets/5000591/20813614/42122372-b7e4-11e6-96c8-6eb0579b83cc.png)

**Comment by sgiavasis** [comment]
Okay, great! I'll make that a separate issue.
