### ISSUE TITLE
Test configuration writes to log directory

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#552]
I'm not sure if this is necessarily an undesired behavior, but when you test a configuration file in the C-PAC GUI it populates the logs directory with a pipeline log for the test run.

**Comment by anibalsolon** [comment]
Have to check if the behavior persists, but does not look like a good behavior to have.

**Comment by anibalsolon** [comment]
CPAC GUI is deprecated and will be removed soon.
