### ISSUE TITLE
Intercface Function failed to run. 

### ISSUE THREAD

**Issue by abidali2619** [FCP-INDI/C-PAC#554]
while running cpac for my brain image processing data i am getting this error.
KeyError: 'pipeline_tad1_test_24082016\nInterface Function failed to run. '

 please help. thank you

[crash.txt](https://github.com/FCP-INDI/C-PAC/files/442303/crash.txt)

**Comment by jpellman** [comment]
Hi @abidali2619 ,

It looks like you might be working with Ankita.  I've written a response to her about this issue [here](https://groups.google.com/forum/#!topic/cpax_forum/tIKdGrgPvDs) that should help.  Let me know if you need anything else.
