### ISSUE TITLE
ReHo quick-pac

### ISSUE THREAD

**Issue by carolFrohlich** [FCP-INDI/C-PAC#557]
- [x] change reho py function to afni
- [x] write tests
- [ ] write workflow
   (depending of the derivative, the workflow needs to know if it has to write file to mni after or before  derivative.)
- [ ] write code to cp files from outputs to quick-pac dir.
- [ ] write code to cp reho outputs to bids format (see ABIDE_Initiative/Derivatives).

**Comment by sgiavasis** [comment]
Woohoo! QuickPACs here we come.
