### ISSUE TITLE
Unable to enter zeros directly into GUI interface for scrubbing

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#559]
One of our users was trying to set the remove preceding frames and remove successive frames parameters to 0 in the scrubbing GUI:

C-PAC version: 0.3.9.2

> In the GUI, when I try to set these parameter to zero, a warning sound is made and no entry is entered. I managed to 'trick' it by writing 10, then deleting the 1.
> 
> I am using Ubuntu Mate 16.04. The wx version is 3.0.2.0 gtk2 (classic)
> 
> When I delete the parameters from the gui it does not repopulate with zeros, it remains blank. Zeros could not be entered as the first digit in the fields.

I was unable to replicate this behavior using Ubuntu 14.04 and wx 3.0.0.0.  It might be wx-related.

**Comment by nimzodisaster** [comment]
I wanted to bring this up again. The issue continues to be true in 1.0.1.
If I enter zeros in the GUI for frames removed prior and successive and save the yaml, the default of 1 and 2 are saved. Then I have to manually change back to zero.

**Comment by sgiavasis** [comment]
With the introduction of the new pipeline builder GUI, we will be phasing these issues out.

More info on the new GUI available here:
http://fcp-indi.github.io/docs/user/new_gui.html
