### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by cccbauer** [FCP-INDI/C-PAC#565]
Hi guys,

I'm trying to install CPAC on Ubuntu 14.04. all went good until I import CPAC, here is the error.
I've tried to reinstal nipype 11.00, but does not work.

----> 1 import CPAC

/home/cccbauer/miniconda/lib/python2.7/site-packages/CPAC/**init**.py in <module>()
     19 test = _NoseTester().test
     20 
---> 21 import anat_preproc, \
     22        func_preproc, \
     23        reho, \

/home/cccbauer/miniconda/lib/python2.7/site-packages/CPAC/pipeline/**init**.py in <module>()
      1 from cpac_runner import run
      2 from cpac_group_runner import run
----> 3 from cpac_pipeline import run
      4 from cpac_group_analysis_pipeline import run
      5 from cpac_basc_pipeline import run

/home/cccbauer/miniconda/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py in <module>()
     20 import nipype.interfaces.io as nio
     21 from nipype.interfaces.afni import preprocess
---> 22 from nipype.pipeline.engine.utils import format_dot
     23 import nipype.interfaces.ants as ants
     24 import nipype.interfaces.c3 as c3

ImportError: No module named utils

thanks

clemens

**Comment by jpellman** [comment]
Hi Clemens,

We recently merged in changes for our upcoming release and are hoping to update the documentation with revised installation instructions soon.  One change is that you will need to use the latest version of nipype.  If you would like to take a look at what will be added to the main site, the HTML file [here](https://raw.githubusercontent.com/FCP-INDI/fcp-indi.github.com/dev040/docs/user/install.html)  contains the latest revision.

**Comment by cccbauer** [comment]
Hi John,

thanks for the HTML. I'm now re-installing everything according to it. will let you know how it goes

**Comment by jpellman** [comment]
Hi Clemens,

One thing that I should mention is that the new version of C-PAC uses
several centrality tools that were recently added to AFNI, and which are
not yet available when you download the pre-compiled code.  We're working
on independently hosting the new tools until the main AFNI binaries catch
up.  You can either try compiling the new code on your machine from source
or we can try to send you the binaries we intend to host when they're
available.

**Comment by sgiavasis** [comment]
Hi Clemens!

Let us know if this is still an issue. Thanks!

**Comment by nx10** [comment]
Stale, likely outdated.
