### ISSUE TITLE
CPAC was imported and can be used, but wxPython was not found

### ISSUE THREAD

**Issue by alexanderalang** [FCP-INDI/C-PAC#566]
Hello,

wxpython was installed using conda in the manner described in the documentation.

when I import CPAC I get this error

> > > import CPAC
> > > CPAC was imported and can be used, but wxPython was not found. In order to use the GUI, wxPython must be installed.
> > > Error: /home/vhasfclij3/miniconda/envs/cpac/lib/python2.7/site-packages/wx-3.0-gtk2/wx/../../../../libwx_gtk2u-3.0.so.0: undefined symbol: gtk_tree_selection_get_select_function

Alex

**Comment by jpellman** [comment]
Hi Alex,

This looks like an issue with Anaconda's wx package.  Which OS are you using?

--John

**Comment by sgiavasis** [comment]
Closing this issue because it has been awhile. If there are any more issues or questions, please feel free to open a new one.

Best,
The C-PAC Team
