### ISSUE TITLE
What is "motion_correct_to_standard_smooth" used for?

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#568]
The code here normalizes the motion-corrected data and then smoothes it:

https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L4169-L4181

I'm not sure why it does this though / what step uses it.  My intuition is that it's for group analysis.  Whatever the case, it might be good to document what it's used for for users.

**Comment by ccraddock** [comment]
it is minimally preprocessed data, this was requested by Vince Calhoun and Gael Varoquaux who prefer to do their nuisance correction on data in MNI space.

**Comment by sgiavasis** [comment]
Closing this- @jpellman when we move onto user docs updates for 1.0.1, we can check closed issues under the milestone to make the list of needed changes.
