### ISSUE TITLE
Group Setup Error in GUI

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#569]
Reporting a bug I received while setting up a model thru the GUI and tried to check the box to define my variable 'Typ0' to be categorical. I've attached my phenotype file for your reference. For now I will be using the text editor based setup.

> PyAssertionError                          Traceback (most recent call last)
> /usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/utils/custom_control.pyc in <lambda>(event)
>     743             self.cbValuesDict[self.idx+1] = [name, 'categorical', False]
>     744 
> --> 745             self.cb.Bind(wx.EVT_CHECKBOX, lambda event: self.onCheck_UpdateValue(event))
>     746 
>     747 
> 
> /usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/utils/custom_control.pyc in onCheck_UpdateValue(self, event)
>     855                         self.tempChoiceDict[('demean',idNum+1)] = wx.FindWindowById(idNum+1).GetValue()
>     856 
> --> 857                     wx.FindWindowById(idNum+1).Set3StateValue(2)  # set demean to N/A
>     858 
>     859                 else:
> 
> /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_controls.pyc in Set3StateValue(_args, *_kwargs)
>     413         state to wx.CHK_UNDETERMINED.
>     414         """
> --> 415         return _controls_.CheckBox_Set3StateValue(_args, *_kwargs)
>     416 
>     417     def Is3State(_args, *_kwargs):
> 
> PyAssertionError: C++ assertion "Assert failure" failed at /usr/include/wx-3.0/wx/checkbox.h(86) in Set3StateValue(): Setting a 2-state checkbox to undetermined state

My subject and phenotype files for group analysis are attached
[SubandPhenoFiles.tar.gz](https://github.com/FCP-INDI/C-PAC/files/525516/SubandPhenoFiles.tar.gz)

**Comment by sgiavasis** [comment]
Hi Nimzo,

This might be a wx-Python issue (the package we use to handle the GUI), but I'm not sure yet.

A few initial questions:
1. Which version of CPAC were you using for this?
2. Are you referring to the Typis0 column in your pheno?

**Comment by nimzodisaster** [comment]
1. This was from C-PAC 0.39.x. I have not yet tested in 1.0.0, and can get to it at the end of the week after a grant deadline.

2. Yes. I had categorical variables in my pheno file. When I tried to define them as categorical in the 0.3.9 group analysis builder,  errors were reported in the terminal.

**Comment by sgiavasis** [comment]
With the introduction of the new pipeline builder GUI, we will be phasing these issues out.

More info on the new GUI available here:
http://fcp-indi.github.io/docs/user/new_gui.html
