### ISSUE TITLE
quickpac

### ISSUE THREAD

**Issue by carolFrohlich** [FCP-INDI/C-PAC#572]
- [ ] write workflow
   (depending of the derivative, the workflow needs to know if it has to write file to mni after or before  derivative.)
- [ ] write code to cp files from outputs to quick-pac dir.
- [ ] write code to cp outputs to bids format (see ABIDE_Initiative/Derivatives).

**Comment by sgiavasis** [comment]
Created an Epic for this:
https://github.com/FCP-INDI/C-PAC/issues/588

Closing this issue.
