### ISSUE TITLE
ABIDE Preprocessed vmhc data

### ISSUE THREAD

**Issue by NataKozh** [FCP-INDI/C-PAC#574]
Hi,

I am trying to use the ABIDE Preprocessed data with estimated voxel-mirrored homotopic connectivity. Are these data sets in the MNI space or in the individual subject space? According to the C-PAC vmhc pipeline, the data seem to be normalized in the MNI space. However, some subjects seem not to be in the MNI - please compare, for example, subjects Caltech_0051478 and Leuven_1_0050704

could you please explain such discrepancy? 

Thanks!

**Comment by sgiavasis** [comment]
Hi NataKozh,

When saying the data does not seem to be in MNI space- are you referring to the outputs of a CPAC pipeline run for VMHC? Or the original data from ABIDE preprocessed?

**Comment by jpellman** [comment]
This thread is mirrored here:

https://groups.google.com/forum/#!searchin/pcp_forum/nata$20Kozh%7Csort:relevance/pcp_forum/p4UQiwMMXCM/9ywmyOE5AwAJ
