### ISSUE TITLE
generate subject list is broken!!

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#576]
I think that this is a merge error. But from CPAC.AWS import fetch_creds is deprected and should use indi_tools

https://github.com/FCP-INDI/C-PAC/blob/v1.0.0/CPAC/AWS/aws_utils.py#L408

**Comment by sgiavasis** [comment]
Replaced all instances in the code of "CPAC.AWS" with "indi_aws".

**Comment by jpellman** [comment]
Was able to generate a participant list of the ABIDE data in S3 with the attached data config, so at least that has been unaffected by the code replacement.

[data_config_ABIDE_S3_test.txt](https://github.com/FCP-INDI/C-PAC/files/582046/data_config_ABIDE_S3_test.txt)
