### ISSUE TITLE
BIDS option in subject list builder not robust to BIDS datasets without multiple sessions

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#578]
I tried running the subject list builder with the Rhyme judgement dataset from OpenfMRI [here](https://openfmri.org/dataset/ds000003/).  This dataset doesn't have multiple sessions, so anatomical and functional data are nested directly within the participant folder.  When I set the BIDS base directory to the root of the BIDS dataset I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 183, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 381, in save
    if self.run(path) >0:
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 250, in run
    CPAC.utils.build_sublist.build_sublist(config)
  File "/usr/local/bin/miniconda/envs/cpac100sublist/lib/python2.7/site-packages/CPAC/utils/build_sublist.py", line 861, in build_sublist
    sess = anat_sp[anat_sess_idx]
TypeError: list indices must be integers, not NoneType
```

Which implies that C-PAC is expecting a non-existent sessions directory nested below the participant directories.  Since session directories are optional in BIDS, the subject list builder should be more robust to this.

[data_config_template_bids_test.txt](https://github.com/FCP-INDI/C-PAC/files/576802/data_config_template_bids_test.txt)

**Comment by jpellman** [comment]
Just as a thought, we might want to consider integrating the subject list builder with the [Grabbids](https://github.com/INCF/grabbit) library in the future, which will allow you to query BIDS datasets and retrieve data that could be used in participant lists.  This would prevent a lot of unnecessary code duplication between C-PAC and that project.

**Comment by sgiavasis** [comment]
@jpellman We can put that idea in the project backlog as to not forget to discuss it in the following release.

@ccraddock Do we have a SOP for laying out participant list structure when there are no sessions in a BIDS format dataset? Perhaps a default session label? Or just omitting that nested level altogether.

**Comment by ccraddock** [comment]
Yes, use ses-1 as default. You can use my code here as an example: https://github.com/BIDS-Apps/CPAC?files=1

Run.py retrieves the file paths 
Bids utilize converts the list of paths to a cpac subject list.

**Comment by sgiavasis** [comment]
Alright, this should be set.

@jpellman , could you pull 1.0.1_development branch, re-install and see if you can still reproduce Issues 576-578? I am doing the same.

**Comment by jpellman** [comment]
Just tried this again with the same data config and a dialog popped up with the message:

`Error importing CPAC. Unable to run extract data tool.`

After clicking 'OK', the terminal printed the following:

```
Error importing CPAC
No module named fs.opener
```

It looks like this might be an undocumented dependency.

**Comment by jpellman** [comment]
After installing fs, the participant list is generated as expected.

**Comment by sgiavasis** [comment]
Filesystem abstraction layer? Wasn't aware of this library. Looks like Danny put it in back in Dec 2015?

**Comment by jpellman** [comment]
I remember him and Chris working with it during the hackathon in Mexico '15 so I think that's when the idea to use it came up.
