### ISSUE TITLE
Remove AWS submodule

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#580]
The AWS submodule is still in master, but isn't being used anymore since being superseded by INDI tools.

**Comment by sgiavasis** [comment]
Are you referring to AWS/aws_utils.py?

**Comment by jpellman** [comment]
Yeah.  It looks like it's only imported in the _cpac_pipeline.py_, which has been switched to use _indi_aws_.

**Comment by sgiavasis** [comment]
Okay, confirmed- I took this out in 1.0.1_development.
