### ISSUE TITLE
C-PAC 1.0.0 Subject List Generator TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#582]
[data_config_AllOct16.yaml.txt](https://github.com/FCP-INDI/C-PAC/files/584554/data_config_AllOct16.yaml.txt)

I installed C-PAC 1.0.0 last night and am trying to generate the subject list from a BIDS compatible data directory. 

However, I am getting the following error:

>###  saving /home/gose66/SUBJECTLISTS/ALL/z.yaml
> Gathering anatomical files...
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 2016-11-10 13:55:12,116 : Found 334 files!
> 161110-13:55:12,116 sublist_builder INFO:
> 	 Found 334 files!
> Gathering functional files...
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 2016-11-10 13:55:12,134 : Found 666 files!
> 161110-13:55:12,134 sublist_builder INFO:
> 	 Found 666 files!
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 2016-11-10 13:55:12,135 : Filtering anatomical files...
> 161110-13:55:12,135 sublist_builder INFO:
> 	 Filtering anatomical files...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Not filtering out any potential sites...
> 161110-13:55:12,136 sublist_builder INFO:
> 	 Not filtering out any potential sites...
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 2016-11-10 13:55:12,136 : Filtered down to 334 files
> 161110-13:55:12,136 sublist_builder INFO:
> 	 Filtered down to 334 files
> Filtered down to 334 anatomical files
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 2016-11-10 13:55:12,137 : Not filtering out any potential sites...
> 161110-13:55:12,137 sublist_builder INFO:
> 	 Not filtering out any potential sites...
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 2016-11-10 13:55:12,138 : Filtered down to 666 files
> 161110-13:55:12,138 sublist_builder INFO:
> 	 Filtered down to 666 files
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.pyc in <lambda>(event)
>     181 
>     182         run_ext = wx.Button(btnPanel, ID_RUN_EXT, "Generate Subject Lists", (280,10), wx.DefaultSize, 0 )
> --> 183         self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
>     184         hbox.Add( run_ext, 1, flag=wx.LEFT|wx.ALIGN_LEFT, border=10)
>     185 
> 
> /home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.pyc in save(self, event, flag)
>     379 
>     380                 if flag == 'run':
> --> 381                     if self.run(path) >0:
>     382                         self.Close()
>     383 
> 
> /home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.pyc in run(self, config)
>     248             else:
>     249                 # Build the subject list from the data config
> --> 250                 CPAC.utils.build_sublist.build_sublist(config)
>     251 
>     252                 # Extract arguments for supplementary files
> 
> /home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/build_sublist.pyc in build_sublist(data_config_yml)
>     879             site = ''
>     880             scan_params = bids_metadata.get_metadata_for_nifti(bids_base_dir,
> --> 881                                                                func)
>     882         else:
>     883             site = func_sp[func_site_idx]
> 
> /homegose66/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/bids_metadata.pyc in get_metadata_for_nifti(bids_root, rel_path)
>      45     potentialJSONs = [topLevelJSON]
>      46 
> ---> 47     subjectLevelJSON = "/" + sub + "/" + "_".join(subjectLevelComponentList)
>      48     potentialJSONs.append(subjectLevelJSON)
>      49 
> 
> TypeError: cannot concatenate 'str' and 'NoneType' objects
> 
> (ipython:3326): Gtk-WARNING **: Unable to find default local directory monitor type
> 
> 
> 

I am not sure if this is the same error reported here: https://github.com/FCP-INDI/C-PAC/issues/576
Yaml attached.
Sorry about the large font.

**Comment by jpellman** [comment]
Hi @nimzodisaster ,

Just to clarify the design of the new participant list builder, you shouldn't need to define an anatomical or functional template- those fields are only used when the 'Custom' file path option is toggled.  Also, BIDS currently does not have a set standard for site (see [here](https://groups.google.com/forum/#!searchin/bids-discussion/site%7Csort:relevance/bids-discussion/SwH-1KRnBU0/oCx0ynEpBAAJ)), although this may change in future iterations of the standard.

One question I wanted to ask about your dataset is whether or not 'sub-' is used in any of the filenames to denote that a file or directory represents a participant.  Since BIDS is based on a pairing of keys and values (such as 'sub' and ID, 'ses' and session name/number) an omission of a key might be tripping C-PAC up when it's trying to parse the dataset.

**Comment by nimzodisaster** [comment]
My apologies, I had not realized that BIDS was the total package.  
My data is in:

> /home/gose66/RestingState/DATA_ARCHIVE/PRIMARYSITES/{site}/{participant}/anat/mpragef.nii.gz
> /homegose66/RestingState/DATA_ARCHIVE/PRIMARYSITES/{site}/{participant}/func/funcf.nii.gz

where 

> site='MIND'
> participant='999999-999' for example. 

 After I double checked that image and path names were consistent with the template string I retried the subject builder with the custom option. This is the output.


---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.pyc in <lambda>(event)
    181 
    182         run_ext = wx.Button(btnPanel, ID_RUN_EXT, "Generate Subject Lists", (280,10), wx.DefaultSize, 0 )
--> 183         self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
    184         hbox.Add( run_ext, 1, flag=wx.LEFT|wx.ALIGN_LEFT, border=10)
    185 

/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.pyc in save(self, event, flag)
    379 
    380                 if flag == 'run':
--> 381                     if self.run(path) >0:
    382                         self.Close()
    383 

/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.pyc in run(self, config)
    248             else:
    249                 # Build the subject list from the data config
--> 250                 CPAC.utils.build_sublist.build_sublist(config)
    251 
    252                 # Extract arguments for supplementary files

/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/utils/build_sublist.pyc in build_sublist(data_config_yml)
    924                   'subjects. Check data organization and file patterns!'
    925         logger.error(err_msg)
--> 926         raise Exception(err_msg)
    927 
    928     # Write subject list out to out location

Exception: Unable to find both anatomical and functional data for any subjects. Check data organization and file patterns!

(ipython:3326): Gtk-WARNING **: Unable to find default local directory monitor type

**Comment by nimzodisaster** [comment]
The multiple checks in the same subject is strange to me: re:

2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...
2016-11-10 15:25:22,519 : Unable to find anatomical image for 999999-999_MIND_func. Skipping...

**Comment by nimzodisaster** [comment]
The problem seems to be expressed here:for anat in anat_paths:
        anat_sp = anat.split('/')
        subj = anat_sp[anat_ppant_idx]
        sess = anat_sp[anat_sess_idx]
        if bids_flag:
            site = ''
        else:
            site = anat_sp[anat_site_idx]
        subj_d = {'anat' : anat, 'creds_path' : creds_path, 'rest' : {},
                  'subject_id' : subj, 'unique_id' : sess,
                  'scan_parameters': site_scan_params}
        tmp_key = '_'.join([subj, site, sess])
        tmp_dict[tmp_key] = subj_d

and errors here
# Try and find the associated anat scan
        try:
            subj_d = tmp_dict[tmp_key]
        except KeyError as exc:
            logger.info('Unable to find anatomical image for %s. Skipping...'\
                        % tmp_key)
            continue

with tmp_key. printing out as
999999-999_MIND_func
so sess='func'
but I do not define any sessions, judt site and participants.

**Comment by jpellman** [comment]
Hi @nimzodisaster ,

Were you able to find some resolution for this error?  We'd like to work on fixing it / troubleshooting it further if it remains an issue.

**Comment by nimzodisaster** [comment]
I closed this for clarity, and opened https://github.com/FCP-INDI/C-PAC/issues/583 which partially identifies the bug. -hope is not a problem .-- Josh
