### ISSUE TITLE
 build_sublist.py from 1.0.0 Requires Session Subdirectory

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#583]
Using C-PAC 1.0.0 I was unable to use the subject generator for custom data format with the following specification and matching file structure: 

> /home/gose66/RS/test/testsites/{site}/{participant}/anat/mpragef.nii.gz
> /home/gose66/RS/test/testsites/{site}/{participant}/func/f.nii.gz

which produced this key piece of output to the terminal:

>  Unable to find anatomical image for 100000-100_MIND_func. Skipping..

where "100000-100_MIND_func" is defined on line 869 of build_sublist.py.
` 869:      tmp_key = '_'.join([subj, site, sess])`

suggesting that the code is defining the func subdirectory as a session subdirectory.

Indeed, the subject list generator completed without error  after restructuring some data under a session subdirectory and running the subject generator with:

> /home/gose66/RS/test/testsites/{site}/{participant}/{session}/anat/mpragef.nii.gz
> /home/gose66/RS/test/testsites/{site}/{participant}/{session}/func/f.nii.gz

I do not think this is intended behavior since I see [examples](http://fcp-indi.github.io/docs/user/subject_list_config.html) without a session subdirectory.

** I closed my[ previous issue](https://github.com/FCP-INDI/C-PAC/issues/582) for clarity since it was initially misspecified to BIDS.

**Comment by nimzodisaster** [comment]
```
if bids_flag:
        anat_site_idx = func_site_idx = None
        anat_path_dirs = anat_template.split('/')
        anat_ppant_idx = func_ppant_idx = anat_path_dirs.index('*')
        anat_sess_idx = func_sess_idx = len(anat_path_dirs)-3
        # If session index is ppant index, then no session dir
        if anat_ppant_idx == anat_sess_idx:
            anat_sess_idx = func_sess_idx = None
    # Get indices from {site} {ppant} {session} identifiers
    else:
        anat_site_idx, anat_ppant_idx, anat_sess_idx = \
            return_dir_indices(anat_template)
        func_site_idx, func_ppant_idx, func_sess_idx = \
            return_dir_indices(func_templat
```
Does the else in the above code fragment also need :

> `If session index is ppant index, then no session dir
>         if anat_ppant_idx == anat_sess_idx:
>             anat_sess_idx = func_sess_idx = None`

```

**Comment by sgiavasis** [comment]
I see where the problem is. @ccraddock , a default session tag if one isn't provided in a custom path template, similar to BIDS and "ses-1" sounds good?

**Comment by sgiavasis** [comment]
In situations where there is no session-level directory specified, a default session label ("ses-1") will be placed into the unique ID following release 1.0.1.
