### ISSUE TITLE
CPAC 1.0.0 pipeline editor saves config yml with incorrect variable name

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#584]
After creating and saving a pipeline in the GUI, I am unable to load the pipeline again. I receive this error:

> ERROR: Configuration file could not be loaded properly - the file might be access-protected or you 

> might have chosen the wrong file.
> 
> Error name: main_window_0001
>  
> Exception: 'Configuration' object has no attribute 'resolution_for_func'
> 

 In my config file, I found that  ${resolution_for_func} is not defined, but this is:
resolution_for_func_preproc :  3mm

config file:

> The resolution (in mm) to which the preprocessed, registered functional timeseries outputs are written into. Note that selecting a 1 mm or 2 mm resolution might substantially increase your RAM needs- these resolutions should be selected with caution. For most cases, 3 mm or 4 mm resolutions are suggested.
> resolution_for_func_preproc :  3mm
>  
>  The resolution (in mm) to which the registered derivative outputs are written into.
> resolution_for_func_derivative :  3mm
> 
> 
>  Standard FSL Skull Stripped Template. Used as a reference image for functional registration
> template_brain_only_for_func :  /usr/share/fsl/5.0/data/standard/MNI152_T1_${resolution_for_func}_brain.nii.gz
> 
> 
>  Standard FSL Anatomical Brain Image with Skull
> template_skull_for_func :  /usr/share/fsl/5.0/data/standard/MNI152_T1_${resolution_for_func}.nii.gz

**Comment by sgiavasis** [comment]
Hi nimzodisaster,

If you open your pipeline configuration YAML file in a text editor and search it, is there an instance of the "resolution_for_func" parameter?

By the way, thank you for all of the really helpful feedback and input.

**Comment by nimzodisaster** [comment]
No, resolution_for_func isn't defined in the yaml, but was being referenced in these lines: 
```
template_brain_only_for_func : /usr/share/fsl/5.0/data/standard/MNI152_T1_${resolution_for_func}_brain.nii.gz
and
template_skull_for_func : /usr/share/fsl/5.0/data/standard/MNI152_T1_${resolution_for_func}.nii.gz

```
I noticed in [pipeline_config.yaml](https://github.com/FCP-INDI/C-PAC/blob/c50afc343aaae3b6b071d0e109fb581d2d5fc3e5/configs/pipeline_config.yml) on this github does not match my yaml in that those two lines replace ${resolution_for_func} with ${resolution_for_func_prerpoc}
I did the same and am now able to load the yaml config and process my data. So I suspect that in the transition to the new vars in 1.0.0 something has been left unchanged somewhere, or else when I installed the new C-Pac 1.0.0, it didn't over-write all my old files..not sure yet..but processing is going fine.

**Comment by sgiavasis** [comment]
I see- we do have functionality which detects when new pipeline configuration parameters are missing in old configuration files and then prompts you to view your configuration and save the new version, but there isn't anything which finds deprecated parameters and removes them. Though, if there are parameters in your config that are no longer needed, this doesn't cause problems. As you discovered, the only problem here is that one of the old parameter names was being used as a link in the value of other parameters.

I think this should be fine the way it is (i.e. no need for some utility to find and correct these), since such changes are rare between version to version. However, I think we'd benefit from putting in some catches/messages that inform the user what they need to do when this happens, instead of just saying "Exception: 'Configuration' object has no attribute 'resolution_for_func'" etc.

**Comment by nimzodisaster** [comment]
Hmm. I think I know what happened then. I had loaded up a config file produced from a previous C-PAC version into the 1.0.0 GUI, was greeted with a message of some undefined parameters, and then I updated it in the GUI,  saved it, and then I encountered the error posted above. Clearly, I should have mentioned that I started with an old config file from the start.. Let me try making a config from scratch and see if I encounter the error.

**Comment by nimzodisaster** [comment]
And I confirmed this. Issue was only encountered when beginning with the config file created from a previous version of C-PAC. I should have checked that first.

**Comment by sgiavasis** [comment]
Yep- but it's our responsibility to have clearer error messages! Thanks for your patience.

**Comment by sgiavasis** [comment]
I've added in a better error catch for this, in this specific scenario.
