### ISSUE TITLE
Crash in anatomical registration after installing newer version of CPAC

### ISSUE THREAD

**Issue by transpersonify** [FCP-INDI/C-PAC#599]
Hi, My previous installation was working fine, however after updating CPAC to latest version I am getting the following crash errors while anatomical registration.  Rest of the outputs are fine. I assume the problem is with nipype?
_________________________________________________________________________________________
File: crash-20161120-022749-drvani-montage_s.pklz
Node: resting_preproc_subj01.montage_mni_anat_0.montage_s
Working directory: /home/drvani/Desktop/seed_based_fmri/working_dir/resting_preproc_subj01/montage_mni_anat_0/montage_s

Node inputs:

cbar_name = red
function_str = S'def montage_sagittal(overlay, underlay, png_name, cbar_name):\n\n    """\n    Draws Montage using overlay on Anatomical brain in Sagittal Direction\n    calls make_montage_sagittal\n\n    Parameters\n    ----------\n\n    overlay : string\n            Nifi file\n\n    underlay : string\n            Nifti for Anatomical Brain\n\n    cbar_name : string\n            name of the cbar \n\n    png_name : string\n            Proposed name of the montage plot\n\n    Returns\n    -------\n\n    png_name : Path to generated PNG\n\n    """\n    import os\n    from CPAC.qc.utils import make_montage_sagittal\n    pngs = None\n    if isinstance(overlay, list):\n        pngs = []\n\n        for ov in overlay:\n            fname = os.path.basename(os.path.splitext(os.path.splitext(ov)[0])[0])\n            pngs.append(make_montage_sagittal(ov, underlay, fname + \'_\' + png_name, cbar_name))\n\n    else:\n\n        pngs = make_montage_sagittal(overlay, underlay, png_name, cbar_name)\n    png_name = pngs\n\n    return png_name\n'
.
ignore_exception = False
overlay = /home/drvani/Desktop/seed_based_fmri/working_dir/resting_preproc_subj01/montage_mni_anat_0/resample_o/MNI152_Edge_AllTissues_1mm.nii.gz
png_name = mni_anat_s.png
underlay = /home/drvani/Desktop/seed_based_fmri/working_dir/resting_preproc_subj01/montage_mni_anat_0/resample_u/transform_Warped_1mm.nii.gz

Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 40, in montage_sagittal
  File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 2250, in make_montage_sagittal
    cbar = grid.cbar_axes[0].colorbar(im)
UnboundLocalError: local variable 'im' referenced before assignment
Interface Function failed to run. 
_________________________________________________________________________________________

File: crash-20161120-022726-drvani-montage_a.pklz
Node: resting_preproc_subj01.montage_mni_anat_0.montage_a
Working directory: /home/drvani/Desktop/seed_based_fmri/working_dir/resting_preproc_subj01/montage_mni_anat_0/montage_a

Node inputs:

cbar_name = red
function_str = S'def montage_axial(overlay, underlay, png_name, cbar_name):\n\n    """\n    Draws Montage using overlay on Anatomical brain in Axial Direction\n    calls make_montage_axial\n\n    Parameters\n    ----------\n\n    overlay : string\n            Nifi file\n\n    underlay : string\n            Nifti for Anatomical Brain\n\n    cbar_name : string\n            name of the cbar \n\n    png_name : string\n            Proposed name of the montage plot\n\n    Returns\n    -------\n\n    png_name : Path to generated PNG\n\n    """\n    import os\n    from CPAC.qc.utils import make_montage_axial\n    pngs = None\n    if isinstance(overlay, list):\n        pngs = []\n\n        for ov in overlay:\n            fname = os.path.basename(os.path.splitext(os.path.splitext(ov)[0])[0])\n            pngs.append(make_montage_axial(ov, underlay, fname + \'_\' + png_name, cbar_name))\n    else:\n\n        pngs = make_montage_axial(overlay, underlay, png_name, cbar_name)\n\n    png_name = pngs\n\n    return png_name\n'
.
ignore_exception = False
overlay = /home/drvani/Desktop/seed_based_fmri/working_dir/resting_preproc_subj01/montage_mni_anat_0/resample_o/MNI152_Edge_AllTissues_1mm.nii.gz
png_name = mni_anat_a.png
underlay = /home/drvani/Desktop/seed_based_fmri/working_dir/resting_preproc_subj01/montage_mni_anat_0/resample_u/transform_Warped_1mm.nii.gz

Traceback: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/plugins/multiproc.py", line 18, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1424, in run
    self._run_interface()
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1534, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/lib/python2.7/dist-packages/nipype/pipeline/engine.py", line 1660, in _run_command
    result = self._interface.run()
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 998, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python2.7/dist-packages/nipype/interfaces/utility.py", line 436, in _run_interface
    out = function_handle(**args)
  File "<string>", line 39, in montage_axial
  File "/usr/local/lib/python2.7/dist-packages/CPAC/qc/utils.py", line 2086, in make_montage_axial
    cbar = grid.cbar_axes[0].colorbar(im)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/axes_grid1/axes_grid.py", line 85, in colorbar
    cb = Colorbar(self, mappable, orientation=orientation, **kwargs)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/axes_grid1/colorbar.py", line 706, in __init__
    mappable.autoscale_None() # Ensure mappable.norm.vmin, vmax
AttributeError: 'NoneType' object has no attribute 'autoscale_None'
Interface Function failed to run.

**Comment by jpellman** [comment]
Hi @transpersonify ,

Would you be able to post your pipeline config here?  Also, to verify- are you using a fresh working directory or is this from a run that used 0.3.9?

We recently removed the QC feature from C-PAC 1.0.0 temporarily so that we could debug it more thoroughly and my intuition is that the errors you are receiving are related to this.

**Comment by transpersonify** [comment]
Yeah I have enabled Quality Check. I will try with QC disabled and post the result soon. Thanks !

**Comment by jpellman** [comment]
Hi @transpersonify ,

Was the pipeline configuration you're using generated by a version of C-PAC from 0.3.9 or prior?  There are also some other elements of the pipeline configuration YAML that have changed between releases that might cause a run to experience issues.

**Comment by transpersonify** [comment]
Yes. The configuration I was using was from 0.3.9 version.

**Comment by jpellman** [comment]
Hi @transpersonify ,

I would suggest re-opening your configuration YAML and updating it manually using the C-PAC GUI to ensure that all parameters are compatible with the newest version of C-PAC.  In particular, settings for time series extraction and SCA are encoded very differently in the new pipeline configuration format.

**Comment by sgiavasis** [comment]
Closing this issue because it has been awhile. If there are any more issues or questions, please feel free to open a new one.

Best,
The C-PAC Team
