### ISSUE TITLE
Missing items from CPAC installation guide

### ISSUE THREAD

**Issue by alexanderalang** [FCP-INDI/C-PAC#600]
To install AFNI on a non-Fedora 21 64-bit Linux machine you may run the follow commands as the super user:

For AFNI to be available globally on your machine, you should then add the following lines to the file located at /etc/bash.bashrc:

The commands referenced above are never listed

**Comment by jpellman** [comment]
Hi @alexanderalang ,

I apologize for that- I made a syntax error with the files we use to generate our documentation and that prevented the commands from displaying.  The commands should be visible now.
