### ISSUE TITLE
data_config_test.yml does not exit

### ISSUE THREAD

**Issue by alexanderalang** [FCP-INDI/C-PAC#601]
when I try to import CPAC, I get this error: 

No such file or directory: '/Users/vhasfclanga/Downloads/C-PAC/test/resources/settings/configs/data_config_test.yml'.

I got these warning when running setup.py install:
UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
Warning: No module named anat_preproc/bin/sh: hg: command not found

Seems like the missing anat_preproc module is causing the error. any Idea why it would be missing?

Here is the full traceback

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "CPAC/__init__.py", line 21, in <module>
    import anat_preproc, \
  File "CPAC/anat_preproc/__init__.py", line 1, in <module>
    from anat_preproc import create_anat_preproc
  File "CPAC/anat_preproc/anat_preproc.py", line 1, in <module>
    from nipype.interfaces.afni import preprocess
  File "/Users/vhasfclanga/anaconda/envs/cpac/lib/python2.7/site-packages/nipype/__init__.py", line 11, in <module>
    from .utils.config import NipypeConfig
  File "/Users/vhasfclanga/anaconda/envs/cpac/lib/python2.7/site-packages/nipype/utils/config.py", line 12, in <module>
    standard_library.install_aliases()
  File "/Users/vhasfclanga/anaconda/envs/cpac/lib/python2.7/site-packages/future/standard_library/__init__.py", line 483, in install_aliases
    import test
  File "test/__init__.py", line 26, in <module>
    res_f = open(DATA_CONFIG, 'w')
IOError: [Errno 2] No such file or directory: '/Users/vhasfclanga/Downloads/C-PAC/test/resources/settings/configs/data_config_test.yml'

**Comment by jpellman** [comment]
Hi @alexanderalang ,

I'm not entirely sure what might be going on with this error, although my primary suspicion is that it is due to the version of Python's future _library_ that you're using.  Would you be willing to post the version here?  You can obtain this using the following commands in a Python interpreter:
```

import future
print future.__version__
```

**Comment by alexanderalang** [comment]
Right, my bad. the version of future I have installed is 0.15.2.

**Comment by alexanderalang** [comment]
update:

I realized I had nipype version 0.12, so I switched to to version 0.11 and tried importing CPAC. Now the error has to do with with a nipype module not being found.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vhasfclanga/anaconda/envs/cpac/lib/python2.7/site-packages/CPAC/__init__.py", line 21, in <module>
    import anat_preproc, \
  File "/Users/vhasfclanga/anaconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/__init__.py", line 3, in <module>
    from cpac_pipeline import run
  File "/Users/vhasfclanga/anaconda/envs/cpac/lib/python2.7/site-packages/CPAC/pipeline/cpac_pipeline.py", line 22, in <module>
    from nipype.pipeline.engine.utils import format_dot
ImportError: No module named utils

**Comment by alexanderalang** [comment]
this is weird

>>> import nipype.pipeline.engine
>>> dir(nipype.pipeline.engine)
['Bunch', 'CommandLine', 'DynamicTraitedSpec', 'File', 'FileNotFoundError', 'InputMultiPath', 'Interface', 'InterfaceResult', 'JoinNode', 'MapNode', 'Node', 'OrderedDict', 'Template', 'TraitDictObject', 'TraitListObject', 'TraitedSpec', 'Undefined', 'Workflow', 'WorkflowBase', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_write_inputs', 'cPickle', 'clean_working_directory', 'config', 'copyfiles', 'create_function_from_source', 'datetime', 'deepcopy', 'errno', 'evaluate_connect_function', 'export_graph', 'filename_to_list', 'flatten', 'fnames_presuffix', 'format_dot', 'format_node', 'generate_expanded_graph', 'get_print_name', 'gethostname', 'getsource', 'glob', 'gzip', 'inspect', 'isdefined', 'list_to_filename', 'load_json', 'loadpkl', 'logger', 'logging', 'make_output_dir', 'md5', 'merge_dict', 'mkdtemp', 'modify_paths', 'np', 'nx', 'op', 'os', 'package_check', 're', 'rmtree', 'save_json', 'savepkl', 'sha1', 'shutil', 'six', 'split_filename', 'str2bool', 'sys', 'topological_sort', 'traits', 'unflatten', 'warn', 'write_rst_dict', 'write_rst_header', 'write_rst_list', 'write_workflow_prov']
>>> nipype.__version__
'0.11.0'
>>> import nipype.pipeline.engine.utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named utils
>>> 


I cant find the utils module in nipype.pipeline.engine

in this similar error https://github.com/FCP-INDI/C-PAC/issues/543,

the utils module was being imported from nipype.pipeline(which does exist for me), not nipype.pipeline.engine.

is there a reason why CPAC is trying to import utils from pipeline.engine?

**Comment by jpellman** [comment]
Hi @alexanderalang ,

There's a typo in the installation instructions.  C-PAC 1.0.0 requires nipype 0.12, which imports utils from pipeline.engine.

**Comment by jpellman** [comment]
One thing I'd like to clarify about the initial error you were receiving- when you are importing C-PAC, what directory are you located in in your terminal?  I'm able to replicate the error you get if I am within the directory that I downloaded C-PAC to (this would be ''/Users/vhasfclanga/Downloads/C-PAC' in your case).  If you're in the directory I mentioned in the last sentence, are you able to import C-PAC if you navigate to another directory?

**Comment by alexanderalang** [comment]
I want to say that I wasn't, since I had just opened a new terminal so I was probably in my home directory. After reinstalling the correct version of nipype, CPAC imports with no errors. Not sure why.
