### ISSUE TITLE
Update install script so that ANTS is compiled directly for Ubuntu 16.04

### ISSUE THREAD

**Issue by shenlongsanti** [FCP-INDI/C-PAC#607]
Dear experts,

I've been having a couple of errors trying to use C-pac, so I formated my computer and tried to install the new version (version 1.0.1).
Unfortunately something went wrong when I tried to install C-pac, and  ANTs was not installed. The error is as follows:

Installing ANTS.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package ants is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source.

E: Package 'ants' has no installation candidate
Installing C-PAC Image Resources.

It's been a while that I'm trying to use C-pac and, how I said, I've been having errors frequently. I really believe this is a very goods software but this many issues are a little discouraging.

I really appreciate if you guys could help me.

Thank you in advance,

Santiago Arcentales.

**Comment by jpellman** [comment]
Hi @shenlongsanti ,

The issue here appears to be that ANTS, which is installed via Neurodebian in the install script, does not have a package available for Ubuntu 16.04 (the page [here](http://neuro.debian.net/pkgs/ants.html) indicates that it only has packages for 12.04, 14.04 and 16.10).  You should be able to compile ANTS from source using the instructions [here](http://fcp-indi.github.io/docs/user/install.html#installing-ants).  We'll update the install script to take this into account so it doesn't happen in the future.

**Comment by nimzodisaster** [comment]
I've always had the most success with ANTs when building it from source. 
One thing I wanted to suggest in addition to the build instructions John linked to is to copy the scripts in stnava/ANTs/Scripts/ to /opt/ants/bin --or add the scripts sirectory to the path. While C-PAC probably doesn't make use of ANTs scripts like BuildOptimalTemplate, if the C-PAC installer is going to build ANTs it should probably make ANTs fully operable, IMO.

**Comment by shenlongsanti** [comment]
Hi John,

Your link was very useful, We could install the ANTS successfully.

Unfortunately, another error appeared when we try to run our pipeline:



discarding /usr/local/bin/miniconda/bin from PATH
prepending /usr/local/bin/miniconda/envs/cpac/bin to PATH
nf05@nfis05:~$ cpac_gui


ERROR: Configuration file could not be loaded properly - the file might be access-protected or you might have chosen the wrong file.

Error name: main_window_0001


Exception: 'Configuration' object has no attribute 'resolution_for_func'
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/CPAC/GUI/interface/windows/main_window.py", line 686, in AddConfig
    if c.pipelineName != None:
UnboundLocalError: local variable 'c' referenced before assignment

Have you seen this before?

Thank You in advance for your help.




________________________________
De: John Pellman <notifications@github.com>
Enviado: segunda-feira, 28 de novembro de 2016 15:47
Para: FCP-INDI/C-PAC
Cc: shenlongsanti; Mention
Assunto: Re: [FCP-INDI/C-PAC] Error installing C-PAC new version on linux 16.04 (#607)


Hi @shenlongsanti<https://github.com/shenlongsanti> ,

The issue here appears to be that ANTS, which is installed via Neurodebian in the install script, does not have a package available for Ubuntu 16.04 (the page here<http://neuro.debian.net/pkgs/ants.html> indicates that it only has packages for 12.04, 14.04 and 16.10). You should be able to compile ANTS from source using the instructions here<http://fcp-indi.github.io/docs/user/install.html#installing-ants>. We'll update the install script to take this into account so it doesn't happen in the future.

-

**Comment by jpellman** [comment]
Hi @shenlongsanti ,

Some variable names in the pipeline configuration YAML have changed names between the C-PAC releases. 'resolution_for_func', for instance, is now separated into two variables - 'resolution_for_func_preproc' and 'resolution_for_func_derivative' in the latest version of C-PAC.  'resolution_for_func_preproc' is the resolution that images are written to in template space after preprocessing, and 'resolution_for_func_derivative' is the resolution that the derivative outputs are written to in template space.

If you're using a pipeline config from an older version of C-PAC with a newer version of C-PAC, my suggestion would be to open the older config in the pipeline configuration builder, make sure that these fields are populated, re-save the pipeline, and then try running the pipeline again.

**Comment by nimzodisaster** [comment]
Between 0.39 and 1.X.X
or
between 1.0.0 to 1.0.1?

**Comment by jpellman** [comment]
Between 0.3.9 and 1.X.X

**Comment by jpellman** [comment]
We've added functionality in that adds in the version number of C-PAC that generated a pipeline configuration file to that configuration file, so in the future it should be easier to check for compatibility before running a pipeline.

**Comment by shenlongsanti** [comment]
Hi John!

Thank you very much, It really worked!! but, unfortunately, when We tried to configure the subject List We had a couple problems. The files attached show what happened.

The file path original is:


 /media/nf05/D4E47912E478F7D6/Teste1_FSL/Imgs/ACA/Anat/ACA_VBM.nii


and to run with cpac we changed some names to:


/media/nf05/D4E47912E478F7D6/{site}/Imgs/{participant}/Anat/*_VBM.nii


Have you seen this before?


Thank You in advance






________________________________
De: John Pellman <notifications@github.com>
Enviado: sexta-feira, 16 de dezembro de 2016 20:57
Para: FCP-INDI/C-PAC
Cc: shenlongsanti; Mention
Assunto: Re: [FCP-INDI/C-PAC] Update install script so that ANTS is compiled directly for Ubuntu 16.04 (#607)


Hi @shenlongsanti<https://github.com/shenlongsanti> ,

Some variable names in the pipeline configuration YAML have changed names between the C-PAC releases. 'resolution_for_func', for instance, is now separated into two variables - 'resolution_for_func_preproc' and 'resolution_for_func_derivative' in the latest version of C-PAC. 'resolution_for_func_preproc' is the resolution that images are written to in template space after preprocessing, and 'resolution_for_func_derivative' is the resolution that the derivative outputs are written to in template space.

If you're using a pipeline config from an older version of C-PAC with a newer version of C-PAC, my suggestion would be to open the older config in the pipeline configuration builder, make sure that these fields are populated, re-save the pipeline, and then try running the pipeline again.

-

**Comment by jpellman** [comment]
Hi @shenlongsanti ,

Unfortunately, I don't see any attachments here on the Github issue- it looks like Github may have filtered them out from your e-mail.  

However, there were a number of bugs with the subject builder in 1.0.0 that we fixed in 1.0.1 (see the revision notes [here](http://fcp-indi.github.io/docs/user/rnotes.html#version-1-0-1-beta-2016-12-09)), and my intuition is that you are encountering one of those- could you install the latest version of C-PAC and see if the issue you are encountering still persists?  If it does, could you then please attach your configuration files using Github's interface?
