### ISSUE TITLE
'Sublist Name' dialogue won't let you cancel

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#615]
After you click 'Generate Subject List' in the Subject List Builder, a window will pop up prompting you to give a name to the subject list.  If I click 'Cancel' on this window (because I want to go back to the subject list builder) the subject list name dialogue re-spawns and won't allow me to go back.

**Comment by sgiavasis** [comment]
@jpellman , could you re-pull and try again? It takes two clicks of 'Cancel' for me to work and I don't know if this is a specific wx thing or not.

**Comment by jpellman** [comment]
It takes two clicks for me too.

**Comment by sgiavasis** [comment]
At least for now it will actually go away if you click it twice. Making note here, will wrangle with the more minute problem of the double-click thing in the next release- sending to 1.0.2.

**Comment by sgiavasis** [comment]
With the introduction of the new pipeline builder GUI, we will be phasing these issues out.

More info on the new GUI available here:
http://fcp-indi.github.io/docs/user/new_gui.html
