### ISSUE TITLE
Giving one dataset a scan parameter list for another dataset

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#616]
I gave the OpenfMRI rhyme judgement dataset a [scan parameters csv for ABIDE](http://fcp-indi.github.io/docs/user/_static/scan_parameters_abide.csv).  When I generated the subject list, the terminal printed this:

```
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
Site ds000003_R2.0.2 missing from scan parameters csv, skipping...
```

This looks all good.  However, when I open the subject list, I get all of the parameters for all of the ABIDE sites nested under each participant.  These site parameters shouldn't end up getting written out to the subject list if the only site recognized by the subject list builder isn't in the scan params csv.

[data_config_abidescanparamsforopenfmri.txt](https://github.com/FCP-INDI/C-PAC/files/632458/data_config_abidescanparamsforopenfmri.txt)
[CPAC_subject_list_abidescanparamsforopenfmri.txt](https://github.com/FCP-INDI/C-PAC/files/632459/CPAC_subject_list_abidescanparamsforopenfmri.txt)

**Comment by jpellman** [comment]
Relatedly, if I add the site to the scan parameters csv and then generate the subject list with the same settings, all of the other sites are still nested below each subject.

[CPAC_subject_list_openfmrisiteadded.txt](https://github.com/FCP-INDI/C-PAC/files/632480/CPAC_subject_list_openfmrisiteadded.txt)

**Comment by jpellman** [comment]
Now I'm getting this error with the data config:

```
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/cpac101_120716/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 183, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
  File "/usr/local/bin/miniconda/envs/cpac101_120716/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 450, in save
    if self.run(path) >0:
  File "/usr/local/bin/miniconda/envs/cpac101_120716/lib/python2.7/site-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 250, in run
    CPAC.utils.build_sublist.build_sublist(config)
  File "/usr/local/bin/miniconda/envs/cpac101_120716/lib/python2.7/site-packages/CPAC/utils/build_sublist.py", line 995, in build_sublist
    subj_d['func'][scan]["scan_parameters"] = scan_params
TypeError: 'str' object does not support item assignment


```

**Comment by jpellman** [comment]
This error also affects data configs where no scan parameters CSV has been specified.

**Comment by sgiavasis** [comment]
Forgot to push that last commit- sorry about that! Try again.

**Comment by jpellman** [comment]
Now it behaves as expected.
