### ISSUE TITLE
BIDS base directory does not support S3

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#617]
If I set the BIDS base directory to a path in S3 (e.g., 's3://fcp-indi/data/Projects/RocklandSample') with the data format set to 'BIDS' I get the following error:

> bidsBaseDir field contains incorrect path. Please update the path!

C-PAC should be able to download BIDS datasets in S3 in addition to being able to download Custom paths in S3.

**Comment by jpellman** [comment]
When I set the data format to 'BIDS' and give the subject list builder a BIDS dataset now, all seems to go well.  The only odd thing I noticed is that the 'scan_parameters' key for each participant now has the parameters from the sidecar JSON loaded in.  This seems like an added feature but I just wanted to check about it.

The only thing I can think of that might be problematic is that 'scan_parameters' has used the 'tr' key to encode repetition time in the past, whereas the subject list generated using the 'BIDS' data format uses the BIDS nomenclature ('RepetitionTime') instead.

[CPAC_subject_list_BIDSoption.txt](https://github.com/FCP-INDI/C-PAC/files/640680/CPAC_subject_list_BIDSoption.txt)

**Comment by jpellman** [comment]
Sorry, I don't think I was thinking straight when I wrote my previous comment.  For some reason I thought that this was an issue I remember encountering earlier where the BIDS path didn't work at all- I haven't yet tested this with S3 but will let you know how that works.

**Comment by jpellman** [comment]
I'm still getting the same error from earlier.

**Comment by sgiavasis** [comment]
To note it here, the builder can now connect to S3 when given an S3 BIDS base directory path, but now I'm getting this:

2016-12-14 16:13:45,649 : There was an error in retrieving S3 bucket: *.
Error: Unable to connect to bucket: *. Error message:
Parameter validation failed:
Invalid bucket name "*": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"
161214-16:13:45,649 sublist_builder ERROR:
     There was an error in retrieving S3 bucket: *.
Error: Unable to connect to bucket: *. Error message:
Parameter validation failed:
Invalid bucket name "*": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 183, in <lambda>
    self.Bind(wx.EVT_BUTTON, lambda event: self.save(event,'run'), id=ID_RUN_EXT)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 453, in save
    if self.run(path) >0:
  File "/usr/local/lib/python2.7/dist-packages/CPAC/GUI/interface/windows/dataconfig_window.py", line 250, in run
    CPAC.utils.build_sublist.build_sublist(config)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/utils/build_sublist.py", line 834, in build_sublist
    anat_paths = return_s3_filepaths(anat_template, creds_path, bids_flag)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/utils/build_sublist.py", line 629, in return_s3_filepaths
    raise Exception(err_msg)
Exception: There was an error in retrieving S3 bucket: *.
Error: Unable to connect to bucket: *. Error message:
Parameter validation failed:
Invalid bucket name "*": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"

**Comment by sgiavasis** [comment]
All done.
