### ISSUE TITLE
Generate subject lists doesn't verify if the templates are globbing non-NifTI files

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#619]
The subject list builder doesn't have any checks to make sure that the files that are matched to the anatomical and functional templates are NifTIs.  This can lead to non-NifTI files mistakenly being added to the subject list YAML (such as the "events.tsv" files in the attached subject list).

Data config:
[both_tsv_and_nifti_dataconfig.txt](https://github.com/FCP-INDI/C-PAC/files/635007/both_tsv_and_nifti_dataconfig.txt)

Subject list:
[both_tsv_and_nifti_sublist.txt](https://github.com/FCP-INDI/C-PAC/files/635008/both_tsv_and_nifti_sublist.txt)

**Comment by jpellman** [comment]
It also looks like the functional template that I used in this example also only globbed one of the files in the func directory instead of both- so for some subjects it matched a TSV file, while for others it matched the NifTI

**Comment by sgiavasis** [comment]
Blocked by #627 currently, putting back on sprint backlog for now.

**Comment by sgiavasis** [comment]
Resolved in 1.0.2!
