### ISSUE TITLE
Fields from older data configurations remain populated when loading new data configurations

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#620]
If I first load a data configuration with _Subjects to Include_, _Sites to Include_, and  _Scan Parameters File_  populated:

[data_config_pop.txt](https://github.com/FCP-INDI/C-PAC/files/637335/data_config_pop.txt)

And then load a config where none of those fields are populated:

[data_config_no_pop.txt](https://github.com/FCP-INDI/C-PAC/files/637336/data_config_no_pop.txt)

Those fields remain populated even after the config where they shouldn't be populated is loaded.

**Comment by sgiavasis** [comment]
@jpellman give this another shot, on 1.0.2_development.

Side note: wx is weird

**Comment by jpellman** [comment]
I'm still getting the same issue.

**Comment by sgiavasis** [comment]
Really? Strange. It's not happening for me anymore.

I'll wait and take a look in person.
