### ISSUE TITLE
h5py error

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#624]
Some of our users have encountered the compilation error described [here](https://groups.google.com/forum/#!searchin/cpax_forum/h5py%7Csort:relevance/cpax_forum/xcdm8mM8Klc/it1OhuM8BAAJ) after importing C-PAC when _h5py_ is installed.

This can be traced back to several lines of code [here](https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/__init__.py#L9-L10) in the _\_\_init\_\_.py_ file, which make use of Cython's _pyximport_ function.  According to the [documentation for pyximport](http://docs.cython.org/en/latest/src/reference/compilation.html#compiling-with-pyximport), any module that Python tries to import with a _.pyx_ file in it will be run through Cython.  _pyximport_ assumes that no external libraries are needed by the _.pyx_ file when it is built.  C-PAC's own modules import _nibabel_, which then tries to import _h5py_.  Because _pyximport_ is active when _h5py_ is being imported, it finds _.pyx_ files in _h5py_ and attempts to build them unsuccessfully since they require external libraries.

This might be fixable by changing the scope where _pyximport_ is imported (i.e., by putting those lines in submodule init files for network centrality and other submodules that use Cython).

**Comment by anibalsolon** [comment]
Cython is deprecated now for C-PAC :tada:
