### ISSUE TITLE
Re-definition of run method in each import in pipeline module __init__.py

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#630]
@erramuzpe previously noticed that the run method was repeatedly being redefined in the \_\_init\_\_.py file for the pipeline module (see [here](https://github.com/FCP-INDI/C-PAC/blob/599801b29b57e74a171fa2a8b25000470cbd5c78/CPAC/pipeline/__init__.py)).  We should fix this / give the run methods unique names perhaps.

**Comment by nx10** [comment]
Outdated
