### ISSUE TITLE
run_cpac_on_cluster function uses old naming convention

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#631]
The function for submitting jobs to a cluster still uses the old naming convention.  This should be updated since these Configuration object attributes will no longer be in the pipeline config YAML.

https://github.com/FCP-INDI/C-PAC/blob/603beb7b84243da5c881fea829796105e139c6cc/CPAC/pipeline/cpac_runner.py#L276

**Comment by nx10** [comment]
Outdated
