### ISSUE TITLE
check_for_s3 is run on scan_parameters key

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#633]
If a subject list YAML contains the 'scan_parameters' key (populated from a scan parameters CSV) under the rest dictionary, the [check_for_s3 ](https://github.com/FCP-INDI/C-PAC/blob/c50afc343aaae3b6b071d0e109fb581d2d5fc3e5/CPAC/utils/datasource.py#L53) function in utils/datasource.py will be run with this key as the 'file_path' parameter.  Since this key is mapped to a dictionary, rather than an expected string value check_for_s3 will crash.

**Comment by sgiavasis** [comment]
This has been resolved.
