### ISSUE TITLE
Remove non-AFNI Centrality measures functions

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#634]
Remove the Cython-based Centrality functions now that they have been implemented as AFNI tools. This will reduce a lot of overhead regarding installation/compilation with Cython.

**Comment by anibalsolon** [comment]
Bump to remove the rest of python-based centrality and add AFNI bins as dependencies.

**Comment by nx10** [comment]
Fixed in https://github.com/FCP-INDI/C-PAC/pull/958
