### ISSUE TITLE
is there a way to turn off some of the registrations steps?

### ISSUE THREAD

**Issue by jcrdubois** [FCP-INDI/C-PAC#635]
Although I understand that it is best to use CPAC only (so as to have a self-contained description of everything that was done to the original data) is there a way to feed already "minimally preprocessed" data to the C-PAC framework? (e.g. data that is already in MNI space)

**Comment by jpellman** [comment]
Hi @jcrdubois ,

This is a very good question- the ability to inject pre-processed data directly into a pipeline is functionality that we are striving towards in C-PAC, though it is not yet present in the current version.  Our quality assessment protocol package does this already, and can offer a preview of what we are working towards: http://preprocessed-connectomes-project.org/quality-assessment-protocol/#subject-list-yaml-files
