### ISSUE TITLE
Strategy graphs are failing due to change in networkx usage

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#641]
The following line to produce strategy graphs will fail due to a change in networkx starting w/ version 1.11:

https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_pipeline.py#L5136

The new syntax should be something like:

nx.drawing.nx_pydot.write_dot(G, dotfilename)

There should be some lines to check the verson of networkx too.

See: https://github.com/nipy/nipype/issues/1350 , https://github.com/networkx/networkx/issues/1984

**Comment by sgiavasis** [comment]
This was resolved in v1.1.0.
