### ISSUE TITLE
Pipeline Crashing During check_for_s3

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#643]
Happy New Year!

I am using 1.0.1. I am trying to run some new subjects through a pipeline originally created in 1.0.0 and then edited in 1.0.1 to change number of processors.

Preprocessing is crashing during check_for_s3.
Attached is the pipeline, and below the the pklz crash report:

(cpac)gose66@:~/RS/crsh$ nipype_display_crash crash-20170119-102018-gose66-check_for_s3.c0-03a90160-de14-448e-a5d0-2db9e2a9b377.pklz

File: crash-20170119-102018-gose66-check_for_s3.c0-03a90160-de14-448e-a5d0-2db9e2a9b377.pklz
Node: resting_preproc_111667-100_sess1.func_gather_0.check_for_s3.c0
Working directory: /home/gose66/RS/wrk/resting_preproc_111667-100_sess1/func_gather_0/_scan_scan_parameters/check_for_s3

Node inputs:

creds_path = None
file_path = None
function_str = def check_for_s3(file_path, creds_path, dl_dir=None, img_type='anat'):
    '''
    '''

    # Import packages
    import os
    import nibabel as nib
    import botocore.exceptions

    from indi_aws import fetch_creds

    # Init variables
    s3_str = 's3://'
[pipeline.txt](https://github.com/FCP-INDI/C-PAC/files/718027/pipeline.txt)

    if dl_dir is None:
        dl_dir = os.getcwd()

    # Explicitly lower-case the "s3"
    if file_path.lower().startswith(s3_str):
        file_path_sp = file_path.split('/')
        file_path_sp[0] = file_path_sp[0].lower()
        file_path = '/'.join(file_path_sp)

    # Check for s3 string in filepaths
    if file_path.startswith(s3_str):
        # Get bucket name and bucket object
        bucket_name = file_path.replace(s3_str, '').split('/')[0]
        bucket = fetch_creds.return_bucket(creds_path, bucket_name)

        # Extract relative key path from bucket and local path
        s3_prefix = os.path.join(s3_str, bucket_name)
        s3_key = file_path.replace(s3_prefix, '').lstrip('/')
        local_path = os.path.join(dl_dir, os.path.basename(s3_key))

        # Get local directory and create folders if they dont exist
        local_dir = os.path.dirname(local_path)
        if not os.path.exists(local_dir):
            os.makedirs(local_dir)

        # Download file
        try:
            bucket.download_file(Key=s3_key, Filename=local_path)
        except botocore.exceptions.ClientError as exc:
            error_code = int(exc.response['Error']['Code'])
            if error_code == 403:
                err_msg = 'Access to bucket: "%s" is denied; using credentials '\
                          'in subject list: "%s"; cannot access the file "%s"'\
                          % (bucket_name, creds_path, file_path)
                raise Exception(err_msg)
            elif error_code == 404:
                err_msg = 'Bucket: "%s" does not exist; check spelling and try '\
                          'again' % bucket_name
                raise Exception(err_msg)
            else:
                err_msg = 'Unable to connect to bucket: "%s". Error message:\n%s'\
                          % (bucket_name, exc)
        except Exception as exc:
            err_msg = 'Unable to connect to bucket: "%s". Error message:\n%s'\
                      % (bucket_name, exc)
            raise Exception(err_msg)

    # Otherwise just return what was passed in
    else:
        local_path = file_path

    # Check image dimensionality
    img_nii = nib.load(local_path)
    if img_type == 'anat':
        if len(img_nii.shape) != 3:
            raise IOError('File: %s must be an anatomical image with 3 '\
                          'dimensions but %d dimensions found!' % (local_path,len(img_nii.shape)))
    elif img_type == 'func':
        if len(img_nii.shape) != 4:
            raise IOError('File: %s must be a functional image with 4 '\
                          'dimensions but %d dimensions found!' % (local_path,len(img_nii.shape)))

    # Return the local path
    return local_path

ignore_exception = False
img_type = func

Traceback: 
Traceback (most recent call last):
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 49, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1000, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/home/gose66/miniconda/envs/cpac/lib/python2.7/site-packages/nipype/interfaces/utility.py", line 499, in _run_interface
    out = function_handle(**args)
  File "<string>", line 18, in check_for_s3
AttributeError: 'NoneType' object has no attribute 'lower'
Interface Function failed to run.

**Comment by nimzodisaster** [comment]
I should have added that I am not trying to run this on s3. I am trying to run it locally.

**Comment by jpellman** [comment]
Hi @nimzodisaster 

This is a known issue with the current release of C-PAC (see https://github.com/FCP-INDI/C-PAC/issues/633).  It occurs due to the _scan_params_ key under _rest_ in the participant YAML being treated as a NifTI when it shouldn't be.  It should not affect preprocessing for any of the other NifTIs nested under _rest_.

**Comment by nimzodisaster** [comment]
By rest, do you mean func?
Here is my subject yaml for one subject. Should I just delete the 'scan_parameters: null' key pair?

- anat: /home/gose66/RestingState/DATA_ARCHIVE/PRIMARYSITES/MIND/1000-100/sess1/anat/mpragef.nii.gz
  creds_path: null
  func:
    funcf: /home/gose66/RestingState/DATA_ARCHIVE/PRIMARYSITES/MIND/1000-100/sess1/func/funcf.nii.gz
    scan_parameters: null
  subject_id: 1000-100
  unique_id: sess1

**Comment by jpellman** [comment]
Hi @nimzodisaster ,

Apologies- we recently changed the naming convention to read as _func_ rather than _rest_ and I'm still accustomed to the older convention.  What's happening is that C-PAC is trying to create a strategy treating _scan_params_ as a functional scan.  The execution of this individual strategy fails when it gets to _check_for_s3_, which is why you are seeing a crash file.  The other strategies do not fail since they are using NifTIs as input to _check_for_s3_.

**Comment by nimzodisaster** [comment]
Thanks John. Im not sure what you mean by 'strategy', but
it didn't just produce a crash file, it crashed/stopped the whole local
pipeline. Only after deleting the scan_param key did the pipeline seem to
run, at least as of when I left for home last night. I was not entering any
parameters by file, so it was null anyway.
-Joshua

On Jan 20, 2017 8:24 AM, "John Pellman" <notifications@github.com> wrote:

Hi @nimzodisaster <https://github.com/nimzodisaster> ,

Apologies- we recently changed the naming convention to read as *func*
rather than *rest* and I'm still accustomed to the older convention. What's
happening is that C-PAC is trying to create a strategy treating
*scan_params* as a functional scan. The execution of this individual
strategy fails when it gets to *check_for_s3*, which is why you are seeing
a crash file. The other strategies do not fail since they are using NifTIs
as input to *check_for_s3*.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FCP-INDI/C-PAC/issues/643#issuecomment-274114272>, or mute
the thread

**Comment by jpellman** [comment]
A 'strategy' refers to the particular combination of preprocessing options that are toggled on and off (see [here](http://fcp-indi.github.io/docs/user/pipeline_config.html#definitions)).  When C-PAC puts together the pipeline for execution, it generates many branching workflows based off the strategy used and other derivative files that would be generated after preprocessing.  The branch of the pipeline that attempts to run preprocessing on a 'null' value should fail, however other branches of the pipeline that are running on functional files should not fail.

When you say that the pipeline crashed/stopped do you mean that none of the other branches ran either (i.e., were there no files produced in the output/working directories)?  If so, this issue might be more problematic.

**Comment by nimzodisaster** [comment]
Thanks John for the clarification.
Yeah, I believe everything stopped. There were some files perhaps, but no
cpu usage and it hadn't ran long enough to complete. Unfortunately, I will
not be able to log on to my server today (a day full of meetings), so I'll
update again with a confirmation of what got done and did not get done.

Thanks again,
Joshua

**Comment by nimzodisaster** [comment]
I have a few new subjects to run through the pipeline again. I will try again leaving the scan_params key set to null to see if it produced files or not. Otherwise, when I deleted that key the pipeline seemed to run fine.

**Comment by nimzodisaster** [comment]
I was mistaken. The bug is indeed limited. The pipeline continued after the crash report.

**Comment by nimzodisaster** [comment]
Here was my confusion: Crash reports are generated, but the pipeline continues. However, eventually the terminal issues an error and stops. The reported error relates to the crashfile produced earlier. I can only conclude two different possibilities:
   1. The pipeline finished, and then CPAC reports that the a crash had occurred. 
or
   2. There is further processing needed after this point, but the bug is not allowing the pipeline to go forward. 

The first seems more likely since it seems many of the expected files have been produced.
