### ISSUE TITLE
Typo in formatted string in C-PAC group runner

### ISSUE THREAD

**Issue by jpellman** [FCP-INDI/C-PAC#647]
In the following formatted string, the second '%s' was mistyped as '\s':

https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/pipeline/cpac_group_runner.py#L140-L141

This causes a TypeError to be thrown when assigning the string to 'err'.

**Comment by sgiavasis** [comment]
Cleaning issues up- this has long been resolved.
