### ISSUE TITLE
subjectListName string insertion fails

### ISSUE THREAD

**Issue by mhlinder** [FCP-INDI/C-PAC#648]
I have a yaml file that contains the line

```
subjectListName : ['subj']
```

But, when I run `cpac_setup.py`, I get the following error:

```
For any errors or messages check the log file - /home/mlinder/research/extract_data_logs.log
Extraction Successfully Completed...Input Subjects_list for CPAC - /home/mlinder/research/CPAC_subject_list.yml
Subject list couldn't be read!
path:  /home/mlinder/research/CPAC_subject_list_['subj'].yml
```

The file `CPAC_subject_list_subj.yml` exists in the directory, but the string is improperly formatted.

How can I get around this?

Thanks!

**Comment by jpellman** [comment]
For the record, the offending line of code is [here](https://github.com/FCP-INDI/C-PAC/blob/603beb7b84243da5c881fea829796105e139c6cc/CPAC/utils/extract_data.py#L753).

To work around this, you can load your data configuration YAML in the C-PAC GUI and generate the subject list YAML from there.  Alternatively you should be able to run something like this following from a Python interpreter:
```

from CPAC.utils.build_sublist import build_sublist
from CPAC.utils.extract_data import generate_supplementary_files
build_sublist('/path/to/data/configuration/yaml')
generate_supplementary_files('[value of outputSubjectListLocation], [value of subjectListName])
```

**Comment by mhlinder** [comment]
Thank you! The GUI exactly meets my needs.
