### ISSUE TITLE
incompatible with numpy > 1.11

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#651]
The failure to typecast the result of nextpow2 on the following line:
https://github.com/FCP-INDI/C-PAC/blob/master/CPAC/nuisance/nuisance.py#L50

Results the exception: TypeError: 'numpy.float64' object cannot be interpreted as an index

Versions of numpy > 1.11 do not allow indexing with floating point numbers: https://github.com/rbgirshick/py-faster-rcnn/issues/481

For now this can be solved with downgrading number to 1.11, in the long term this should be fixed.

I would prefer replacing all of nuisance regression and filtering with a call to 3dTproject: https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dTproject.html

**Comment by sgiavasis** [comment]
This was resolved in #667 via @florisvanvugt .
