### ISSUE TITLE
Incomplete symlink directory for multi-option preproc pipeline

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#653]
In a pipeline **with** and **without** global regression strategies, symlinks were produced only for the preprocessed data **without** global regression.  However, output files were produced for global regression strategy, so seems limited to symlinking.

In version 1.0.1

**Comment by nimzodisaster** [comment]
This bug stands, is it still relevant to current version? Can close.

**Comment by anibalsolon** [comment]
I will take a look on that tomorrow! Have you tested in the last version?

**Comment by nimzodisaster** [comment]
v. 1.0.1 I'm not sure if it is relevant to the current version. So much has changed.

**Comment by nimzodisaster** [comment]
btw, I'm currently still on 1.0.1 because either all the bugs (that i know about) have been worked out or I've a work around for it. 

Some of the new features are tempting though, so I run it and submit bug reports.

**Comment by nimzodisaster** [comment]
Apparently I am slow to read you whole sentence. No I have not tested it out in the new versions, in part because I still haven't managed to get through a whole preprocessing run with the current version.

**Comment by nx10** [comment]
Outdated. Symlink directory does not exist anymore.
