### ISSUE TITLE
incompatible with jinja2 v 2.9.5

### ISSUE THREAD

**Issue by mhlinder** [FCP-INDI/C-PAC#656]
Hi,

A fresh install with jinja2 fetched from the conda server resulted in jinja2 v 2.9.5, which gave an error when handling `CPAC/resources/templates/cpac_runner.html`

Uninstalling this version of jinja2 and reinstalling with 2.7.2 (installed on a separate machine, and working) fixes the problem.

**Comment by sgiavasis** [comment]
Great- thank you.
