### ISSUE TITLE
I have only functional data. Is it possible to preprocess it?

### ISSUE THREAD

**Issue by isukrit** [FCP-INDI/C-PAC#658]
Hi, I only have functional scans for my subjects. I downloaded this data from ADNI and did not want to download anatomical data. I want to get functional connectivity matrices from this data. Is it possible to preprocess only functional data, without using anatomical data in C-PAC? Thanks!

**Comment by ccraddock** [comment]
I am very sorry, but for now, anatomical data is required for preprocessing using CPAC.
