### ISSUE TITLE
cpac_gui confusion

### ISSUE THREAD

**Issue by bth22** [FCP-INDI/C-PAC#663]
Hi,

I'm having difficulty defining filepaths to generate a subject list, and it's giving some contradictory error messages here.  I'll post images of the filepaths I'm using and the error messages.  I am trying both data formats, and each says that I am trying to use the other one.  In reality I'm trying to use BIDS.  CPAC_test is the folder with numbered subject folders, each has an 'anat' and 'func' subfolder, then for testing purposes just the one file that is referred to in the following images in the template fields.

<img width="816" alt="1" src="https://user-images.githubusercontent.com/28631917/27553669-de535f5c-5a79-11e7-88b6-0b9721391fa0.png">
<img width="817" alt="2" src="https://user-images.githubusercontent.com/28631917/27553673-e07a1f0a-5a79-11e7-9f79-25bdfe7fdf71.png">
<img width="821" alt="3" src="https://user-images.githubusercontent.com/28631917/27553676-e2082894-5a79-11e7-8081-e36e0c727759.png">

**Comment by sgiavasis** [comment]
Hi bth,

Try clearing the path template fields (while keeping BIDS selected and the BIDS Base Directory field populated) and try again?

**Comment by bth22** [comment]
Okay now I'm able to at least save the settings but it gives the error "Error importing CPAC. Unable to run extract data tool" when I click "Generate Subject Lists".  

From the terminal:
`aving /home/bth22/data_config_newlist.yaml
Gathering anatomical files...
2017-07-11 12:59:02,334 : Found 3 files!
170711-12:59:02,334 sublist_builder INFO:
	 Found 3 files!
Gathering functional files...
2017-07-11 12:59:02,366 : Found 3 files!
170711-12:59:02,366 sublist_builder INFO:
	 Found 3 files!
2017-07-11 12:59:02,397 : Filtering anatomical files...
170711-12:59:02,397 sublist_builder INFO:
	 Filtering anatomical files...
2017-07-11 12:59:02,399 : Not filtering out any potential sites...
170711-12:59:02,399 sublist_builder INFO:
	 Not filtering out any potential sites...
2017-07-11 12:59:02,402 : Filtered down to 3 files
170711-12:59:02,402 sublist_builder INFO:
	 Filtered down to 3 files
Filtered down to 3 anatomical files
2017-07-11 12:59:02,406 : Not filtering out any potential sites...
170711-12:59:02,406 sublist_builder INFO:
	 Not filtering out any potential sites...
2017-07-11 12:59:02,444 : Filtered down to 3 files
170711-12:59:02,444 sublist_builder INFO:
	 Filtered down to 3 files
Error importing CPAC
cannot import name fsopendir`

**Comment by bth22** [comment]
Any ideas?

**Comment by sgiavasis** [comment]
Hi bth22,

You most likely have a more recent version of the Python package fs. This can be checked by either going into Python and entering:

```
import fs
fs.__version__
```
..or, if you installed via pip, using ```pip list```. The latest version of fs is 2.0.4.

I think what is happening is that fs's later versions have changed some of its interface, and we have not ported to this yet. Try temporarily downgrading your fs install to 0.5.4. This can be done easily via:

`pip install fs==0.5.4`

Let me know if this temporary workaround works.

Best,
Steve

**Comment by bth22** [comment]
Okay, got it!  After downgrading and using the custom file formats I got it to at least make the list.  Thank you.
