### ISSUE TITLE
bandpass filtering

### ISSUE THREAD

**Issue by florisvanvugt** [FCP-INDI/C-PAC#665]
Hi, I am running a fairly standard pipeline and it crashes during the bandpass filtering. I think this is a type casting issue.

In my case, the following patch solved the issue:

```
diff --git a/CPAC/nuisance/nuisance.py b/CPAC/nuisance/nuisance.py
index dfa7de6..84ffc7f 100644
--- a/CPAC/nuisance/nuisance.py
+++ b/CPAC/nuisance/nuisance.py
@@ -42,7 +42,7 @@ def bandpass_voxels(realigned_file, bandpass_freqs, sample_period = None):
         
         def nextpow2(n):
             x = np.log2(n)
-            return 2**np.ceil(x)
+            return int(2**np.ceil(x))
         
         sample_freq = 1./sample_period
         sample_length = data.shape[0]
```

[crash-20170705-133941-floris-frequency_filter_0.aI.a0.b0.c0-3670d04a-dd56-46ea-b356-38026c747a22.pklz.txt](https://github.com/FCP-INDI/C-PAC/files/1126029/crash-20170705-133941-floris-frequency_filter_0.aI.a0.b0.c0-3670d04a-dd56-46ea-b356-38026c747a22.pklz.txt)

**Comment by sgiavasis** [comment]
Hi florisvangut,

Yes, I believe this is an issue that pops up depending on the Numpy version. Thank you for bringing this up/providing a solution.
