### ISSUE TITLE
pip install INDI-Tools 

### ISSUE THREAD

**Issue by ilkayisik** [FCP-INDI/C-PAC#669]
I was following the installation page (http://fcp-indi.github.io/docs/user/install.html) to install CPAC.
In the last step where I was checking the cpac installation I got an error related to indi-tools, stating that it is not installed even though I ran the previous command and installed all the Python dependencies within a Miniconda environment. 
Later, I ran pip install INDI-Tools with an upper-case T (INDI-Tools instead of INDI-tools). This installed indi-Tools successfully.

**Comment by sgiavasis** [comment]
Thanks! We'll update the documentation to be more explicit about this.
