### ISSUE TITLE
setting up a subject list

### ISSUE THREAD

**Issue by florisvanvugt** [FCP-INDI/C-PAC#670]
I seem to have trouble setting up a subject list.

I followed the instructions to set up a subject list `data_config.yml` (see below for the listing of the file). Then I try to run:
```
cpac_setup.py data_config.yml
```
And I get this error:
```
ERROR: input 'data_config.yml' is not a python file (*.py)
```
However, when I rename my yaml to a .py file then it starts to process it (but it runs into other errors it seems). I created a pull request on my fork of this repo that fixes this issue.

**Comment by florisvanvugt** [comment]
Also, the example subject list configuration file ( https://raw.githubusercontent.com/FCP-INDI/C-PAC/master/configs/data_config.yml ) raises an error, because subjectListName is not defined in it.

**Comment by sgiavasis** [comment]
cpac_setup.py has been updated to work with the latest changes- this will be in 1.0.1b.
