### ISSUE TITLE
Using a custom CSV for contrasts

### ISSUE THREAD

**Issue by florisvanvugt** [FCP-INDI/C-PAC#675]
Hi, I am trying to use a custom CSV to set up contrasts. C-PAC complains that the number of columns in the contrasts file does not match the number of columns in the design matrix.

I used the following design formula:
```
design_formula :  age + age_onset + hours_lifetime
```

I then used the following custom contrasts CSV file:
```
Contrasts,age,age_onset,hours_lifetime
age+,1,0,0
age-,-1,0,0
age_onset+,0,1,0
age_onset-,0,-1,0
hours_lifetime+,0,0,1
hours_lifetime-,0,0,-1
```

However, when I run this group analysis, C-PAC complains
```
[!] CPAC says: The number of EVs in your model design matrix (found in the age_age_onset.mat file) does not match the number of EVs (columns) in your custom contrasts matrix CSV file.

Custom contrasts matrix file: contrasts_ageonset.csv

Number of EVs in design matrix: 3
Number of EVs in contrasts file: 4

The column labels in the design matrix should match those in your contrasts .CSV file.
Column labels in design matrix:
['age', 'age_onset', 'hours_lifetime']
```

If I disable this error checking (by adding one to the number of contrasts in the contrasts file), then FSL chokes further down the line:

```
Standard error:
Num tcontrast cols  = 4, design matrix cols = 3
```

The problem lies in that C-PAC created a design matrix **without** an intercept, but a contrasts file **with** an intercept. 
Design matrix:
```
/NumWaves	3
/NumPoints	38
/PPheights	1.00000e+00	1.00000e+00	1.00000e+00


age	age_onset	hours_lifetime	

/Matrix
3.07895e+00	-9.73684e-01	1.60197e+03
1.07895e+00	-4.73684e-01	5.04797e+03
-1.92105e+00	-1.47368e+00	4.17597e+03
-9.21053e-01	5.52632e+00	-1.75203e+03
-4.92105e+00	-1.47368e+00	1.21840e+04
-9.21053e-01	-2.47368e+00	9.76597e+03
... etc etc etc
```

Contrasts file:
```
/ContrastName1 	age+
/ContrastName2 	age-
/ContrastName3 	age_onset+
/ContrastName4 	age_onset-
/ContrastName5 	hours_lifetime+
/ContrastName6 	hours_lifetime-
/NumWaves	4
/NumContrasts	6
/PPheights	1.00000e+00	1.00000e+00	1.00000e+00	1.00000e+00	1.00000e+00	1.00000e+00
/RequiredEffect	1.00000e+00	1.00000e+00	1.00000e+00	1.00000e+00	1.00000e+00	1.00000e+00


Intercept	age	age_onset	hours_lifetime	

/Matrix
0.00000e+00	1.00000e+00	0.00000e+00	0.00000e+00
0.00000e+00	-1.00000e+00	0.00000e+00	0.00000e+00
0.00000e+00	0.00000e+00	1.00000e+00	0.00000e+00
0.00000e+00	0.00000e+00	-1.00000e+00	0.00000e+00
0.00000e+00	0.00000e+00	0.00000e+00	1.00000e+00
0.00000e+00	0.00000e+00	0.00000e+00	-1.00000e+00
```

**Comment by florisvanvugt** [comment]
I created a fix for this problem at least for my case: https://github.com/florisvanvugt/C-PAC/commit/6e8855ba0638401ab8b574fe0687ed2cd695338d

This fix basically removes the intercept term from the contrasts matrix, so that now the contrasts matrix and the design matrix are compatible. However, since I am not sure how the developers imagined when the intercept term would be added to the design matrix, please have a look before taking over that fix.

**Comment by nimzodisaster** [comment]
Great. I was having this issue also.
-Josh

-
Joshua Lee, Ph.D.
Post-Doctoral Researcher
MIND Institute
University of California, Davis
916-703-0360

**Comment by nimzodisaster** [comment]
Not a developer here, but the intercept is optional. If desired, then it must be explicitly added to the model formula in the yaml.

**Comment by sgiavasis** [comment]
Hi Floris,

Thank you for this. I have not seen this error happen, though it has happened to others. I will need to reproduce it first.

@nimzodisaster , has this gotten you past the issue?
