### ISSUE TITLE
Incorrect Derivatives List in GUI Documentation in 1.0.1

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#684]
As discussed [here](https://groups.google.com/forum/#!topic/cpax_forum/hk7ZLqjGv4E),
the list of derivatives [here](http://fcp-indi.github.io/docs/user/group_analysis.html) and within the CPAC GUI documentation are incorrect for version 1.0.1

I believe this is a corrected list of derivatives:
derivative_list :  ['alff_to_standard_zstd', 'alff_to_standard_smooth_zstd', 'falff_to_standard_zstd', 'falff_to_standard_smooth_zstd', 'reho_to_standard_zstd', 'reho_to_standard_smooth_zstd', 'sca_roi_files_to_standard_fisher_zstd', 'sca_roi_files_to_standard_smooth_fisher_zstd', 'dr_tempreg_maps_zstat_files_to_standard', 'dr_tempreg_maps_zstat_files_to_standard_smooth', 'sca_tempreg_maps_zstat_files', 'sca_tempreg_maps_zstat_files_smooth', 'centrality_outputs_zstd', 'centrality_outputs_smoothed_zstd', 'vmhc_fisher_zstd_zstat_map']

**Comment by sgiavasis** [comment]
@nimzodisaster Thanks! Currently in the process of updating all documentation.
