### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kyleliang919** [FCP-INDI/C-PAC#685]
Hi,there
  I am a research assistant from Decision Neuroscience Lab, Beckman Insititue, UIUC. I have been trying to install CPAC on the linux Ubuntu 14.04(a brand new system without any package preinstalled, I presume that there will not be any version problem). After running the cpac_install.sh, I still can not  import the CPAC in python. And that shell script did run sucessfully. 

Here is the prompt:
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import CPAC
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named CPAC
Here is the cpac.log:
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency cmake
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency git
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency graphviz
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency graphviz-dev
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency gsl-bin
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency libexpat1-dev
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency libgiftiio-dev
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency libglib2.0-dev
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency libglu1-mesa-dev
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency libjpeg-progs
[ Tue Aug  8 12:05:44 CDT 2017 ] : Missing system dependency libxml2-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxext-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxft-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxi-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxmu-headers
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxmu-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxpm-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxslt1-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency mesa-common-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency mesa-utils
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency netpbm
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency build-essential
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency xvfb
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency tcsh
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency zlib1g-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency m4
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libmotif-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libxp-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Missing system dependency libgsl0-dev
[ Tue Aug  8 12:05:45 CDT 2017 ] : Python is not installed, need to install all Python dependencies.
[ Tue Aug  8 12:08:30 CDT 2017 ] : apt-get Installed C-PAC system dependency cmake git graphviz graphviz-dev gsl-bin libexpat1-dev libgiftiio-dev libglib2.0-dev libglu1-mesa-dev libjpeg-progs libxml2-dev libxext-dev libxft-dev libxi-dev libxmu-headers libxmu-dev libxpm-dev libxslt1-dev mesa-common-dev mesa-utils netpbm build-essential xvfb tcsh zlib1g-dev m4 libmotif-dev libxp-dev libgsl0-dev
[ Tue Aug  8 12:08:31 CDT 2017 ] : C-PAC system dependencies succesfully installed.
[ Tue Aug  8 12:08:31 CDT 2017 ] Installing miniconda!
[ Tue Aug  8 12:13:53 CDT 2017 ] : FSLDIR must be defined for C-PAC image resources to install.

**Comment by sgiavasis** [comment]
Hi @kyleliang919,

Sorry this hasn't been addressed- are you still having issues? Please let us know and we can help.

Best,
Steve

**Comment by kyleliang919** [comment]
Hi, Steve
 I reverted C-PAC back to the previous version and it was working.  I remember someone told me before that it was due to a conflict between that version and one of the dependency.  I am going to close the issue here.
Thanks,
Kyle
