### ISSUE TITLE
Unclear error in cpac_gui

### ISSUE THREAD

**Issue by bth22** [FCP-INDI/C-PAC#688]
So I've gotten things to run to the point where I am able to define a pipeline and subject list, but when I try to run it looks like maybe I have the wrong version of some module perhaps.  Will post the error below, this is when I'm trying to run the individual analysis.

170815-15:14:58,373 workflow INFO:
	 VERSION: CPAC 1.0.1

Setting maximum number of cores per participant to 1
Setting number of participants at once to 1
Setting OMP_NUM_THREADS to 1
Setting MKL_NUM_THREADS to 1
Setting ANTS/ITK thread usage to 1

Maximum potential number of cores that might be used during this run: 1

++ 3dcalc: AFNI version=AFNI_17.1.08 (Jun  1 2017) [64-bit]
++ Authored by: A cast of thousands
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/pipeline/cpac_pipeline.py", line 414, in prep_workflow
    anat_preproc = create_anat_preproc(already_skullstripped).clone('anat_preproc_%d' % num_strat)
  File "/usr/local/lib/python2.7/dist-packages/CPAC/anat_preproc/anat_preproc.py", line 86, in create_anat_preproc
    anat_deoblique = pe.Node(interface=preprocess.Refit(),
AttributeError: 'module' object has no attribute 'Refit'

**Comment by sgiavasis** [comment]
Hi bth22,

What versions of Nipype and CPAC are you running?

**Comment by sgiavasis** [comment]
Hello @bth22,

Are you still having issues? Please let us know, and we can help.

Best,
Steve
