### ISSUE TITLE
Cannot install CPAC (wxPython install issues)

### ISSUE THREAD

**Issue by kevnmr** [FCP-INDI/C-PAC#690]
Hi

I currently have anaconda 4.3.23 nipype 0.13.1.  I get this error when doing a import CPAC in ipython:

/home/kevin/anaconda2/lib/python2.7/site-packages/matplotlib/**init**.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
CPAC was imported and can be used, but wxPython was not found. In order to use the GUI, wxPython must be installed.
Error: No module named combo

When running cpac_gui i get this error: 

/home/kevin/anaconda2/lib/python2.7/site-packages/matplotlib/**init**.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
CPAC was imported and can be used, but wxPython was not found. In order to use the GUI, wxPython must be installed.
Error: No module named combo
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Traceback (most recent call last):
  File "/home/kevin/anaconda2/bin/cpac_gui", line 5, in <module>
    CPAC.GUI.run()
  File "/home/kevin/anaconda2/lib/python2.7/site-packages/CPAC/GUI/mainUI.py", line 14, in run
    ListBox(None, -1, 'Configure & Run CPAC')
NameError: global name 'ListBox' is not defined

I've tried downgrading CPAC to 0.3xxx. Gave me another utils error.

Please help.

Kevin

**Comment by anibalsolon** [comment]
Hi Kevin! Sorry to hear that you are having trouble.

Have you tried to install wxpython?
https://wiki.wxpython.org/How%20to%20install%20wxPython

Since you are using Anaconda, I believe you can install using: ```conda install -c anaconda wxpython```

**Comment by sgiavasis** [comment]
Hello @kevnmr -

Have you tried @anibalsolon 's suggestion? Please let me know if you are still having trouble.

Thanks!
Steve

**Comment by sgiavasis** [comment]
Hi kevnmr,

Glad to hear you're running, but I will take note of this and see if we can resolve the original issue in the near future.

**Comment by sgiavasis** [comment]
New GUI in place, closing this issue.
