### ISSUE TITLE
Integrate new Nuisance changes into GUI and pipeline config structure

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#693]
Major revisions to nuisance regression have been introduced in 1.0.2. A new sub-window is required in the UI for configuring nuisance regression.

* [ ] Create new sub-window for nuisance regression strategies
* [ ] Create new "Edit" button in GUI and tie it into the sub-window
* [ ] Write out new nuisance strategy dictionary to pipeline config, and load it back in properly
* [ ] Update pipeline configuration YAML file template with new format, with examples

**Comment by sgiavasis** [comment]
This has been changed to a long-scale project, and introducing only de-spiking for now (issue #695).

**Comment by mnarayan** [comment]
Any chance nuisance regression using custom confounds (e.g. many useful regressors are created from fmriprep) can be used/incorporated into this workflow?

**Comment by sgiavasis** [comment]
Hi @mnarayan,

This is a long time coming, though we are now working on integrating that functionality in the upcoming version 1.4.2 (issue #949).

Best,
Steve

**Comment by sgiavasis** [comment]
Also, the new nuisance changes have been implemented in v1.4.1.
