### ISSUE TITLE
Pipeline: Field Map Correction workflow

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#697]
Start posting resources here. This thread is for shaping out all the options and ideas and documenting it here. A few necessary things:

- [x] Rough flowchart of how to run it, which tools are best, if we'll offer alternatives
- [x] How to validate it works, get it working by hand through terminal first
- [ ] Configurable options, if any

**Comment by sgiavasis** [comment]
User Guide for FUGUE:
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE

**Comment by nrajamani3** [comment]
SPM example dataset for testing out field map correction:
http://www.fil.ion.ucl.ac.uk/spm/data/fieldmap/

**Comment by sgiavasis** [comment]
Per the FUGUE guide, can run fsl_prepare_fieldmap script for field maps from Siemens scanners. It strongly urges having a very tight skull-stripping, even at the expense of losing brain voxels. Maybe consider having a separate skull-stripping that is more stringent, but doesn't feed this version into the rest of the pipeline?

**Comment by nrajamani3** [comment]
You can also perform two brain extractions: Both can be integrated into the pipeline, but just prior to feeding in to the field map correction pipeline, a second (more tighter) brain extraction could be performed?
