### ISSUE TITLE
Error with nipype

### ISSUE THREAD

**Issue by mk2299** [FCP-INDI/C-PAC#706]
Hi,

I recently installed CPAC and was trying to run a preprocessing pipeline. However, I am getting this error with nipype: 
![screen shot 2017-11-30 at 1 52 24 am](https://user-images.githubusercontent.com/33186673/33417864-2c5e1b0c-d571-11e7-879a-5da855e95540.png)
Any workarounds around this? Would really appreciate any feedback as I've been stuck on this for a while.

**Comment by sgiavasis** [comment]
Hi @mk2299 ,

Let's try to get you running- which versions of Nipype and CPAC are you using?

**Comment by mk2299** [comment]
Thanks for your prompt response! I'm using CPAC v1.0.2 and nipype version 0.13.1. I also get the following warning and am wondering if the error might be cause by this?

Warning: Datasink cannot create the strategy and pipeline graph, dot or/and pygraphvix is not installed. 

Also, I still get 'Pipeline building completed' before. 
<img width="538" alt="screen shot 2017-11-30 at 1 57 44 pm" src="https://user-images.githubusercontent.com/33186673/33449376-91cf2156-d5d6-11e7-9f2b-2fc66e3b8ced.png">

**Comment by mk2299** [comment]
Hi @sgiavasis, any ideas? Thanks!!

**Comment by nimzodisaster** [comment]
re: Datasink cannot create the strategy and pipeline graph, dot or/and
pygraphvix is not installed.
I've been getting that since 0.39 :)

-Joshua

**Comment by mk2299** [comment]
Hi @nimzodisaster , Does that mean it is nothing to worry about? And the error message is maybe caused by something else? 
Thanks! :)

**Comment by nimzodisaster** [comment]
Yeah, I'm pretty sure it is just failing to make an image (jpeg/png) of a
graph of the pipeline.

**Comment by ccraddock** [comment]
Yes that Warning is just a statement that it will not create an image of the pipeline execution graph. Maybe we should rephrase it so that it is more clear that it can be ignored, or that it will not impact pipeline execution.

**Comment by sgiavasis** [comment]
@ccraddock good idea, created an issue for it- #715

@mk2299, as for the original error-
1. Does this stop the pipeline from continuing?
2. Does it produce any Nipype crash files?
3. Approximately where/when in the pipeline does this occur? Do you have the pipeline log files?

**Comment by sgiavasis** [comment]
Hello @mk2299,

Are you still having issues?

Best,
Steve
