### ISSUE TITLE
Why does SCA require runVoxelTimeSeries?

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#734]
https://github.com/FCP-INDI/C-PAC/blob/547ae572146fe0744a8c363418eab5326aa5b945/CPAC/pipeline/cpac_pipeline.py#L3202

This is counterintuitive given that runVoxelTimeseries is described as: "Extract the time series of all voxels within one or more ROIs/seeds", which is different from the standard SCA procedure using a single mean TS per R0I.

**Comment by ccraddock** [comment]
actually looks like runVoxelTimeseries was  deprecated, but somehow didn't get removed from the logic at line 3202

**Comment by sgiavasis** [comment]
This is all commented out, it's just not obvious at first glance. It should no longer be there in the first place- removing it in the dev branch.
