### ISSUE TITLE
How to install C-PAC on Centos7?

### ISSUE THREAD

**Issue by Larry-Lai** [FCP-INDI/C-PAC#747]
Dear experts

How to install C-PAC on Centos 7?

Thanks for considering my request.

Cheers
Larry

**Comment by nrajamani3** [comment]
Hi Larry,
Have you reviewed the documentation? You can find it here. https://fcp-indi.github.io/docs/user/install.html. While there are no specific instructions for centOS, you could try by replacing the "apt-get" in linux with "yum install". To install other dependencies: 
1. For python packages: In case you do not already have "pip" you can download it, as "yum install python-pip". Other instructions are given here: https://www.godaddy.com/help/how-to-install-python-pip-on-centos-12367
2. Installing AFNI: https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/install_instructs/steps_linux_Fed_RH.html
3. Installing FSL: Follow the same installation script for linux. You can refer to this: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Linux for more details
4. For C3D use this http://sourceforge.net/projects/c3d/ to download
5. For installing ANTS you can follow the "for other platforms" instructions given on the C-PAC installation guide.
6. The rest is pulled from git hub itself so you can follow the rest of the instructions on the installation guide.
Please let us know if you have any specific questions!

**Comment by Larry-Lai** [comment]
Fabulous, thanks for your help.

I'll post the results later.

Best wishes
Larry
