### ISSUE TITLE
Version of nipype found in ... does not contain the MultiProc plugin.

### ISSUE THREAD

**Issue by oesteban** [FCP-INDI/C-PAC#749]
Forwarded from nipy/nipype#2402

Nipype API has changed as regards the resource management. We'll be very happy to assist on how to upgrade to the latest nipype version. Other than that, I forward the question of a user from the nipype repo for support here:

> I am currently using the latest version of nipype and ran into the following error message. Any ideas why?
> 
> Version of nipype found in /usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype does not contain the MultiProc plugin. Please check installation is the most up-to-date or download and install the FCP-INDI nipype repo at https:/github.com/fcp-indi/nipype.
> Error: No module named callback_log
> 180125-12:14:49,288 workflow INFO:
> Workflow resting_preproc_50002_followup_1 settings: ['check', 'execution', 'logging', 'monitoring']
> Could not complete cpac run for subject: 50002!
> Error: Execution graph does not have a unique set of node names. Please rerun the workflow
> 
> Any help would be really appreciated!

**Comment by sgiavasis** [comment]
Hi @oesteban ,

Are these API changes starting in the latest version 1.0?
https://github.com/nipy/nipype/releases/tag/v1.0.0

(Congrats on the release, by the way).

Steve

**Comment by oesteban** [comment]
As of nipype-0.14.0 (https://github.com/nipy/nipype/pull/2200)

**Comment by anibalsolon** [comment]
Old one- Nipype upgraded and unified to the original one :pray: Thanks for relaying to us, @oesteban !
