### ISSUE TITLE
Pipeline: only iterable inputs should be in a list in pipeline config

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#758]
Example from pipeline config:

`# Disables skull-stripping on the anatomical inputs if they are already skull-stripped outside of C-PAC. Set this to On if your input images are already skull-stripped.
already_skullstripped :  [0]`

This option is not iterable, i.e. cannot run both options at once to have the pipeline fork, so it doesn't need to be written out as a list.

* [ ] cpac_pipeline.py changes
* [ ] pipeline config template update
* [ ] pipeline config reader/writer update

**Comment by sgiavasis** [comment]
Pipeline config template will also have to be updated.

**Comment by anibalsolon** [comment]
Would be good to have a pipeline normalization, to handle old pipelines that contain lists.

**Comment by sgiavasis** [comment]
This is handled in v1.8.
