### ISSUE TITLE
installation problem libgl1-mesa-dri

### ISSUE THREAD

**Issue by ESA2018** [FCP-INDI/C-PAC#775]
Hi all ,

New to CPAC, I'm running into a problem when installing the system-level dependencies, in particular libgl1-mesa-dri. This is the error generated by the cpac_install.sh script, and also when I try to install it individually:

The following packages have unmet dependencies:
 gnome-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

My system is a fresh install of Ubuntu 14.04.5 LTS (trusty). 
I would really appreciate your help. Many thanks in advance

**Comment by anibalsolon** [comment]
Hi @ESA2018 

Have you tried to install `libcheese-gtk23` ?

 `sudo apt-get install libcheese-gtk23`

It looks like a problem from previous packages installations since C-PAC does not use `libcheese-gtk23` nor Gnome and Unity Control Centers.

**Comment by ESA2018** [comment]
Hi, 
Thank you for the response Anibal. I tried indeed and it returns that libcheese-gtk23 is already installed and the newest version. 
No particular installs in the system so far though. The system is fairly fresh besides anaconda2.

**Comment by nrajamani3** [comment]
Hi,
I would suggest you to try two methods:
If it is already installed you could try:
sudo apt-get update. 
If that doesn't work, then you can try to create a dynamic link to your libcheese-gtk23 by first locating where the lib cheese-gtk23 library is found in your system and then using "ldconfig -n /path/to/lib"
Please let us know if you still have issues!
Thanks!

**Comment by anibalsolon** [comment]
I am closing this issue because it has been inactive for a few months.
Please, open a new issue if you face new problems or have questions!
