### ISSUE TITLE
MDMR: UX (CLI, GUI, ..)

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#795]
* [ ] Set up easy-to-use CLI for MDMR
* [ ] Create GUI interface as well, preferably calling same interface objects as CLI
* [ ] Establish how/where the outputs will be written

Main inputs to MDMR:

* Preprocessed functional timeseries (NIFTI) in standard space
* Mask of ROIs (NIFTI)
* Regressors (as a CSV/TSV file)
* Which regressors from that file (selection)
* Num permutations

Main outputs:

* Volumes of estimated F-values
* Volumes of estimated p-values

**Comment by anibalsolon** [comment]
User can provide a .csv / .tsv as regressors
