### ISSUE TITLE
Error: wxPython must be installed

### ISSUE THREAD

**Issue by Turius** [FCP-INDI/C-PAC#801]
I have the following error and can not use CPAC gui:

> conda install wxpython
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/turius/.conda/envs/cpac:

The following NEW packages will be INSTALLED:

```
wxpython: 3.0.0.0-py27_2 (soft-link)
```

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |##################################################| 100%
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import CPAC
CPAC was imported and can be used, but wxPython was not found. In order to use the GUI, wxPython must be installed.
Error: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

**Comment by sgiavasis** [comment]
Hello @Turius,

We are phasing out the old GUI that relies on wxPython. A new GUI is available now- more details can be found here:
http://fcp-indi.github.io/docs/user/new_gui.html
