### ISSUE TITLE
Pipeline Config: Populate missing fields with defaults?

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#809]
@nrajamani3 @anibalsolon @ccraddock 

The pipeline config is starting to get larger. Making sure every field is populated before you can run (even if it's only with "None" or "Off" or default vals) may be too onerous for users who want to get running, but can't just toss in the default pipeline because they still want to modify, say, 30% of it or something. Also, if you don't provide something like "runSCA", why not default it to Off instead of having C-PAC yell at the user and halt the pipeline execution?

The defaults could possibly be taken from here:
https://github.com/BIDS-Apps/CPAC/blob/master/default_pipeline.yaml
(but without all the switches being On, for example)

Would like to hear thoughts/reservations/potential complications. @anibalsolon mentioned concerns over version changes, which led to issue #808.

**Comment by anibalsolon** [comment]
As an implementation aspect, we can actually read the `default_pipeline.yaml` and merge with the user-provided pipeline, so default values are consolidated in this file.

**Comment by sgiavasis** [comment]
Yes, perfect- keep everything in one place.

**Comment by ccraddock** [comment]
This is sort of how the bids app runs already. I think it is a good idea. Read default into dict, read custom, update dict from custom.

**Comment by sgiavasis** [comment]
This is now a feature via pipeline imports in v1.8.
