### ISSUE TITLE
update wxPython to 4.0.2

### ISSUE THREAD

**Issue by nrajamani3** [FCP-INDI/C-PAC#811]
The current version we are working with is 3.0.0, which is no longer available as a pip package and hence support for it is also limited. The update will involve possibly:(this is a vague description, will clear up as we go forward)

* Making wxPython installation easier - this bug was fixed in version 4.0.1a - the package is more self contained, can be downloaded into virtual machines, etc. This also means better error management with python 2.7 and python 3 packages 
* Changing control boxes, new wrappers introduced, etc : We could work on the custom_control.py script to add the new wrappers: NumberEntry dialog box, ListEntry box, new and corrected  INT_CNTRL box, etc
* This would also help the greater effort of making an advanced  tab and a default tab where we display options. There is a new and improved destroy dialog box (with the selection of a particular option, it will be able to make a new option appear)
--will continue to update

**Comment by anibalsolon** [comment]
Moving to the new GUI.
