### ISSUE TITLE
Different centrality indices generate the same z_score outfile name

### ISSUE THREAD

**Issue by haililihai** [FCP-INDI/C-PAC#817]
Different centrality indices (degree/eigenvector/lfcd, binarized/weighted) generate the same z_score outfile name.

https://github.com/FCP-INDI/C-PAC/blob/cbc5ce8767c42f7b800583acefd09c9c19afff12/CPAC/pipeline/cpac_pipeline.py#L4200

https://github.com/FCP-INDI/C-PAC/blob/250a1f4a3752e110c18259f5cc7a43e07588a657/CPAC/utils/utils.py#L260

**Comment by sgiavasis** [comment]
Hello @haililihai,

Thank you for posting feedback. This issue shouldn't occur in the current release (v1.2.0) currently on Master- could you please give that a try and confirm?

Thank you!
Steve

**Comment by sgiavasis** [comment]
Closing this issue- please feel free to re-open if needed!

Best,
Steve
