### ISSUE TITLE
Docker run.py does not generate a correct data config file

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#824]
here is an example of the incorrectly generated data config file:

* anat: s3://fcp-indi/data/Projects/FCON1000/Cambridge_Buckner/sourcedata/sub-04270/anat/sub-04270_T1w.nii.gz
  creds_path: null
  func: {task-rest: 's3://fcp-indi/data/Projects/FCON1000/Cambridge_Buckner/sourcedata/sub-04270/func/sub-04270_task-rest_bold.nii.gz'}
  site_id: site-none
  subject_id: sub-04270
  unique_id: ses-1

where it should be

* anat: s3://fcp-indi/data/Projects/FCON1000/Cambridge_Buckner/sourcedata/sub-04270/anat/sub-04270_T1w.nii.gz
  creds_path: null
  func: {rest: {scan: 's3://fcp-indi/data/Projects/FCON1000/Cambridge_Buckner/sourcedata/sub-04270/func/sub-04270_task-rest_bold.nii.gz'}}
  site_id: site-none
  subject_id: sub-04270
  unique_id: ses-1

**Comment by anibalsolon** [comment]
Hi @ccraddock 

It is fixed in the new release (v1.4.1) !

Let us know if it works now for you.
