### ISSUE TITLE
error handling 'anon' s3 bucket access

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#826]
When no AWS credentials are provided, the container run.py can list the bucket to create a config file, but when the pipeline attempts to download the data an access denied error is thrown. It looks as though the pipeline is interpreting the 'None' in the aws_creds slots of the data config file is interpreted as the filename of the aws access keys and not None. 

Perhaps we could use 'Anon' to indicate the desire for an anonymous connection to S3.

**Comment by anibalsolon** [comment]
Fixed for the 1.4.3 release.
