### ISSUE TITLE
CPAC gets stuck

### ISSUE THREAD

**Issue by vascosa** [FCP-INDI/C-PAC#832]
I created a pipeline and tested the configuration successfully.  
The pipeline runs fine up to registration:

Running: flirt -in /media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/func_preproc_automask_0/_scan_rest/func_normalize/sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_maths.nii.gz -ref /media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/seg_preproc_0/CSF/CSF_mask/segment_seg_0_maths.nii.gz -out sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_maths_flirt.nii.gz -omat sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_maths_flirt.mat -applyisoxfm 2 -init /media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/func_to_anat_FLIRT_0/_scan_rest/linear_func_to_anat/sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_tstat_flirt.mat

180830-12:47:34,528 workflow INFO:

 [Job finished] jobname: func_to_2mm_flirt_applyxfm.c0 jobid: 122

After FLIRT finished, it gets stuck and does not start the next job, which I believe should be gen_motion_stats. Any clues as to why this might be happening?

**Comment by anibalsolon** [comment]
Hi @vascosa ,

FLIRT is an intense process, which is known to take some time depending on the image resolution. You can run the command on your terminal, to check if it just taking much time or if it is a C-PAC issue:

```flirt -in /media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/func_preproc_automask_0/_scan_rest/func_normalize/sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_maths.nii.gz -ref /media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/seg_preproc_0/CSF/CSF_mask/segment_seg_0_maths.nii.gz -out sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_maths_flirt.nii.gz -omat sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_maths_flirt.mat -applyisoxfm 2 -init /media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/func_to_anat_FLIRT_0/_scan_rest/linear_func_to_anat/sub-10171_task-rest_bold_calc_tshift_resample_volreg_calc_tstat_flirt.mat```

could you please inform us how much time is it taking?

**Comment by vascosa** [comment]
Hi,
I could not run the command because I had already deleted the working files. I tried to recreate the issue but this time did not get as far as before.

What had me confused is that it says job finished. I have tried running it three more times and get stuck at different places. I have attached 3 logs so you can see what I'm saying. For instance, on test 3, it got to a write_log job with id93, and then didn't start the next job (I waited about 30 minutes before breaking it).


[test3.log](https://github.com/FCP-INDI/C-PAC/files/2340562/test3.log)
[test1.log](https://github.com/FCP-INDI/C-PAC/files/2340563/test1.log)
[test2.log](https://github.com/FCP-INDI/C-PAC/files/2340564/test2.log)


Let me know what you think.

**Comment by vascosa** [comment]
Hello again,

I was able to replicate the issue and run the pipeline up to func_to_2mm_flirt_applyxfm.c0. I ran the flirt command outside of CPAC and it took 67 seconds. Again, I've attached the log so you can see where it stopped.

[test4.log](https://github.com/FCP-INDI/C-PAC/files/2341345/test4.log)

**Comment by sgiavasis** [comment]
Hi @vascosa,

So running FLIRT manually outside of C-PAC worked, right?

Can you see if there is a "report" folder containing a "report.rst" file in this directory:
`/media/sf_shared/CPAC_test/Working/resting_preproc_10171_ses-1/func_to_anat_FLIRT_0/_scan_rest/linear_func_to_anat`

If so, could you post the contents of that file?

Thank you,
Steve

**Comment by sgiavasis** [comment]
Closing this issue. If the issue persists, please feel free to contact us.
