### ISSUE TITLE
Prevents CPAC Installation: ImportError: libgfortran.so.1: cannot open

### ISSUE THREAD

**Issue by nimzodisaster** [FCP-INDI/C-PAC#839]
CPAC installer having an issue with a missing shared object

    $ python setup.py install
    Traceback (most recent call last):
      File "setup.py", line 27, in <module>
        from build_helpers import INFO_VARS
      File "/home/jlee38/Downloads/FCP-INDI-C-PAC-a390456/build_helpers.py", line 28, in <module>
        from numpy.distutils.misc_util import appendpath
      File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
        from . import add_newdocs
      File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
        from numpy.lib import add_newdoc
      File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
        from .polynomial import *
      File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
        from numpy.linalg import eigvals, lstsq, inv
      File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
        from .linalg import *
      File "/home/jlee38/miniconda/envs/cpac/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
        from numpy.linalg import lapack_lite, _umath_linalg
    ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory

 Here is the conda environment:

$ conda list
# packages in environment at /home/jlee38/miniconda/envs/cpac:

atomicwrites              1.2.1                     <pip>
attrs                     18.2.0                    <pip>
backports                 1.0                      py27_0 
backports.shutil-get-terminal-size 1.0.0                     <pip>
boto3                     1.9.14                    <pip>
botocore                  1.12.14                   <pip>
cairo                     1.12.18                       6 
certifi                   2016.2.28                py27_0 
click                     7.0                       <pip>
configparser              3.5.0                     <pip>
cython                    0.26                     py27_0 
decorator                 4.1.2                    py27_0 
docutils                  0.14                      <pip>
enum34                    1.1.6                    py27_0 
expat                     2.1.0                         0 
fontconfig                2.11.1                        6 
freetype                  2.5.5                         1 
fs                        0.5.4                     <pip>
funcsigs                  1.0.2                     <pip>
future                    0.15.2                    <pip>
futures                   3.2.0                     <pip>
get_terminal_size         1.0.0                    py27_0 
icu                       54.1                          0 
indi-tools                0.0.6                     <pip>
ipython                   5.3.0                    py27_0 
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py27_0 
isodate                   0.6.0                     <pip>
jinja2                    2.7.2                    py27_0 
jmespath                  0.9.3                     <pip>
libgfortran               3.0.0                         1 
libiconv                  1.14                          0 
libpng                    1.6.17                        0 
libxml2                   2.9.4                         0 
lockfile                  0.12.2                    <pip>
lxml                      4.2.5                     <pip>
markupsafe                1.0                      py27_0 
matplotlib                1.4.3                np19py27_2 
mock                      2.0.0                     <pip>
more-itertools            4.3.0                     <pip>
networkx                  1.11                     py27_0 
nibabel                   2.3.0                     <pip>
nipype                    0.13.1                    <pip>
nose                      1.3.7                    py27_1 
numpy                     1.9.2                    py27_0 
openssl                   1.0.2l                        0 
pandas                    0.17.1               np19py27_0 
path.py                   10.3.1                   py27_0 
pathlib2                  2.3.0                    py27_0 
patsy                     0.5.0                     <pip>
pbr                       4.2.0                     <pip>
pexpect                   4.2.1                    py27_0 
pickleshare               0.7.4                    py27_0 
pip                       9.0.1                    py27_1 
pixman                    0.32.6                        0 
pluggy                    0.7.1                     <pip>
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.15                   py27_0 
prov                      1.5.2                     <pip>
psutil                    5.4.7                     <pip>
ptyprocess                0.5.2                    py27_0 
py                        1.6.0                     <pip>
py2cairo                  1.10.0                   py27_2 
pydotplus                 2.0.2                     <pip>
pygments                  2.2.0                    py27_0 
pygraphviz                1.5                       <pip>
pyparsing                 2.0.3                    py27_0 
pyqt                      4.11.4                   py27_4 
pytest                    3.8.1                     <pip>
python                    2.7.13                        0 
python-dateutil           2.6.1                    py27_0 
pytz                      2017.2                   py27_0 
pyyaml                    3.12                     py27_0 
qt                        4.8.7                         3 
rdflib                    4.2.2                     <pip>
readline                  6.2                           2 
s3transfer                0.1.13                    <pip>
scandir                   1.5                      py27_0 
scipy                     0.16.0               np19py27_0 
setuptools                36.4.0                   py27_1 
simplegeneric             0.8.1                    py27_1 
simplejson                3.16.0                    <pip>
sip                       4.18                     py27_0 
six                       1.10.0                   py27_0 
sqlite                    3.13.0                        0 
tk                        8.5.18                        0 
traitlets                 4.3.2                    py27_0 
traits                    4.6.0                    py27_0 
urllib3                   1.23                      <pip>
wcwidth                   0.1.7                    py27_0 
wheel                     0.29.0                   py27_0 
wxpython                  3.0.0.0                  py27_2 
wxpython-common           3.0.0.0                   <pip>
yaml                      0.1.6                         0 
zlib                      1.2.11                        0

**Comment by anibalsolon** [comment]
Hi @nimzodisaster

thank you for your contact. 

The command `conda install libgfortran` might do the trick. We will add this dependency for future C-PAC releases. 

Please let us know if you have further questions or problems.

**Comment by nimzodisaster** [comment]
That is the strange thing. I tried this. Indeed you will see in the environment I posted above that "libgfortran 3.0.0 1"  is listed. Yet when I load the cpac conda environment then call  'python setup.py install'
I'll get the `ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory` error.

**Comment by nrajamani3** [comment]
Hi Joshua, 
It may happen that there is a specific problem in finding the shared object file (.so.1). I would suggest trying to locate the file in your file system and then typing: 
$ ldconfig -n /path/to/shared/library. 
This essentially creates a symbolic link that will allow it be found. 
Two notes on this: 1. You will need to use sudo 
2. C-PAC’s installation webpage has the same solution mention for the same error, but concerning libgsl. You can also refer to that!

**Comment by nimzodisaster** [comment]
ldconfig didn't seem to work.

I saw this: https://github.com/travis-ci/travis-ci/issues/4816#issuecomment-142228535
And so tried:
```
conda install --yes numpy=1.9.1 scipy=0.16
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/jlee38/miniconda/envs/cpac:

The following packages will be DOWNGRADED:

    numpy: 1.9.2-py27_0 --> 1.9.1-py27_0

numpy-1.9.1-py 100% |#########################################################################################################| Time: 0:00:00  14.77 MB/s
```
But it didn't work still so I wanted to make sure everything that might have been downgraded got upgraded.

So I ran:
conda install scipy

```
conda install scipy
Fetching package metadata ...........
Solving package specifications: 

Package plan for installation in environment /home/jlee38/miniconda/envs/cpac:

The following NEW packages will be INSTALLED:

    blas:           1.0-mkl          
    cycler:         0.10.0-py27_0    
    intel-openmp:   2019.0-118       
    libgcc-ng:      8.2.0-hdf63c60_1 
    libgfortran-ng: 7.3.0-hdf63c60_0 
    libstdcxx-ng:   8.2.0-hdf63c60_1 
    mkl:            2019.0-118       
    pycairo:        1.10.0-py27_0    

The following packages will be UPDATED:

    matplotlib:     1.4.3-np19py27_2  --> 1.5.1-np111py27_0    
    numpy:          1.9.1-py27_0      --> 1.11.3-py27h3dfced4_4
    pandas:         0.17.1-np19py27_0 --> 0.23.4-py27h04863e7_0
    scipy:          0.16.0-np19py27_0 --> 1.1.0-py27hd20e5f9_0 

Proceed ([y]/n)? Y
```

and suddenly CPAC installer started working.

**Comment by anibalsolon** [comment]
Glad to know that it is working now!

Maybe what made the difference was the `libgfortran-ng`. We will keep an eye on this behavior to see if it causes more trouble.

Cheers
