### ISSUE TITLE
Error message when testing pipeline - "Issue info: 'Resource'"

### ISSUE THREAD

**Issue by Virginiaconde** [FCP-INDI/C-PAC#842]
Hi there C-PAC experts,

I'm trying to set a C-PAC pipeline to run Regional Homogeneity analyses of resting-state fMRI data. I have generated a subject list that seems to work, but whenever I try to test the pipeline I get the following error:

"There are issues with the current configuration which need to be resolved - please check to make sure the options you are running have the proper pre-requisites selected.  Issue Info: 'Resource'"

I don't seem to be able to find a solution for this either on the troubleshooting site of the C-PAC userguide or on the C-PAC forum / google group. I have attached the pipeline and the subject list files. I'd appreciate any input on this! 

Best wishes,
Virginia

[pipeline_config_TBI_group_reho.txt](https://github.com/FCP-INDI/C-PAC/files/2474053/pipeline_config_TBI_group_reho.txt)
[data_settings_TBI_reho.txt](https://github.com/FCP-INDI/C-PAC/files/2474054/data_settings_TBI_reho.txt)
[data_config_TBI_reho.txt](https://github.com/FCP-INDI/C-PAC/files/2474055/data_config_TBI_reho.txt)

**Comment by anibalsolon** [comment]
Hi Virginia,

thank you for reaching out!

Could you please inform us your C-PAC version?

Also, it is likely that an error was printed before the message "There are issues...", could you please provide us with this errors?

**Comment by Virginiaconde** [comment]
Hi Anibal,


thanks for your reply!


This is the only thing that gets printed in the terminal when testing the pipeline (with the GUI):


"

08:35:23: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
Checking subject list: /home/virgincr/TBI_group/data_config_TBI_reho.yml...
Subject list looks good!
'Resource'
an exception occurred


"


The Debug message appears *before* testing the pipeline.


Best wishes,

Virginia


________________________________
Fra: Anibal Sólon <notifications@github.com>
Sendt: 15. oktober 2018 18:14
Til: FCP-INDI/C-PAC
Kopi: Virginia Conde Ruiz; Author
Emne: Re: [FCP-INDI/C-PAC] Error message when testing pipeline - "Issue info: 'Resource'" (#842)


Hi Virginia,

thank you for reaching out!

Could you please inform us your C-PAC version?

Also, it is likely that an error was printed before the message "There are issues...", could you please provide us with this errors?

-

**Comment by Virginiaconde** [comment]
Hi,

sorry I just realised I didn't mention the C-PAC's version. It is the 1.1.0

Thanks in advance for your feedback!
Virginia


-------- Original Message --------
Subject: Re: [FCP-INDI/C-PAC] Error message when testing pipeline - "Issue info: 'Resource'" (#842)
From: Anibal Sólon
To: FCP-INDI/C-PAC
CC: Virginia Conde Ruiz ,Author


Hi Virginia,

thank you for reaching out!

Could you please inform us your C-PAC version?

Also, it is likely that an error was printed before the message "There are issues...", could you please provide us with this errors?

-

**Comment by anibalsolon** [comment]
Hi @Virginiaconde ,

I would recommend you to update to the last version of C-PAC.

Apart from that, you can try to run your pipeline. It is possible that this pipeline test is not properly working, because it requires some environment info that it is not present during the test. By running it, it will give us more information about what might be wrong.

**Comment by nx10** [comment]
Stale
