### ISSUE TITLE
childmind/cpac container fails to run

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#844]
The error is copied below. Looks like there is a problem with the version of nipype?

docker run -i --rm -v /myvolume/data/nfb-study/bids:/bids_dataset -v /myvolume/data/nfb-study/output:/outputs -v /tmp:/scratch childmind/c-pac:latest /bids_dataset /outputs participant --skip_bids_validator

/usr/local/miniconda/lib/python2.7/site-packages/matplotlib/**init**.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)
In file included from /usr/local/miniconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/local/miniconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/miniconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /root/.pyxbld/temp.linux-x86_64-2.7/pyrex/CPAC/network_centrality/thresh_and_sum.c:475:
/usr/local/miniconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
Traceback (most recent call last):
  File "/code/run.py", line 374, in <module>
Namespace(analysis_level='participant', aws_input_creds=None, aws_output_creds=None, bids_dir='/bids_dataset', bids_validator_config=None, data_config_file=None, disable_file_logging=False, mem_gb=None, mem_mb=None, n_cpus='1', output_dir='/outputs', participant_label=None, participant_ndx=None, pipeline_file='/cpac_resources/default_pipeline.yaml', save_working_dir=False, skip_bids_validator=True)
skipping bids-validator...

#### Running C-PAC
Number of participants to run in parallel: 1
Input directory: /bids_dataset
Output directory: /outputs/output
Working directory: /scratch/working
Crash directory: /outputs/crash
Log directory: /outputs/log
Remove working directory: True
Available memory: 6.0 (GB)
Available threads: 1
Number of threads for ANTs: 1
    from nipype.pipeline.plugins.callback_log import log_nodes_cb
ImportError: No module named callback_log

**Comment by anibalsolon** [comment]
Yes, there is a problem there, on the run.py script. I am going to upload a fix for this right now.

**Comment by anibalsolon** [comment]
It is updated now, it will work after a `docker pull` !

**Comment by dowd-a** [comment]
The pipeline builds now, but there is a runtime error. It looks like there is an issue with the repetition time key.


181023-00:19:16,27 nipype.workflow INFO:
	 [Node] Setting-up "resting_preproc_sub-M10978008_ses-NFB3.scan_params_0" in "/scratch/working/resting_preproc_sub-M10978008_ses-NFB3/_scan_task-mask/scan_params_0".
181023-00:19:16,35 nipype.workflow INFO:
	 [Node] Running "scan_params_0" ("CPAC.utils.function.Function")
181023-00:19:16,38 nipype.workflow WARNING:
	 [Node] Error on "resting_preproc_sub-M10978008_ses-NFB3.scan_params_0" (/scratch/working/resting_preproc_sub-M10978008_ses-NFB3/_scan_task-mask/scan_params_0)
181023-00:19:17,579 nipype.workflow ERROR:
	 Node scan_params_0.c1 failed to run on host 1ae6c06cb718.
181023-00:19:17,580 nipype.workflow ERROR:
	 Saving crash info to /outputs/crash/crash-20181023-001917-root-scan_params_0.c1-d78ff97a-0267-403c-bafe-19b0adad5972.pklz
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/function.py", line 158, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/utils/utils.py", line 1521, in get_scan_params
    TR = float(check(params_dct, subject_id, scan, 'TR', False))
  File "/code/CPAC/utils/utils.py", line 1402, in check
    if isinstance(params_dct[val], dict):
KeyError: 'TR'

**Comment by anibalsolon** [comment]
Hi @dowd-a 

It looks like it is a problem in your data config yaml, related to the scan parameters. Could you please provide us with your data config file?

The scan parameters should be defined as this example: https://fcp-indi.github.io/docs/user/subject_list_config.html#data-yaml-fields

**Comment by dowd-a** [comment]
I ran the pipeline in a docker container using the following command:

docker run -i --rm -v /myvolume/data/nfb-study/bids:/bids_dataset -v /myvolume/data/nfb-study/output:/outputs -v /tmp:/scratch childmind/c-pac:latest /bids_dataset /outputs participant

It automatically created a yaml file with entries that look like this:

- anat:
    scan: /bids_dataset/sub-M10978008/ses-NFB3/anat/sub-M10978008_ses-NFB3_T1w.nii.gz
    scan_parameters: &id001 {!!python/unicode 'RepetitionTime': 1000}
  creds_path: null
  func:
    task-mask:
      scan: /bids_dataset/sub-M10978008/ses-NFB3/func/sub-M10978008_ses-NFB3_task-mask_bold.nii.gz
      scan_parameters: &id002
        !!python/unicode 'EchoTime': 0.03
        !!python/unicode 'EffectiveEchoSpacing': 0.0004699954880433148
        !!python/unicode 'FlipAngle': 90.0
        !!python/unicode 'MagneticFieldStrength': 3.0
        !!python/unicode 'Manufacturer': !!python/unicode 'SIEMENS'
        !!python/unicode 'ManufacturerModelName': !!python/unicode 'TrioTim'
        !!python/unicode 'PhaseEncodingDirection': !!python/unicode 'j-'
        !!python/unicode 'RepetitionTime': 2.0
        !!python/unicode 'SliceEncodingDirection': !!python/unicode 'k'
        !!python/unicode 'SliceTiming': [0.0, 1.032, 0.06, 1.095, 0.12, 1.155, 0.183,
          1.215, 0.243, 1.278, 0.303, 1.338, 0.365, 1.398, 0.425, 1.46, 0.485, 1.52,
          0.548, 1.58, 0.608, 1.642, 0.668, 1.702, 0.73, 1.763, 0.79, 1.825, 0.85,
          1.885, 0.913, 1.945, 0.972]
        !!python/unicode 'TaskName': !!python/unicode 'mask'
    task-morald:
      scan: /bids_dataset/sub-M10978008/ses-NFB3/func/sub-M10978008_ses-NFB3_task-morald_bold.nii.gz
      scan_parameters: &id003
        !!python/unicode 'EchoTime': 0.03
        !!python/unicode 'EffectiveEchoSpacing': 0.0004699954880433148
        !!python/unicode 'FlipAngle': 90.0
        !!python/unicode 'MagneticFieldStrength': 3.0
        !!python/unicode 'Manufacturer': !!python/unicode 'SIEMENS'
        !!python/unicode 'ManufacturerModelName': !!python/unicode 'TrioTim'
        !!python/unicode 'PhaseEncodingDirection': !!python/unicode 'j-'
        !!python/unicode 'RepetitionTime': 2.0
        !!python/unicode 'SliceEncodingDirection': !!python/unicode 'k'
        !!python/unicode 'SliceTiming': [0.0, 1.032, 0.06, 1.095, 0.12, 1.155, 0.182,
          1.215, 0.243, 1.278, 0.303, 1.338, 0.365, 1.398, 0.425, 1.46, 0.485, 1.52,
          0.548, 1.58, 0.608, 1.642, 0.668, 1.702, 0.73, 1.762, 0.79, 1.825, 0.85,
          1.885, 0.913, 1.945, 0.972]
        !!python/unicode 'TaskName': !!python/unicode 'morald'
    task-msit:
      scan: /bids_dataset/sub-M10978008/ses-NFB3/func/sub-M10978008_ses-NFB3_task-msit_bold.nii.gz
      scan_parameters: &id004
        !!python/unicode 'EchoTime': 0.03
        !!python/unicode 'EffectiveEchoSpacing': 0.0004699954880433148
        !!python/unicode 'FlipAngle': 90.0
        !!python/unicode 'MagneticFieldStrength': 3.0
        !!python/unicode 'Manufacturer': !!python/unicode 'SIEMENS'
        !!python/unicode 'ManufacturerModelName': !!python/unicode 'TrioTim'
        !!python/unicode 'PhaseEncodingDirection': !!python/unicode 'j-'
        !!python/unicode 'RepetitionTime': 2.0
        !!python/unicode 'SliceEncodingDirection': !!python/unicode 'k'
        !!python/unicode 'SliceTiming': [0.0, 1.032, 0.06, 1.095, 0.12, 1.155, 0.183,
          1.215, 0.243, 1.278, 0.303, 1.338, 0.365, 1.398, 0.425, 1.46, 0.485, 1.52,
          0.548, 1.58, 0.608, 1.642, 0.668, 1.702, 0.73, 1.762, 0.79, 1.825, 0.85,
          1.885, 0.913, 1.945, 0.972]
        !!python/unicode 'TaskName': !!python/unicode 'msit'
    task-peer_run-2:
      scan: /bids_dataset/sub-M10978008/ses-NFB3/func/sub-M10978008_ses-NFB3_task-peer_run-2_bold.nii.gz
      scan_parameters: &id005
        !!python/unicode 'EchoTime': 0.03
        !!python/unicode 'EffectiveEchoSpacing': 0.0004699954880433148
        !!python/unicode 'FlipAngle': 90.0
        !!python/unicode 'MagneticFieldStrength': 3.0
        !!python/unicode 'Manufacturer': !!python/unicode 'SIEMENS'
        !!python/unicode 'ManufacturerModelName': !!python/unicode 'TrioTim'
        !!python/unicode 'PhaseEncodingDirection': !!python/unicode 'j-'
        !!python/unicode 'RepetitionTime': 2.0
        !!python/unicode 'SliceEncodingDirection': !!python/unicode 'k'
        !!python/unicode 'SliceTiming': [0.0, 1.032, 0.06, 1.095, 0.12, 1.155, 0.182,
          1.215, 0.243, 1.278, 0.303, 1.338, 0.365, 1.398, 0.425, 1.46, 0.485, 1.52,
          0.548, 1.58, 0.608, 1.642, 0.668, 1.702, 0.73, 1.762, 0.79, 1.825, 0.85,
          1.885, 0.913, 1.945, 0.972]
        !!python/unicode 'TaskName': !!python/unicode 'peer'
    task-test:
      scan: /bids_dataset/sub-M10978008/ses-NFB3/func/sub-M10978008_ses-NFB3_task-test_bold.nii.gz
      scan_parameters: &id006
        !!python/unicode 'EchoTime': 0.03
        !!python/unicode 'EffectiveEchoSpacing': 0.0004699954880433148
        !!python/unicode 'FlipAngle': 90.0
        !!python/unicode 'MagneticFieldStrength': 3.0
        !!python/unicode 'Manufacturer': !!python/unicode 'SIEMENS'
        !!python/unicode 'ManufacturerModelName': !!python/unicode 'TrioTim'
        !!python/unicode 'PhaseEncodingDirection': !!python/unicode 'j-'
        !!python/unicode 'RepetitionTime': 2.0
        !!python/unicode 'SliceEncodingDirection': !!python/unicode 'k'
        !!python/unicode 'SliceTiming': [0.0, 1.032, 0.06, 1.095, 0.12, 1.155, 0.183,
          1.215, 0.243, 1.278, 0.303, 1.338, 0.365, 1.398, 0.425, 1.46, 0.485, 1.52,
          0.548, 1.58, 0.608, 1.642, 0.668, 1.702, 0.73, 1.763, 0.79, 1.825, 0.85,
          1.885, 0.913, 1.945, 0.972]
        !!python/unicode 'TaskName': !!python/unicode 'test'
    task-train:
      scan: /bids_dataset/sub-M10978008/ses-NFB3/func/sub-M10978008_ses-NFB3_task-train_bold.nii.gz
      scan_parameters: &id007
        !!python/unicode 'EchoTime': 0.03
        !!python/unicode 'EffectiveEchoSpacing': 0.0004699954880433148
        !!python/unicode 'FlipAngle': 90.0
        !!python/unicode 'MagneticFieldStrength': 3.0
        !!python/unicode 'Manufacturer': !!python/unicode 'SIEMENS'
        !!python/unicode 'ManufacturerModelName': !!python/unicode 'TrioTim'
        !!python/unicode 'PhaseEncodingDirection': !!python/unicode 'j-'
        !!python/unicode 'RepetitionTime': 2.0
        !!python/unicode 'SliceEncodingDirection': !!python/unicode 'k'
        !!python/unicode 'SliceTiming': [0.0, 0.06, 0.12, 0.182, 0.242, 0.302, 0.365,
          0.425, 0.485, 0.548, 0.608, 0.668, 0.73, 0.79, 0.85, 0.912, 0.972, 1.032,
          1.095, 1.155, 1.215, 1.278, 1.337, 1.397, 1.46, 1.52, 1.58, 1.642, 1.702,
          1.762, 1.825, 1.885, 1.945]
        !!python/unicode 'TaskName': !!python/unicode 'train'
  site_id: site-none
  subject_id: sub-M10978008
  unique_id: ses-NFB3

I think the issue might be that the yaml file created use the key 'RepetitionTime', while scan_params is looking for the key 'TR'.

**Comment by anibalsolon** [comment]
Hi @dowd-a  

Could you please provide us the steps that you took to generate this data config file?
If you have the time, can we skype to nail this down?

Thank you

**Comment by dowd-a** [comment]
Hi @anibalsolon 

I pulled the latest docker image (docker pull childmind/c-pac:latest). And then ran CPAC for a single participant using the following command:

docker run -i --rm -v /myvolume/data/nfb-study/bids:/bids_dataset -v /myvolume/data/nfb-study/output:/outputs -v /tmp:/scratch childmind/c-pac:latest /bids_dataset /outputs participant

where nfb-study/bids is the bids dataset I'm using.

And sure I'm available to Skype.

Thanks

**Comment by anibalsolon** [comment]
Awesome, thanks @dowd-a !

Please add me in Skype and let me know when you have a moment so we can look into your issue: https://join.skype.com/invite/F7mXSIzJpnOY

**Comment by anibalsolon** [comment]
Thank you for meeting me @dowd-a 

While we work in a fix for your problem, I would recommend you to generate the data config manually.

To do so, you need to install C-PAC on your server: `pip install --user git+git://github.com/FCP-INDI/C-PAC.git`

and create a file named `data_settings.yaml` containing:

```dataFormat: BIDS
bidsBaseDir: /myvolume/data/nfb-study/bids
anatomicalTemplate: 
functionalTemplate: 
outputSubjectListLocation: /myvolume/data/nfb-study/bids
subjectListName: nfb-study
anatomical_scan: None
awsCredentialsFile: None
scanParametersCSV: None
brain_mask_template: None
fieldMapPhase: None
fieldMapMagnitude: None
subjectList: None
exclusionSubjectList: None
siteList: None
exclusionSiteList: None
sessionList: None
exclusionSessionList: None
scanList: None
exclusionScanList: None```

from this file, you can generate your data_config:

`cpac utils data_config build data_settings_test.yaml`

it will generate a file `/myvolume/data/nfb-study/bids/data_config_nfb-study.yml`, but pointing to the paths from your server
so now you can run docker using:

```docker run -i --rm -v /myvolume/data/nfb-study/bids:/myvolume/data/nfb-study/bids -v /myvolume/data/nfb-study/output:/outputs -v /tmp:/scratch childmind/c-pac:latest /myvolume/data/nfb-study/bids /outputs participant --data_config_file /myvolume/data/nfb-study/bids/data_config_nfb-study.yml```

in this way, the paths will be valid.

A fix will be available tomorrow. Please let me know if the outcome!

**Comment by anibalsolon** [comment]
Hi @dowd-a 

We've updated that docker image, so you can run `docker pull childmind/c-pac:latest` to get the last C-PAC version. Your problem should be solved now!

Please let us know if there are other questions or problems during your analysis.

**Comment by dowd-a** [comment]
Hi @anibalsolon 

I tried pulling the updated docker image and running C-PAC again, but I got another key error.

181101-00:43:02,605 nipype.workflow WARNING:
	 [Node] Error on "resting_preproc_sub-M10978008_ses-NFB3.scan_params_0" (/scratch/working/resting_preproc_sub-M10978008_ses-NFB3/_scan_task-train/scan_params_0)
181101-00:43:04,112 nipype.workflow ERROR:
	 Node scan_params_0.c0 failed to run on host bf7e32dbda18.
181101-00:43:04,112 nipype.workflow ERROR:
	 Saving crash info to /outputs/crash/crash-20181101-004304-root-scan_params_0.c0-95c7026a-f5eb-43d2-8716-c01fefce0b19.pklz
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/function.py", line 158, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/utils/utils.py", line 1571, in get_scan_params
    False))
  File "/code/CPAC/utils/utils.py", line 1402, in check
    if isinstance(params_dct[val], dict):
KeyError: 'reference'

I think it's still an issue with the way the data config yml file is created in the docker container. I checked the data config file and there is no 'reference' key.

**Comment by anibalsolon** [comment]
Hi @dowd-a 

Now it is supposed to work! I've tested it with a BIDS dataset that had the same problem, so now it must be okay. Please `docker pull childmind/c-pac:latest` and run it again.

Let us know!

**Comment by sgiavasis** [comment]
Noting here that the official C-PAC container is available via:

`docker pull fcpindi/c-pac:latest`
