### ISSUE TITLE
Anatomical only preprocessing

### ISSUE THREAD

**Issue by dowd-a** [FCP-INDI/C-PAC#883]
I would like to configure the C-PAC pipeline to run only anatomical preprocessing, but I'm having some trouble. There is no flag in the pipeline config file to shut off all functional processing. I've been trying to selectively turn off some of the functional processing, but C-PAC keeps breaking due to various dependencies. Is there a clean way to only do anatomical preprocessing?

**Comment by anibalsolon** [comment]
Hi @dowd-a 

Currently, we do not have this functionality. We may include it in the next version! When we develop this functionality, we can send you a beta version so you can test it.

Thank you

**Comment by dowd-a** [comment]
Okay, thanks for looking into it.

**Comment by sgiavasis** [comment]
This was included in 1.4.0. 👍
