### ISSUE TITLE
Unable to run 2 types of skull stripping in parallel

### ISSUE THREAD

**Issue by dowd-a** [FCP-INDI/C-PAC#885]
I'm trying to run two different types of skull stripping in parallel. On the C-PAC documentation page, it says you can select this option in the gui. I would like to run it in a container using a pipeline config file. I tried entering it like this in the config file:

`skullstrip_option: [AFNI, BET]`

But I got an error:

Traceback (most recent call last):
  File "/code/run.py", line 392, in <module>
    plugin='MultiProc', plugin_args=plugin_args)
  File "/code/CPAC/pipeline/cpac_runner.py", line 487, in run
    p_name, plugin, plugin_args)
  File "/code/CPAC/pipeline/cpac_pipeline.py", line 547, in prep_workflow
    workflow.connect(node, out_file, anat_preproc, 'inputspec.anat')
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 155, in connect
    self._check_nodes(newnodes)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/workflows.py", line 727, in _check_nodes
    'Duplicate node name "%s" found.' % node.name)
IOError: Duplicate node name "anat_preproc_0" found.

What is the proper syntax for this?

**Comment by anibalsolon** [comment]
Hi @dowd-a 

This is the correct syntax. I will check what is happening, it looks like a node naming problem.

**Comment by dowd-a** [comment]
Hi @anibalsolon 

Did you figure out what the issue was? Does C-PAC have this capability (running 2 skull stripping methods in parallel) right now?

**Comment by anibalsolon** [comment]
Hi @dowd-a 

Yes, it is working, but in the dev branch.

Could you please inform me if you are running with docker or singularity? So I can send you a "nightly build" version.

**Comment by anibalsolon** [comment]
Hi @dowd-a 

Could you please try this image? I've created it based on the branch `1.4.0_dev`.

https://s3.amazonaws.com/anibalsolon-research/cmi/c-pac/c-pac-1.4.0_dev-0ab249c0f5cd69518f8c162207bfa723141675cb.simg

Please let me know if it works now!

**Comment by anibalsolon** [comment]
Hi @dowd-a 

Have you had the chance to test this singularity image?

Thank you

**Comment by sgiavasis** [comment]
This has been resolved. If the issue recurs, please feel free to re-open.
