### ISSUE TITLE
Drop leaf nodes feature in favor of pool's resource direct reference

### ISSUE THREAD

**Issue by anibalsolon** [FCP-INDI/C-PAC#888]
It is about `strat.set_leaf_properties` and `strat.get_leaf_properties`.

Although it is "easier" to just get the leaf nodes, it is really hard to be sure what, at a point in the pipeline, the leaf currently is. The ideal code explicitly references the object from the resource pool, to avoid confusion/cognitive load.

**Comment by sgiavasis** [comment]
Obviated via v1.8.
