### ISSUE TITLE
Docker image GUI on Mac

### ISSUE THREAD

**Issue by chrisfoulon** [FCP-INDI/C-PAC#893]
Hi! 

I tried to run the GUI with the docker image on Mac using the instructions on GitHub. XQuartz was already installed, I authorized the connections from network clients, added the IP address to the xhost, and finally, I tried to run the command: 
`docker run -i --rm \
        --privileged \
        -e DISPLAY=$ip:0 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /tmp:/scratch \
        -v /Users/filo/data/ds005:/bids_dataset \
        -v /Users/filo/outputs:/outputs \
		bids/cpac \
		/bids_dataset /outputs GUI`

changing the directories with mine.

I got the following error: 
`No protocol specified
Namespace(analysis_level='gui', aws_input_creds=None, aws_output_creds=None, bids_dir='/bids_dataset', bids_validator_config=None, data_config_file=None, disable_file_logging=False, mem_gb=None, mem_mb=None, n_cpus='1', output_dir='/outputs', participant_label=None, participant_ndx=None, pipeline_file='/cpac_resources/default_pipeline.yaml', save_working_dir=False, skip_bids_validator=False)
Starting CPAC GUI
Unable to access the X Display, is $DISPLAY set properly?`

The XQuartz display doesn't seem to like the ip address, I also tried directly with the $DISPLAY variable but it produces the same error.

Thank you in advance for your help,
Chris.

**Comment by chrisfoulon** [comment]
Oh I verified that the IP was there, and I am connected through ethernet. So I do have an IP, but it seems not to be ok to run the GUI.

**Comment by anibalsolon** [comment]
Hi @chrisfoulon 

Is it still an issue? Let me know and we can schedule a one-on-one to debug this via Skype/TeamViewer.

**Comment by chrisfoulon** [comment]
I didn't have the occasion to try it since then but I just tried with the new docker image from fcpindi and I had the same kind of error. 

I did:
`ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
echo  $ip
docker run -i --rm --privileged -e DISPLAY=$ip:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /tmp:/scratch -v /Users/chris/test/bids_test/sourcedata:/bids_dataset -v /Users/chris/test/bids_test/derivatives:/outputs fcpindi/c-pac /bids_dataset /outputs GUI`

And I tried to echo the $DISPLAY variable: 
`echo $DISPLAY
/private/tmp/com.apple.launchd.4m1bAfecxn/org.macosforge.xquartz:0`

I don't really if the value is good or wrong though. 

I don't have the use of the GUI anymore but if you want to try to debug it we can do it to avoid having the same problem with the users. 

Thanks!

**Comment by shnizzedy** [comment]
Deprecated by #1262
