### ISSUE TITLE
Wrong legend and label for motion plot 

### ISSUE THREAD

**Issue by haililihai** [FCP-INDI/C-PAC#895]
https://github.com/FCP-INDI/C-PAC/blob/7befcf9c706052fb7c37567e378cca9add60d7a9/CPAC/qc/utils.py#L1196

The first 6 parameters generated by 3dvolreg are "roll pitch yaw dS dL dP", so I think, the sequence of titles, legend, and labels are wrong.

**Comment by anibalsolon** [comment]
Thank you, Lei!

**Comment by anibalsolon** [comment]
Hi @haililihai 

Thank you for the feedback! We are going to check it and address it in the next release.

Best

**Comment by anibalsolon** [comment]
Hi @haililihai 

The new release is out, and this plot is fixed now!

Thank you
