### ISSUE TITLE
Install c-pac ImportError: No module named numpy.distutils.misc_util

### ISSUE THREAD

**Issue by poppintiger** [FCP-INDI/C-PAC#896]
Hi, I was trying install capc on ubuntu 16.04, and when I got to the final step by runing:
`python setup.py install`

It shows the error:

> Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from build_helpers import INFO_VARS
  File "/tmp/C-PAC/build_helpers.py", line 28, in <module>
    from numpy.distutils.misc_util import appendpath
ImportError: No module named numpy.distutils.misc_util

So, but I have install the numpy by following the instructions, how can I deal with this problem?

**Comment by poppintiger** [comment]
@nrajamani3  Hi, thanks for your replay and I still have the problem.
I have followed your advice by print the system path:
` >>>import sys 
          sys.path
‘
'
['', '/root/miniconda/envs/cpac/lib/python27.zip', '/root/miniconda/envs/cpac/lib/python2.7', '/root/miniconda/envs/cpac/lib/python2.7/plat-linux2', '/root/miniconda/envs/cpac/lib/python2.7/lib-tk', '/root/miniconda/envs/cpac/lib/python2.7/lib-old', '/root/miniconda/envs/cpac/lib/python2.7/lib-dynload', '/root/miniconda/envs/cpac/lib/python2.7/site-packages', '/root/miniconda/envs/cpac/lib/python2.7/site-packages/wx-3.0-gtk2']`

**Comment by nrajamani3** [comment]
Hello @poppintiger,
Have you solved this issue - are you looking for more help?

**Comment by sgiavasis** [comment]
Closing this issue- please re-open if you are still having difficulty.
