### ISSUE TITLE
Docker IOError

### ISSUE THREAD

**Issue by poppintiger** [FCP-INDI/C-PAC#899]
When I run on Docker:
`docker run -i --rm \
-v /home/admin123/mri/caltech_51460/rest/:/bids_dataset \
-v /home/admin123/mri/caltech_51460/rest:/outputs \
-v /tmp:/scratch \
fcpindi/c-pac:latest /bids_dataset /outputs participant`

It showed this error:
> Namespace(analysis_level='participant', aws_input_creds=None, aws_output_creds=None, bids_dir='/bids_dataset', bids_validator_config=None, data_config_file=None, disable_file_logging=False, mem_gb=None, mem_mb=None, n_cpus='1', output_dir='/outputs', participant_label=None, participant_ndx=None, pipeline_file='/cpac_resources/default_pipeline.yaml', save_working_dir=False, skip_bids_validator=False)

> Running BIDS validator
/usr/lib/node_modules/bids-validator/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

> SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/bids-validator/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

> Running C-PAC
Number of participants to run in parallel: 1
Input directory: /bids_dataset
Output directory: /outputs/output
Working directory: /scratch/working
Crash directory: /outputs/crash
Log directory: /outputs/log
Remove working directory: True
Available memory: 6.0 (GB)
Available threads: 1
Number of threads for ANTs: 1
Traceback (most recent call last):
  File "/code/run.py", line 307, in <module>
    (file_paths, config) = collect_bids_files_configs(args.bids_dir, args.aws_input_creds)
  File "/code/bids_utils.py", line 497, in collect_bids_files_configs
    " directory, and that it is not empty.".format(bids_dir))
IOError: Didn't find any files in %s. Please verify that the path is typed correctly, that you have read access to the directory, and that it is not empty.

So.what is the directory is? Is the file contain the rest image   rest.nii.gz?

**Comment by sgiavasis** [comment]
Hi @poppintiger ,

Do you still get this error if you skip the BIDS validator?
You can do this by providing the `--skip_bids_validator` flag.

Best,
Steve

**Comment by poppintiger** [comment]
@sgiavasis Hi，thanks for your replay and I still have the problem.
I followed your advice, and add the flag: 
`docker run   -i   --rm --skip_bids_validator \
>         -v /home/admin123/mri/CMU_50644:/bids_dataset \
>         -v /home/admin123/mri/:/outputs \
>         -v /tmp:/scratch \
>          fcpindi/c-pac:latest /bids_dataset /outputs participant
But,it shows the following error:

`  unknown flag: --skip_bids_validator
   See 'docker run --help'.``

Did I write it wrong?

**Comment by sgiavasis** [comment]
This might be a placement thing- try putting it after "participant"?

**Comment by sgiavasis** [comment]
Hi @poppintiger,

Checking in on this issue- any update?

**Comment by sgiavasis** [comment]
Closing this issue- please re-open if you are still having any difficulty.
