### ISSUE TITLE
Lesion masking strategy for T1w registration with ANTs

### ISSUE THREAD

**Issue by chrisfoulon** [FCP-INDI/C-PAC#900]
Add the possibility to use a lesion/ROI mask to improve the registration of lesioned T1w images.
If C-PAC detects a lesion/ROI mask in BIDS folders and that ANTs is selected as the registration strategy, it will use this mask during the normalization.

**Comment by sgiavasis** [comment]
We're going to fold this into 1.4.2, which is slated for the next 1-2 weeks.

**Comment by sgiavasis** [comment]
This is now in v1.4.3.
