### ISSUE TITLE
Skull stripping strategies exception not caught

### ISSUE THREAD

**Issue by chrisfoulon** [FCP-INDI/C-PAC#902]
Hi,

I just noticed a problem with an uncaught exception in the cpac_pipeline.py. 
If I modify the pipeline and set a skull_stripping method that is not handled by cpac it will continue the pipeline and crash when it realizes that the anatomical_brain resource has not been generated. Like I could put "ANTS" in the pipeline config of even "afni" in lowercase, and it would throw an error only mentioning the anatomical_brain missing resource. 
For now, it's basically: 

if 'brain_mask' in sub_dict.keys():
  create anat preproc
 if "AFNI" in c.skullstrip_option:
  create anat preproc
 if "BET" in c.skullstrip_option and 'anat_preproc' not in nodes:
  create anat preproc
continue pipeline

I think you planned to modify the cpac_pipeline a lot soon, do you plan to fix that? 

Thanks! 

Chris.

**Comment by sgiavasis** [comment]
Hi @chrisfoulon,

Thanks for bringing this up!
Yes, revamping the pipeline generation is on the slate (via the Quick-PACS project). Taking note of this.

Steve

**Comment by sgiavasis** [comment]
I've put a small check for this, for the time being. It will be in v1.4.1.

> Exception: 
>
> [!] C-PAC says: Your skull-stripping method options setting does not include either 'AFNI' or 'BET'.
>
> Options you provided:
> skullstrip_option: ['cpac', 'life']
