### ISSUE TITLE
v1.4 singularity container fails on thresh_and_sum

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#910]
here is the error:

Building module CPAC.network_centrality.thresh_and_sum failed: ["CompileError: command 'gcc' failed with exit status 1\n"]

Why are we still using thresh_and_sum??? this is deprecated code

**Comment by sgiavasis** [comment]
Thank you for reporting. This has been fixed and will be in the v1.4.1 release.

**Comment by sgiavasis** [comment]
1.4.1 is out and this has been resolved. :)
