### ISSUE TITLE
singularity container does not write to s3

### ISSUE THREAD

**Issue by ccraddock** [FCP-INDI/C-PAC#911]
If i pass an S3 path to the output, the data gets written to a local directory s3:/fcp-indi ... rather than being written to s3.

-cc

**Comment by sgiavasis** [comment]
Thank you @ccraddock - good timing on these.
Will address.

**Comment by ccraddock** [comment]
The problem writing to s3 also exists with 1.3, my guess is it may have to do with a change to the datasink in nipype.

**Comment by sgiavasis** [comment]
1.4.1 is out and this has been resolved.
