### ISSUE TITLE
Singularity build (1.4.0): 3dSkullStrip fails

### ISSUE THREAD

**Issue by PaulZhutovsky** [FCP-INDI/C-PAC#918]
Dear all,

I just build a new singularity (v2.5.2) image with the newest C-PAC version (1.4.0) by running:
`singularity build c-pac-1.4.0.simg docker://fcpindi/c-pac:release-v1.4.0`

During the building I saw the following warning being displayed:
`WARNING:` Warning handling tar header: Can't create 'usr/lib/x86_64-linux-gnu/libgsl.so.19'

A quick search pointed me to the following issue in [MRIQC](https://github.com/poldracklab/mriqc/issues/648) where it became apparent that singularity wasn't properly creating a soft-link for libgsl.so.19 which would make afni's `3dSkullStrip` fail. That is indeed the case here as well:
`singularity exec c-pac-1.4.0.simg 3dSkullStrip
3dSkullStrip: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or  directory`

It would be great if this issue could be fixed! 
Thanks for developing C-PAC!

Cheers,
Paul

**Comment by anibalsolon** [comment]
Hi @PaulZhutovsky 

If you wish to build your Singularity image, we have a receipt in our repository:
https://github.com/FCP-INDI/C-PAC/blob/master/Singularity

that basically creates these soft links.

You can also download from singularity hub:
```
singularity pull shub://FCP-INDI/C-PAC
```

Let me know how it goes!

**Comment by PaulZhutovsky** [comment]
Hey!

Thanks for your help @anibalsolon! Using a recipe file for singularity does not seem to work for me since it requires sudo rights which I don't have on the system I'm working on.

But pulling from singularity hub worked with no problems!

Thanks!
Paul

**Comment by anibalsolon** [comment]
Great to know @PaulZhutovsky ! I've forgot the sudo issue.

Let us know if you have any questions.
