### ISSUE TITLE
Improve working directory deletion

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#944]
C-PAC won't clear working directories (when directed to do so), if the pipeline crashes.

**Comment by anibalsolon** [comment]
if it crashes, should it remove only if `removeWorkingDir` is true?

**Comment by sgiavasis** [comment]
Yes- sorry, should have specified this. This is for removeWorkingDir only.

**Comment by sgiavasis** [comment]
This has been resolved, and will be in 1.4.2.
