### ISSUE TITLE
Func TS should only be resampled once for SCA (if same res)

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#945]
Example, if there are 4 ROI nifti files set for SCA, and they all are in the same resolution, when C-PAC goes to resample the functional to be in the ROI's space, it will resample it four separate times (redundant).

(Look into 3dcompare?)

**Comment by sgiavasis** [comment]
With the added Neuroparc atlases, TS resampling all at the same time (when given many CPUs) often leads to a memory crash (FLIRT Killed).

Possibly move resampling to beginning of pipeline, check the dimensions/resolutions of the given atlases first, and only resample to that set (most of the time the atlases are same sizes/dimensions). Then put resampled functionals into resource pool.

@ccraddock any idea why we don't resample the atlases to the functional instead?

**Comment by SucyLi** [comment]
To fix  
- Functional TS duplicated resampling with same ROI dimensions 
- Functional TS duplicated resampling with different analyses, eg. Avg, DualReg, MultReg

**Comment by sgiavasis** [comment]
This has been resolved in v1.6.2.
