### ISSUE TITLE
Key Error: Grey Matter

### ISSUE THREAD

**Issue by cbin-cnl** [FCP-INDI/C-PAC#962]
When I try and run nuisance regression with GSR, I keep getting the following error:

```
File "/code/CPAC/GUI/interface/pages/nuisance.py", line 792, in compile_selector
selector['GreyMatter'].update(self.compile_selector_summary(self.data_controls['GreyMatter']))
KeyError: 'GreyMatter'
```
I think the following line may be referencing the GreyMatter parameters and trying to pull in those values for the GSR parameter. 

https://github.com/FCP-INDI/C-PAC/blob/b90fac7666f93cc7dc4413ae8b9a4d37256ce58f/CPAC/GUI/interface/pages/nuisance.py#L792

**Comment by anibalsolon** [comment]
Hi @cbin-cnl 

Thanks for reaching out!
Yes, it should be GlobalSignal on this line. We've fixed and will make the fix available on our next release.

Meanwhile, you can active GlobalSignal manually in the pipeline config, using:
```
   GlobalSignal:
     summary: Mean
```

**Comment by cbin-cnl** [comment]
Thanks Anibal
