### ISSUE TITLE
Add option to choose interpolation method

### ISSUE THREAD

**Issue by sgiavasis** [FCP-INDI/C-PAC#984]
During structural registration to a template, linear interpolation is the default rather than lanszos sinc— it adds substantial blurring/noise.

It will require a new parameter on the workflow from `CPAC/registration/registration.py` to allow the interpolation parametrization on the YAML file, for ANTS (`create_wf_calculate_ants_warp`) and FSL (`create_fsl_flirt_linear_reg`).

ANTS provides this set of options:
```
     -n, --interpolation Linear
                         NearestNeighbor
                         MultiLabel[<sigma=imageSpacing>,<alpha=4.0>]
                         Gaussian[<sigma=imageSpacing>,<alpha=1.0>]
                         BSpline[<order=3>]
                         CosineWindowedSinc
                         WelchWindowedSinc
                         HammingWindowedSinc
                         LanczosWindowedSinc
                         GenericLabel[<interpolator=Linear>]
```

And FLIRT provides these options:
```
-interp {trilinear,nearestneighbour,sinc,spline}  (final interpolation: def - trilinear)
```

I would suggest providing `trilinear`, `spline` and `sinc` (`Linear`, `BSpline`, `LanczosWindowedSinc`) and keep it a single pipeline parameter (for the YAML file) for now.

**Comment by anibalsolon** [comment]
@sgiavasis @HechengJin0 details provided.

**Comment by sgiavasis** [comment]
This is now in v1.5.0.
